### ISSUE TITLE
App Insights - 404 from Android image

### ISSUE THREAD

**Issue by bradystroud** [SSWConsulting/SSW.Website#1001]
![image](https://github.com/SSWConsulting/SSW.Website/assets/38869720/eafa6d2f-ce62-4ffb-958b-5a007300220a)
**Figure: 404 for weird image**

I am guessing Chrome on Androids looks for this image but we don't have it...

```[tasklist]
### Tasks
- [ ] Investigate this 404 - What is causing it?
- [ ] Fix
```

**Comment by jackreimers** [comment]
We have tried adding a manifest.json file and a link tag in the head of index.html that point to the favicon, but this has not resolved the issue.

It seems to be a crawler requesting the image as App Insights reports it as a Linux machine (with identical version numbers) with an unspecified browser on every request.

As per my discussion with @bradystroud I am going to stop working on this and move onto other issues, in the meantime we will ask around to see if anyone knows what is causing the issue.

**Comment by jackreimers** [comment]
cc: @bradystroud 

I was able to resolve some of the issues by updating the favicon, but there are still requests for non-existant files being logged in App Insights. 

These requests are likely from crawlers and are not affecting any users so this issue will be closed.
