### ISSUE TITLE
Quick Fix - Partytown CORS Errors

### ISSUE THREAD

**Issue by Harry-Ross** [SSWConsulting/SSW.Website#1005]
Since implementing web workers, there has been a high volume of CORS errors in the console.

**Comment by camillars** [comment]
Hi @Harry-Ross 
as per our conversation, you can remove this tag in GTM:
![image](https://github.com/SSWConsulting/SSW.Website/assets/53064613/f9cc0f66-de7d-4381-bb23-32e220717a07)

Thanks.
