### ISSUE TITLE
📄 Migrate pages - SSW Style guide, SSW logos, SSW fonts

### ISSUE THREAD

**Issue by bradystroud** [SSWConsulting/SSW.Website#1010]
As per my conversation with @jaydenalchin he is working on mockups for these pages

https://www.ssw.com.au/ssw/company/Web-Reference.aspx
https://www.ssw.com.au/ssw/logo/ssw/
https://www.ssw.com.au/ssw/logo/Default.aspx
https://www.ssw.com.au/ssw/logo/Past.aspx

Once Jayden's mockups are ready, refine this PBI so its ready to go.

**Comment by bradystroud** [comment]
As per my conversation with @jaydenalchin he is working on mockups for these pages

**Comment by tiagov8** [comment]
cc @jaydenalchin @2fernandez @bettybondoc 

Hi @bradystroud / @Harry-Ross 

The page https://www.ssw.com.au/ssw/company/Web-Reference.aspx is being redirected to the company index.

It was not migrated yet which means it is unaccessible ATM.

- [ ] 1. Please revert the redirection until the page is finally migrated

**Comment by bettybondoc** [comment]
@jaydenalchin 

- [ ] 1. Please make sure we have the 3 colours codes (Hex, RGB, CMYK) in the mock-up

> **SSW Red**
> #cc4141
> RGB(204,65,65)
> C: 14%, M: 89%, Y: 78%, K: 3%
> 
> **SSW Ash**
> #aaaaaa
> RGB(170,170,170)
> C: 35%, M: 28%, Y: 28%, K: 0%
> 
> **SSW Stone**
> #797979
> RGB(121, 121, 121)
> C: 54%, M: 45%, Y: 45%, K: 10%
> 
> **SSW Charcoal**
> #333333
> RGB(51,51,51)
> C: 69%, M: 63%, Y: 62%, K: 58%

- [ ] 2. Please consider the 3 file formats (SVG for Digital, PNG for Digital, PDF for Print) when designing the download feature

**Comment by andrewwaltosssw** [comment]
Completed on
- #2240
- #2282 
- #2241
