### ISSUE TITLE
✨ Consulting - Add Case Study + Video to UI-UX-Design page

### ISSUE THREAD

**Issue by hveraus** [SSWConsulting/SSW.Website#1013]
URL: https://www.ssw.com.au/consulting/ui-ux-design

**Description:**

See https://ssw.com.au/ssw/Company/Clients/
Add all Case Study links + Videos to the respective client to UI/UX design page

**Comment by tiagov8** [comment]
As per my conversation with @amankumarrr 

We need an extra button in the Showcase items... based on fields in Tina editing mode

Something like "See Case Study" and "Watch Video" (similar to what we have on https://www.ssw.com.au/company/clients)

If those fields are filled than the button appears for each of the clients section

- [x] 1. Please add that functionality

The red line dividing clients needs to be thinner and have more space around. I think red is too much too

- [x] 2. Reduce line height from .25rem to 1px
- [x] 3. Increase both margins top and bottom to 5rem;
- [x] 4. Change color from red to `#666`

- [x] 5. Change the client name from `<h4>` to `<h3>`

- [x] 6. The "Visit Website" link should be white and the font-weight normal (not bold)

**Comment by amankumarrr** [comment]
@hveraus 
done 

![image](https://github.com/SSWConsulting/SSW.Website/assets/71385247/d3ae166c-1337-4c82-ba42-03b4f44b234d)

**Figure: Case Study and Video button with the company's carousel**
