### ISSUE TITLE
⚠️ Urgent - new webpage - finance

### ISSUE THREAD

**Issue by sethdaily** [SSWConsulting/SSW.Website#1029]
Hi Brady,

Please action ASAP – the TV team need the webpage so they can start their testimonial video which will be embedded on the page.

1. Please create a new webpage in the style of [Education (ssw.com.au)](https://www.ssw.com.au/educational) with this content  [ Finance-industry-new-page.docx](https://sswcom.sharepoint.com/:w:/r/sites/SSWMarketing/Shared%20Documents/General/Seth%27s%20drafts/Finance-industry-new-page.docx?d=w8fdac88b1c7f4ec8ae1cf03086d6045c&csf=1&web=1&e=whUDom)
2. Put it in the ‘Who we work with’ section of the website
3. Make the URL ssw.com.au/industry/finance
4. Change the education page URL to /industry/education and move it into the ‘Who we work’ with section
5. Ask Seth if there are issues with organizing the content
6. Get it checked by Seth

@camillars @UlyssesMaclaren @Levijj22

**Comment by bradystroud** [comment]
Hey @sethdailyssw 


> 1. Please create a new webpage in the style of [Education (ssw.com.au)](https://www.ssw.com.au/educational) with this content [Finance-industry-new-page.docx](https://sswcom.sharepoint.com/:w:/r/sites/SSWMarketing/Shared%20Documents/General/Seth%27s%20drafts/Finance-industry-new-page.docx?d=w8fdac88b1c7f4ec8ae1cf03086d6045c&csf=1&web=1&e=whUDom)
> 2. Put it in the ‘Who we work with’ section of the website
> 3. Make the URL ssw.com.au/industry/finance
> 4. Change the education page URL to /industry/education and move it into the ‘Who we work’ with section
> 5. Ask Seth if there are issues with organizing the content
> 6. Get it checked by Seth

All done - As per our conversation, this page is live at https://ssw.com.au/industry/finance
Educational page has moved to https://ssw.com.au/industry/educational
![image](https://github.com/SSWConsulting/SSW.Website/assets/38869720/729d736e-6c1b-4d8e-8e7d-1dada86a1b7e)
**Figure: New page on the MegaMenu**
