### ISSUE TITLE
Missing "Companies we have worked with" component beneath marketing

### ISSUE THREAD

**Issue by BrookJeynes** [SSWConsulting/SSW.Website#104]
The consultation pages are missing the "Companies we have worked with" component beneath the marketing section:

![Screenshot 2023-02-03 at 13 50 01](https://user-images.githubusercontent.com/25432120/216508523-b117f8c4-b5c9-4087-bbff-4b17bba0d129.png)
**Figure: Missing section**

**Comment by wicksipedia** [comment]
closing as the consulting pages show this component



![Image](https://github.com/SSWConsulting/SSW.Website/assets/600044/f2bf4cb4-afca-4aa7-b8b4-63813b521562)
