### ISSUE TITLE
✨ Tags for PRs that differentiate changes to code vs content.

### ISSUE THREAD

**Issue by Jord-Gui** [SSWConsulting/SSW.Website#1047]
**Is your feature request related to a problem? Please describe.**
I am unable to view whether a PR is for a code change, or a content change. Would like to be able to differentiate the two. 

**Describe the solution you'd like**
An automatic tag on the PR that says 'code change' or 'content change' 

**Describe alternatives you've considered**
N/A

**Additional context**
This would help immensely for the SSW.Dory flow in trying to differentiate the two types of Pull Requests in SSW.Website repo.

**Comment by bradystroud** [comment]
@Jord-Gui Why does dory need to know the difference?

**Comment by Jord-Gui** [comment]
@bradystroud Initially, we wanted to request different reviewers automatically based on if it was a content vs code change. This is no longer needed.
