### ISSUE TITLE
Missing "Book Us" component at bottom of page

### ISSUE THREAD

**Issue by BrookJeynes** [SSWConsulting/SSW.Website#105]
The consultation pages are missing the "Book Us" component at the bottom of the page:

![Screenshot 2023-02-03 at 13 56 13](https://user-images.githubusercontent.com/25432120/216509213-e17af004-b890-437e-941b-78d3bb3f4321.png)
**Figure: Missing components**

**Comment by wicksipedia** [comment]
closing as this component is on the consulting pages



![Image](https://github.com/SSWConsulting/SSW.Website/assets/600044/4c71f171-6d4e-4e55-9318-1985f24ebf48)
