### ISSUE TITLE
⏩ Performance - LiveStream Banner Worsening Performance

### ISSUE THREAD

**Issue by Harry-Ross** [SSWConsulting/SSW.Website#1076]
As per my conversation with @bradystroud @wicksipedia, the PageSpeed Insights score has taken a dip on a day with the livestream banner.

```[tasklist]
### Tasks
- [x] Test if setting `{ ssr: true }` in `next/dynamic` makes performance better
- [x] Implement if so
```

**Comment by wicksipedia** [comment]
Have a look at implementing https://nextjs.org/docs/pages/building-your-application/data-fetching/incremental-static-regeneration

**Comment by Harry-Ross** [comment]
> Have a look at implementing https://nextjs.org/docs/pages/building-your-application/data-fetching/incremental-static-regeneration

It would be good to have this - but this would mean we would need to make the SharePoint requests on every page to be passed from getStaticProps. Two things to consider:

1. Devs creating page routes with no events data fetched from `getStaticProps`
2. Events data updating before the static props data has been revalidated

**Comment by wicksipedia** [comment]
ISR has caching with absolute time expiries - so I think it should be fine

caching sharepoint is another place which could yield benefits - just need similar cache expiration policies as well

eventual consistency is a reasonable approach

**Comment by Harry-Ross** [comment]
Closed, as I investigated the feasibility of splitting the fetches to each individual component (`<LiveStreamBanner>` and `<LiveStreamWidget>`) and then using next/dynamic to fetch them, but found that fetching in a dynamic component using `{ ssr: true }` does not result in the fetch being done on the server-side (similar to app router). 

Before this I also created a PR (https://github.com/SSWConsulting/SSW.Website/pull/1098) for ISR, but as per my conversation w/ @wicksipedia, we decided it was not feasible at the moment.
