### ISSUE TITLE
✨ User Groups - Component RegisterForFree

### ISSUE THREAD

**Issue by johnxu16** [SSWConsulting/SSW.Website#1081]
As per a conversation with Ken(@hveraus), the event register block has not been confirmed.

**Figure: component RegisterForFree on Figma**

https://www.figma.com/file/6IU1jg9Stosfecs4YfawoR/SSW-Website-v3?type=design&node-id=2612-8407&mode=design&t=ME5sqgYBPoSjqn0e-4

```[tasklist]
### Tasks
- [ ] Find a third-party form service
- [x] Create form component
```

**Comment by Harry-Ross** [comment]
Linked to https://github.com/SSWConsulting/SSW.Website/issues/512

**Comment by Harry-Ross** [comment]
As a part of the development of the user group template PBI (#512), I developed a basic form using Formik to take in user information:

![Image](https://github.com/SSWConsulting/SSW.Website/assets/20507092/90e7519e-621c-4fb3-907b-049035f1c82c)

How we will store this information and automate the marketing email flow is still undecided - will likely use some third-party form solution such as ActiveCampaign.

**Comment by Harry-Ross** [comment]
Closing as the task to integrate the form is in PBI #1475
