### ISSUE TITLE
🐛 404 Broken link on Homepage! "/about"

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.Website#1083]
cc @bradystroud 

**Describe the bug**

Broken link to https://www.ssw.com.au/about on https://www.ssw.com.au/

- [x] Fix link
- [ ] How did that happen? Can you find and cc the culprit?

<img width="690" alt="Screenshot 2023-07-20 at 2 59 24 PM" src="https://github.com/SSWConsulting/SSW.Website/assets/12601228/5ba18d90-3ca9-465b-b740-43635227e084">

**Comment by bradystroud** [comment]
Hey @tiagov8 

Done - I changed the link to go to https://www.ssw.com.au/ssw/Company/AboutUs.aspx

![](https://github.com/SSWConsulting/SSW.Website/assets/38869720/06868fcf-088c-4e69-8adc-387c360b1d41)
**Figure: Fixed link**
