### ISSUE TITLE
📄 Update page - Video Production | Customer Testimonials & Case Studies

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.Website#1099]
cc @apforsyth @jontygardner @BrookJeynes 

URL: https://www.ssw.com.au/consulting/video-production/product-videos

From @landonmaxwell 

--

**Title** – this page is called “Video Production”, which is confusing, as the main page is also called the same name. (E.g. it should be called “Testimonials & Case Studies”)

1. [x] Update title

--

**URL** – it is odd to have the subdirectory as “video-production/product-videos”, it should be “video-production/testimonials”

2. [x] Update URL

--

**Content** – Should include Shepherd Centre

3. [x] Add https://www.youtube.com/watch?v=6HIPaw4jG18 to the list of videos

--

**Video Headings** – it might be better to have titles (and maybe short descriptions) for our case studies:

4. [x] Add a heading for each of the videos

![image002](https://github.com/SSWConsulting/SSW.Website/assets/12601228/6a41a830-5cf6-4e3c-b479-c53dfc0cfbe8)

**Figure: A solid block of videos without headings or descriptions.**

**Comment by tiagov8** [comment]
Hey @bradystroud 

Can you action the missing task?

**Comment by bradystroud** [comment]
Done in #1261 

Hey @KristenHu 

- [x] Update megamenu link (if there is one)
- [x] Add redirect to front door

**Comment by KristenHu** [comment]
Hey @bradystroud ,

> * [x]  Update megamenu link (if there is one)
**Done** - No such link needs to be updated.
> * [x]  Add redirect to front door
**Done** - https://github.com/SSWConsulting/SSW.FrontDoor/pull/87
