### ISSUE TITLE
📄 Events - Rates are incorrect on our Customised Courses page

### ISSUE THREAD

**Issue by samsmithssw** [SSWConsulting/SSW.Website#1130]
URL: https://www.ssw.com.au/ssw/Events/Training/Training-Options.aspx

**From:**

If you need a training session at your location for your department or the whole company, we can do that too. Maximize your training dollars by running your own tailored programs. From ~$3,960~ per day (per company), choose from our list of [Training 

**To:**

If you need a training session at your location for your department or the whole company, we can do that too. Maximize your training dollars by running your own tailored programs. From $4,990 per day (per company), choose from our list of [Training

**Comment by amankumarrr** [comment]
Hey @samsmithssw, I made the change on the site, therefore I'm marking this as done and closing the issue 

<img width="680" alt="image" src="https://github.com/SSWConsulting/SSW.Website/assets/71385247/752348a6-9222-48cd-b772-719ca7846206">

**Figure: Updated price on https://www.ssw.com.au/ssw/Events/Training/Training-Options.aspx**
