### ISSUE TITLE
📄Instruction - How to add endpoint in .env file for API related to newsletters?

### ISSUE THREAD

**Issue by KristenHu** [SSWConsulting/SSW.Website#1132]
As per my conversation with @amankumarrr and @bradystroud , our instruction should be updated to show how to add endpoints in .env file for newsletters' API and Create Lead's API

**Comment by KristenHu** [comment]
**Done** - https://github.com/SSWConsulting/SSW.Website/wiki/Accessing-the-Third%E2%80%90Party-APIs-Locally (Checked by Aman)

**Comment by Harry-Ross** [comment]
As per my conversation with @bradystroud, please can you add a size estimate to this PBI
