### ISSUE TITLE
💸 Tech Debt - Increase base font-size

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.Website#1147]
cc @BrookJeynes @bradystroud @amankumarrr 

**Description**  

Usually it's [recommended to use a font-size at least 16px](https://www.learnui.design/blog/mobile-desktop-website-font-size-guidelines.html) which is exactly what we have at ssw.com.au

However I've received some feedback from @adamcogan considering it too small (Email subject: **Home page banner**)

> Can you increase the font size?

Let's make it 18px instead.

I also think we don't need to set a different base line-height, keeping the default

**Proposed solution**  
1. Please update the CSS replacing

```
html {
    line-height: 1.5;
    ...
}
```

with

```
html {
    font-size: 18px;
    ...
}
```

**Note:** This change will affect the website content pretty much everywhere. We may need to adjust some font sizes here and there (e.g https://github.com/SSWConsulting/SSW.Website/issues/1148) since they are all based in this piece of css

---

![image0](https://github.com/SSWConsulting/SSW.Website/assets/12601228/bd13d901-afea-4f57-b679-dc174f4987d4)

**Figure: Font size on the bottom red box seems too small to Adam**

**Comment by bradystroud** [comment]
@tiagov8 As per my conversation with @wicksipedia we should not modify the base size, we should use large or XL in tailwind to increase size

**Comment by wicksipedia** [comment]
> we should not modify the base size

rationale - it makes px to rem calcs much easier for devs

Unless the intent was to scale **everything**, since tailwind uses rem sizes everywhere - this will scale the entire site

**Comment by tiagov8** [comment]
> @tiagov8 As per my conversation with @wicksipedia we should not modify the base size, we should use large or XL in tailwind to increase size

Hey @bradystroud . Does that mean we need to set these classes on EVERY element? I think this is bad for maintenance and could generate a lot of inconsistency over the time (e.g. changing font size in a section in a page, and not the similar section on another page).

I still believe the CSS base font is the most effective way to go

> > we should not modify the base size
> 
> rationale - it makes px to rem calcs much easier for devs
> 
> Unless the intent was to scale **everything**, since tailwind uses rem sizes everywhere - this will scale the entire site

The idea is to scale the entire site indeed. I obviously expect some further adjustments to be made, but the regular main text 1rem should be equivalent to 18px.

**Comment by wicksipedia** [comment]
done - font size bumped up

![CleanShot 2023-11-28 at 11 46 37](https://github.com/SSWConsulting/SSW.Website/assets/600044/58da653d-c9db-4d57-85ec-fe19ab7390ee)

**Comment by tiagov8** [comment]
Hi @wicksipedia 

The overall fonts look fine, but I noticed the Upcoming Events sections to have some unproportional small fonts.

Seems like the cause is a class ".text-xxs" which I am not sure why is being used now (I assume it wasn't there before...). I think if change to ".text-xs" will fix the problem

- [ ] 1. Please investigate and fix

<img width="586" alt="Screenshot 2023-11-29 at 10 11 41 AM" src="https://github.com/SSWConsulting/SSW.Website/assets/12601228/1bf8038c-f711-442d-9c0a-55f3bde607bd">

Note: Same for "X days to go" in the Events index: https://www.ssw.com.au/events

<img width="769" alt="Screenshot 2023-11-29 at 10 17 56 AM" src="https://github.com/SSWConsulting/SSW.Website/assets/12601228/f348fee1-433d-4f7f-967a-fec434c74eda">

**Comment by wicksipedia** [comment]
Hey @tiagov8 

Done

![CleanShot 2023-11-30 at 10 30 26@2x](https://github.com/SSWConsulting/SSW.Website/assets/600044/d92bf336-2c18-46e1-a29a-c3ab00de36c5)
![CleanShot 2023-11-30 at 10 31 04@2x](https://github.com/SSWConsulting/SSW.Website/assets/600044/1f02a225-be92-415f-945f-be146d7fc290)
