### ISSUE TITLE
✨ New page - Our Partners

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.Website#1160]
cc @UlyssesMaclaren @sethdailyssw @camillars @amankumarrr @bradystroud @hveraus 

Based on https://www.ssw.com.au/products

- [x] 1. Add a new page called "Our Partners" **ssw.com.au/partners** 
- [x] 2. Include (with icons, links, and blurb)
  - Microsoft
  - IdentityServer
  - Octopus
  - Zendesk
  - Control4

- [x] 3. Add to main menu under "Who we work with"

**Comment by amankumarrr** [comment]
@tiagov8 @wicksipedia @bradystroud @camillars 

I've uploaded the images provided by @hveraus for our partners and now waiting for the content for each partner with the email subject "Partners Page - Content"

**Comment by tiagov8** [comment]
Hi @amankumarrr @ae-cher-ssw @sethdailyssw 

Is this still pending? If yes, then

- [x] 1. Use the below (either long or short versions)
- [ ] 2. Create another PBI for the marketing team to review/improve the texts

---

I've asked ChatGPT for a start:

> Certainly, here's a short blurb for each of these items:
> 
> **Microsoft:** Microsoft is a globally renowned technology company, known for its wide range of software, hardware, and cloud services, including Windows, Office, Azure, and Surface devices.
> 
> **IdentityServer:** IdentityServer is an open-source authentication and authorization framework that helps developers secure their web applications and APIs with ease, providing a robust and customizable identity management solution.
> 
> **Octopus:** Octopus is a DevOps automation platform designed to simplify the deployment and management of applications. It streamlines the release process and ensures consistency in software delivery.
> 
> **Zendesk:** Zendesk is a leading customer service and engagement platform that empowers businesses to provide exceptional customer support through a variety of channels, including email, chat, and social media.
> 
> **Control4:** Control4 is a home automation and smart home system that enables homeowners to control and automate various aspects of their homes, such as lighting, climate, entertainment, and security, for enhanced convenience and efficiency.
> 

and a little bit shorter

> Certainly, here are shorter blurbs for each item:
> 
> **Microsoft:** A global tech giant offering software, hardware, and cloud services.
> 
> **IdentityServer:** Open-source identity management for web apps and APIs.
> 
> **Octopus:** DevOps automation platform for simplified deployments.
> 
> **Zendesk:** Customer service and engagement platform.
> 
> **Control4:** Smart home automation for convenience and security.

**Comment by amankumarrr** [comment]
@bradystroud @wicksipedia 

Hi @tiagov8 @ae-cher-ssw @sethdailyssw 

Thanks for the content @tiagov8 , this page is live now. Instead of creating a new issue, I will keep it open until its content get test passed by marketing team, please share your thoughts on it?

<img width="751" alt="image" src="https://github.com/SSWConsulting/SSW.Website/assets/71385247/7f488dfa-a345-4d2f-b3da-e3ea94a4a27f">

**Figure: Partners page on production and also in the mega menu.**

**Comment by bradystroud** [comment]
@tiagov8 @amankumarrr 

I feel like this should be a company page and be at /company/partners

**Comment by tiagov8** [comment]
> @tiagov8 @amankumarrr
> 
> I feel like this should be a company page and be at /company/partners

Agreed!

@amankumarrr 

- [x] 1. Please move page to be under /company/partners
- [ ] 2. Can we make the current /partners redirect?

**Comment by sethdaily** [comment]
@amankumarrr can you link the page in this thread please

**Comment by amankumarrr** [comment]
@sethdailyssw here is the link - https://www.ssw.com.au/company/partners
