### ISSUE TITLE
🐛 Events Page - Footer cut off by overflowing events 

### ISSUE THREAD

**Issue by JackDevAU** [SSWConsulting/SSW.Website#1199]
**Describe the bug**
When I scrolled to the bottom the events page, I noticed that the footer is cut off by the above events.

**To Reproduce**
1. Go to, https://www.ssw.com.au/ssw/Events?tech=all&type=all
2. Scroll to the bottom
3. See issue

**Browser:** Firefox - haven't checked other browsers

**Expected behavior**
Should be able to see the full footer without it being cut off.

**Screenshots/Video**
If applicable, add screenshots/video to help explain your problem.
Remember to mark the area in the application that's impacted.

![image](https://github.com/SSWConsulting/SSW.Website/assets/57518417/681a5f0c-c9eb-453c-937f-1183a93a70c1)
Figure: Footer cut off by events

**Comment by bradystroud** [comment]
Thanks @JackDevAU 
This page is still part of the old website (its got `/ssw/` in the url) and will probably be fixed by migrating it to the new site.
@Harry-Ross is working on this now #1056

**Comment by Harry-Ross** [comment]
I imagine this won't be a problem once I finish migrating that page, so I'll close this when I complete it (likely today)

**Comment by Harry-Ross** [comment]
Fixed by https://github.com/SSWConsulting/SSW.Website/pull/1217 at https://www.ssw.com.au/events
