### ISSUE TITLE
🐞 Events - Unable to select specific testimonials

### ISSUE THREAD

**Issue by wicksipedia** [SSWConsulting/SSW.Website#1202]
When I setup an event, I want to select the correct testimonials e.g. when I edit the CA Workshop event, I don't want to see Firebootcamp testimonials

```[tasklist]
### Tasks
- [x] Add ability to select specific testimonials (like the consulting pages)
```

![Image](https://github.com/SSWConsulting/SSW.Website/assets/600044/3f0921a0-3247-4306-bd15-58fed93f7409)

**Comment by bradystroud** [comment]
Hey @johnxu77 I can see this one was closed but there is no Done Video or done comment.

I think a video would be really valuable here, showing users how to use testimonials and testimonial categories.

**Comment by johnxu16** [comment]
Hi @bradystroud,

Thanks for the advice, I've uploaded the Done Video on the channel of "SSW Website" 😊

Video Link: https://youtu.be/6oCwsRWnrZA
