### ISSUE TITLE
🐛 Intune consulting page missing from consulting index 

### ISSUE THREAD

**Issue by AshAnil** [SSWConsulting/SSW.Website#1243]
cc @tiagov8 @bradystroud @BrookJeynes 

Hi Team,

This page https://www.ssw.com.au/consulting/intune is missing from the consulting list https://www.ssw.com.au/consulting 

- [x] Investigate and Fix
- [x] I thought this was automatic. Is there any other step need to be done by page creators?
- [x] Can you check if there are others?

**Comment by johnxu16** [comment]
@AshAnil 
> I thought this was automatic. Is there any other step need to be done by page creators?  

This is not automatic. All links on consulting index page are stored in a standalone json file.

**Comment by johnxu16** [comment]
>  Can you check if there are others?  
No, there is only one page which should not be a PageCard.

![image](https://github.com/SSWConsulting/SSW.Website/assets/113034339/77babf3d-0e1b-47a5-92c0-216150bf4298)
**Figure: page links not include in the json file**

![image](https://github.com/SSWConsulting/SSW.Website/assets/113034339/42eb0e82-5b1e-4ac6-8778-6a44d7f6149f)
**Figure: https://ssw.com.au/consulting/are-you-stuck**
