### ISSUE TITLE
App insights - Try filter out autodiscover.xml

### ISSUE THREAD

**Issue by bradystroud** [SSWConsulting/SSW.Website#1251]
```[tasklist]
### Tasks
- [ ] Filter out unfixable error - change Kusto query
- [ ] We might need a new dashboard
```

<img width="1428" alt="image" src="https://github.com/SSWConsulting/SSW.Website/assets/38869720/f7156ddb-c53a-410b-9940-ce2551676d00">

Check out Matt W's LinkedIn

**Comment by wicksipedia** [comment]
Closing as this has already been implemented in a separate report
