### ISSUE TITLE
Pages - News

### ISSUE THREAD

**Issue by amankumarrr** [SSWConsulting/SSW.Website#1257]
[News & Press](https://www.ssw.com.au/ssw/News/)

new URL: `/company/news`

```[tasklist]
### Tasks
- [x] migrate page
- [x] Add redirect
- [x] Update megamenu link
```

**Comment by Harry-Ross** [comment]
Front Door redirect: https://github.com/SSWConsulting/SSW.FrontDoor/pull/94
Menu: https://github.com/SSWConsulting/SSW.Website.Menu.json/pull/96
