### ISSUE TITLE
📄 Migration | New Zealand page

### ISSUE THREAD

**Issue by Harry-Ross** [SSWConsulting/SSW.Website#1281]
Check with @adamcogan and @wicksipedia 
Is this page worth migrating?

```[tasklist]
### Tasks
- [x] Migrate https://www.ssw.com.au/ssw/NewZealand/ to /new-zealand
- [x] Add redirect to FrontDoor
```
If it is migrated, I think it makes sense to move it under /consulting/new-zealand

**Comment by wicksipedia** [comment]
> If it is migrated, I think it makes sense to move it under /consulting/new-zealand

disagree

**Comment by jeoffreyfischer** [comment]
As per our conversation with Matt W, we think it should be migrated. @UlyssesMaclaren do you agree?
Create new images using SPICE: https://sswcom.sharepoint.com/SitePages/SSW-GPTs.aspx

**Comment by andrewwaltosssw** [comment]
As per Teams [comment](https://teams.microsoft.com/l/message/19:b_FZrvF1JpY3Sj3c6Me8fuA86vkaqcq_7OTurG_qtZY1@thread.tacv2/1711502785830?tenantId=ac2f7c34-b935-48e9-abdc-11e5d4fcb2b0&groupId=016bee4c-2858-41f9-a89c-2ecf91cf4af5&parentMessageId=1673834417094&teamName=SSW%20Website%20v3&channelName=General&createdTime=1711502785830) with @wicksipedia page to be migrated to path `/new-zealand`

**Comment by andrewwaltosssw** [comment]
> As per our conversation with Matt W, we think it should be migrated. [@UlyssesMaclaren](https://github.com/UlyssesMaclaren) do you agree? Create new images using SPICE: https://sswcom.sharepoint.com/SitePages/SSW-GPTs.aspx

As per conversation with Uly, He is also in favour of migrating the NZ page. We have also asked Camilla for input on the content. We should be able to migrate this page and content can be updated later by marketing team

**Comment by andrewwaltosssw** [comment]
As per [comment](https://github.com/SSWConsulting/SSW.Website/pull/2401#issuecomment-2031107923). Marketing approved migration as screenshot below. There may be future work to split this content to other pages.

Page migrated:

![image](https://github.com/SSWConsulting/SSW.Website/assets/87786621/7755653d-10f9-4cb3-bd57-35241e9e1cbb)
**Figure: Old page (left) vs new page (right)**
