### ISSUE TITLE
🐛 Some Events have a null description (old site)

### ISSUE THREAD

**Issue by Hona** [SSWConsulting/SSW.Website#1282]
Some Events have a null description

https://www.ssw.com.au/ssw/

<img width="369" alt="image" src="https://github.com/SSWConsulting/SSW.Website/assets/10430890/a095904c-6a09-438d-8ed7-5e1dd9fb23c0">

```[tasklist]
### Tasks
- [ ] Investigate
- [ ] Fix
```

**Comment by KristenHu** [comment]
As per my conversation with @amankumarrr , we will

- [x] Add redirect from old page to new homepage
**Done** - https://github.com/SSWConsulting/SSW.FrontDoor/pull/90
- [x] Note this issue of null description

**Comment by Hona** [comment]
@KristenHu why is this issue closed?

I just checked again and there is still 'null' text on some events:

![image](https://github.com/SSWConsulting/SSW.Website/assets/10430890/c170cf9f-a580-400f-a22b-572d1e127869)

**Comment by amankumarrr** [comment]
Hey @Hona, this issue only exists on old home page, therefore, we tried adding a redirect it to the new one but it didn't work, I have created an issue #1350 which probably going to fix it and will update you on this shortly.

**Comment by Hona** [comment]
Okay - in future I would avoid closing a bug unless it is fixed (or marked as 'not going to fix')

**Comment by Hona** [comment]
Duplicate of #1350

**Comment by bradystroud** [comment]
Closing as this is fixed by https://github.com/SSWConsulting/SSW.Website/issues/1350
