### ISSUE TITLE
✨ SSW Website - Call us link

### ISSUE THREAD

**Issue by amankumarrr** [SSWConsulting/SSW.Website#1300]
@2fernandez 
**Description:**
Currently, the 'Call Us' button on mobile directly initiates a phone call when clicked, while on desktop, it prompts users to open a compatible application for making the call. To align the behavior, we aim to have the button open the '[Contact Us](https://ssw.com.au/company/contact-us)' page on desktop while maintaining the existing behavior on mobile devices.

**Acceptance Criteria:**
Both scenarios should be a normal hyperlink 

![CallUS](https://github.com/SSWConsulting/SSW.Website/assets/71385247/cfc7c5cd-f8ba-4249-b167-a4e10eb3f176)
**Figure: Call us button on landing page**

**Comment by 2fernandez** [comment]
Hi @amankumarrr can you please clarify the 

Acceptance Criteria "Both scenarios should be a normal hyperlink"

Can you confirm if we will be able to do the following ?

1. For Desktop: redirects to the “Contact Us” page (https://www.ssw.com.au/company/contact-us)
2. For Mobile: Leave the same - on click it makes a call
