### ISSUE TITLE
🔧 DevOps - Move Off Using Docker

### ISSUE THREAD

**Issue by Harry-Ross** [SSWConsulting/SSW.Website#1303]
As per my conversation with @wicksipedia, we should move off Docker.

Problems with using Docker:
1. Build time takes too long
2. We manage too many secrets in the build process

```[tasklist]
### Tasks
- [ ] Confirm that we can build without Docker and push code to an App Service or similar alternative
- [ ] Test please from Matt W
```

**Comment by wicksipedia** [comment]
As per conversation with @bradystroud  and @Harry-Ross - it looks like this isn't possible in the foreseeable future
