### ISSUE TITLE
✨Testimonials cannot be displayed without avatars

### ISSUE THREAD

**Issue by KristenHu** [SSWConsulting/SSW.Website#1322]
The testimonial components are unable to display without avatars. Please fix this issue.

```[tasklist]
### Tasks
- [x] Check with designer to see if how to deal with this situation
- [x] Update testimonials
```

**Comment by johnxu16** [comment]
As per conversation with @hveraus, we'll add an image as a placeholder when a testimonial does not have an avatar image
