### ISSUE TITLE
📄Create Lead - Document it in SharePoint 

### ISSUE THREAD

**Issue by amankumarrr** [SSWConsulting/SSW.Website#1332]
To: @pierssinclairssw 
CC: @Marxoz  @wicksipedia @adamcogan  @Aibono1225  @2fernandez @camillars @samsmithssw @bradystroud @JackDevAU 
Subject: RE: ⚠️[URGENT] - Leads through SSW.Rules and SSW.People

We are currently using the same endpoint (i.e., api/create-lead) in three different places (SSW.Webiste, SSW.Rules and SSW.People) for lead creation. This situation poses a risk, as changes made by a new developer in one location could potentially affect the other areas. To mitigate this, it's essential to thoroughly document the usage to ensure that any modifications are made carefully and do not cause unintended issues.
```[tasklist]
### Tasks
- [x] Document it in SharePoint
- [x] Add the link to that in the code where we are calling out that API in all three places
```

**Comment by amankumarrr** [comment]
@Marxoz @wicksipedia @adamcogan @Aibono1225 @2fernandez @camillars @samsmithssw @bradystroud @JackDevAU

Hi team,

I've created a doc for create lead - https://sswcom.sharepoint.com/:w:/r/sites/SSWDevelopers/_layouts/15/Doc.aspx?sourcedoc=%7BE8A18D9B-DE74-47EC-B836-01A5AD193DCC%7D&file=Create-lead-Flow.docx&action=default&mobileredirect=true, test passed by @christianmorfordwaitessw and now it's being referenced in all three places in our code.

**Comment by camillars** [comment]
[https://outlook-1.cdn.office.net/assets/reaction/like.png]     Camilla Rosa Silva [SSW] reacted to your message:




[cid:ssw-circle(1)_4c7259a6-23f6-49e5-b933-230ca304562e.png]

Camilla Rosa Silva
SSW Marketing Manager
Stalk: SSW People<https://www.ssw.com.au/people/Camilla-Rosa%20Silva?utm_source=emailsignature>   |   Walk: SSW Sydney<https://www.ssw.com.au/ssw/Company/Offices/?utm_source=emailsignature>   |   Talk: +61 426 007 665<https://www.ssw.com.au/ssw/Company/ContactUs.aspx>
[cid:youtube-icon_b8b5cda9-a973-4973-8763-cf3d4922e060.png] <https://www.youtube.com/c/SSWTV>    [cid:linkedin-icon_b153ac9a-eb66-47d9-9c51-ad20b42b8a0a.png]  <https://www.linkedin.com/company/ssw/>    [cid:twitter-icon_16ddd2de-0a0c-4b56-9986-6c5968e517d2.png]  <https://twitter.com/SSW_TV>    [cid:teams-icon_552803c2-9c44-4267-b563-7fe1a7a0e589.png] ***@***.***>


        ⭐️ 2023 Microsoft Partner of the Year Finalist<https://www.ssw.com.au/SSW/Consulting/Case-Study/Shepherd-Centre.aspx>

________________________________
