### ISSUE TITLE
💄 Events - Text Size Too Small

### ISSUE THREAD

**Issue by Harry-Ross** [SSWConsulting/SSW.Website#1349]
As per my conversation with @adamcogan, the text size is too small on the date field on [ssw.com.au/events](https://www.ssw.com.au/events).

![image](https://github.com/SSWConsulting/SSW.Website/assets/20507092/45dc2f6b-7db2-4fb3-9c22-af3d5dfc1c13)
**Figure: The text that needs to be bigger**

```[tasklist]
### Tasks
- [x] Increase the text size of the date field *only* on `/events`
- [x] Check the index page (/) has not been affected
```

**Comment by KristenHu** [comment]
**Done** - https://github.com/SSWConsulting/SSW.Website/pull/1388

![image](https://github.com/SSWConsulting/SSW.Website/assets/52522913/3fea7cf5-d7ae-4a9e-8ae0-f8a746b31dc9)
**Figure: Date field on the events page**

![image](https://github.com/SSWConsulting/SSW.Website/assets/52522913/518bf60a-340d-4f99-91c5-d52e9c297703)
**Figure: Date field on the homepage**
