### ISSUE TITLE
🐛 Front Door - Exact matches causing issue 

### ISSUE THREAD

**Issue by amankumarrr** [SSWConsulting/SSW.Website#1350]
**Description:**

We've come across a redirection issue involving exact matches on Front Door. For instance, if we set up a redirect with an exact match for 'ssw,' it won't work for 'ssw/' (with a trailing slash). 
```[tasklist]
### Tasks
- [x] Find a way to fix add multiple routes (with or without trailing backlash)
- [x] Fix all redirects accordingly (if it requires)
```

**Comment by amankumarrr** [comment]
@wicksipedia 

As per my conversation with @william-liebenberg, @leahy268, @bradystroud and @Harry-Ross, we decided to utilize an array of strings instead of a single string for our ruleset redirects. This adjustment will resolve the issue with exact matches since it will accommodate multiple values in the parameter. Furthermore, we intend to convert the JSON format to BICEP in our parameter file to reduce the noise associated with JSON.

<img width="230" alt="image" src="https://github.com/SSWConsulting/SSW.Website/assets/71385247/df54ce55-3ca3-4439-ad04-db5cfbbaa56a">

**Figure: Showing Request Path as string in JSON file**

**Comment by johnxu16** [comment]
@amankumarrr 
As per https://github.com/Azure/bicep/issues/10454 and https://github.com/Azure/bicep/issues/11042, the bicepparam files do not support supplemental parameters which makes it hard to work with parameters we injected during deployment.

As per discussion with Jim, I add a step in github action for replacing parameters stored in bicepparam.

**Comment by KristenHu** [comment]
@amankumarrr @bradystroud 
As per my conversation with @wicksipedia , we will choose the origin JSON format for redirect lists instead of bicepparam files.

Also, before deploy it to the staging env, please make sure the new ruleset for the staging env has been updated in related bicep file.

**Comment by amankumarrr** [comment]
@wicksipedia @bradystroud @KristenHu @johnxu77 

This has been fixed and deployed on Production. So now we can have multiple request paths with and without slashes.
