### ISSUE TITLE
💸 Megamenu - Bundle Size Too Large

### ISSUE THREAD

**Issue by Harry-Ross** [SSWConsulting/SSW.Website#1357]
**Description**  
Right now, the megamenu size is much too large - this is likely due to bundling npm depdendencies that could be classified as peerDependencies. 

I have created an issue on SSW.Megamenu here: https://github.com/SSWConsulting/SSW.MegaMenu/issues/40

**Proposed solution**  
I will be moving as many NPM packages as possible to peer dependencies/removing the dependency where possible. 

```[tasklist]
### Tasks
- [x] Publish a new version of the NPM package
- [ ] Verify the package with SSW.Rules and SSW.People
```

**Comment by johnxu16** [comment]
In optimizing the size of the package, could you please move those image assets to remote so we can utilize speed from cdn, etc?

They take around 190kb(60%) space.

**Comment by Harry-Ross** [comment]
Created a PR at https://github.com/SSWConsulting/SSW.MegaMenu/pull/41

**Comment by Harry-Ross** [comment]
SSW Rules issue: https://github.com/SSWConsulting/SSW.Rules/issues/1097
SSW People issue:  https://github.com/SSWConsulting/SSW.People/issues/532

**Comment by Harry-Ross** [comment]
Menu JSON to be merged when all tasks completed: https://github.com/SSWConsulting/SSW.Website.Menu.json/pull/99
