### ISSUE TITLE
🐛 Booking form - add description field limit 

### ISSUE THREAD

**Issue by amankumarrr** [SSWConsulting/SSW.Website#1377]
**Describe the bug**
Currently, our booking form does not have any constraints or limits in place. Recently, a client attempted to add a description that exceeded the allowed limit, resulting in a failure to create the lead in our CRM system. Therefore, ~on the front end, we need to implement restrictions to prevent users from entering text beyond the 2000 limit.~ need to increase the limit in the CRM.

```[tasklist]
### Tasks
- [x] Increase the limit of characters from 2000 to 2100 for Description field
```
 
<img width="323" alt="Description Field" src="https://github.com/SSWConsulting/SSW.Website/assets/71385247/d499c0bc-1b1b-42fa-8f30-96c4b7541957">

**Figure: Booking form with the description field.**

<img width="309" alt="image" src="https://github.com/SSWConsulting/SSW.Website/assets/71385247/e6894a5b-c9c0-4673-b82f-1348ace9d324">

**Figure: Create lead flow is failing due to exceeded string length**

**Comment by bradystroud** [comment]
It needs client side validation

**Comment by amankumarrr** [comment]
@wicksipedia @bradystroud 

On investigation, I discovered that we have indeed implemented the logic correctly to restrict users from entering descriptions exceeding the limit of 2000 characters. However, it appears that the issue arises when our flow appends additional information.

So, the client entered approximately 1950 characters, but due to the additional information appended by our flow, the total character count exceeded the allowed limit by about 75 characters.

<img width="447" alt="image" src="https://github.com/SSWConsulting/SSW.Website/assets/71385247/b2435e0f-87e4-4335-8851-88d87c86bb1f">

**Figure: Description field being appended with some extra information**

As per my discussion with @zl24622, we have decided to increase the character limit for the CRM's field to 2100 characters. This adjustment will provide us with a buffer to accommodate any additional information we may wish to append to this field.

**Comment by zl24622** [comment]
@amankumarrr 

> Increase the limit of characters from 2000 to 2100 for Description field

Done - increased the characters to 2200

<img width="358" alt="image" src="https://github.com/SSWConsulting/SSW.Website/assets/8521734/273f4b00-19fe-40a9-bc73-5ed972ef23c0">

**Comment by amankumarrr** [comment]
@zl24622 @wicksipedia @bradystroud  
I tested it in production and it is working as expected, therefore, closing this issue.
