### ISSUE TITLE
Resolve dependabot PRs

### ISSUE THREAD

**Issue by bradystroud** [SSWConsulting/SSW.Website#1383]
These PRs from Dependabot have builds that failed.

#1378
#1371

```[tasklist]
### Tasks
- [x] Resolve them
```

**Comment by johnxu16** [comment]
As per #1378

A hook created before typed the timer with `NodeJs.Timer` which cannot be used as param of clearTimeout.

![image](https://github.com/SSWConsulting/SSW.Website/assets/113034339/cb2b954e-16dd-45bf-acaa-f2944723cd9b)
**Figure: type error**

After I replace type `NodeJs.Timer` with `NodeJs.Timeout`, it resolved.
![image](https://github.com/SSWConsulting/SSW.Website/assets/113034339/16de683a-969a-4e4a-88ed-c120e028d3f2)
**Figure: no type error**

The hook is not used by any component and the use cases of this hook is uncommon so I decided to remove it.
