### ISSUE TITLE
🐛 UI - Wrong text colour on lists 

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.Website#1391]
cc @jaydenalchin @bradystroud 

**Describe the bug**
https://www.ssw.com.au/employment#available

When you look at a job description, you can see the text colour on lists (`#374151`) is slightly different from the paragraphs texts (`#333333`)

**Expected behavior**
Colours should be the same.

See the related issue https://github.com/SSWConsulting/SSW.Website/issues/1203 for more info

**Screenshots/Video**

<img width="1395" alt="Screenshot 2023-09-12 at 5 42 05 PM" src="https://github.com/SSWConsulting/SSW.Website/assets/12601228/5dab512f-00ef-4ef8-af4b-9a5370bde3db">

**Comment by tiagov8** [comment]
Hi @Harry-Ross 

I saw you fixed the bullet points color, but if you double check the Issue, it is about the **text** colour on lists. 
Basically the body color of this site (via this prose class) is set to be `#374151`

I am not familiar with the prose thing, but we should set all these default base colours to follow [SSW colours](https://www.ssw.com.au/ssw/company/Web-Reference.aspx#Colors)

- [ ] 1. Please action

See text colour slightly changes when you change the CSS:

https://github.com/SSWConsulting/SSW.Website/assets/12601228/3916af6b-2f8e-4488-acb7-51e04dd8d944

PS. It is OK to keep the bulltet as it is now ;) Looks better

**Comment by wicksipedia** [comment]
> I am not familiar with the prose thing

this is the default class name for [Tailwind typography](https://tailwindcss.com/docs/typography-plugin)

**Comment by wicksipedia** [comment]
done

![CleanShot 2023-11-01 at 11 13 03@2x](https://github.com/SSWConsulting/SSW.Website/assets/600044/ad122441-e11f-4a90-8d30-9da244483982)
