### ISSUE TITLE
🐛 Cannot create a new Consulting page

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.Website#1404]
**Describe the bug**
I tried duplicating an existing page AND creating a new page.

In both cases, when I tried to edit the SEO value I got this error:

<img width="1591" alt="Screenshot 2023-09-15 at 9 59 45 AM" src="https://github.com/SSWConsulting/SSW.Website/assets/12601228/3c1d3544-a05f-47c9-ad59-bf6368068529">

- [x] 1. Please investigate and fix

**Comment by tiagov8** [comment]
Note: I created a new Issue for this new page: https://github.com/SSWConsulting/SSW.Website/issues/1405

**Comment by jeoffreyfischer** [comment]
- **Pains**: 
1. The tip message was manually added in each page.
2. The message was not clearly saying which field to fill. 

- **Solutions**: 
1. I created a single tip message in "shared-fields" and imported it in each page.
2. The message now mentions which field needs to be filled (see screenshot)


- Affected routes: `/admin/`

- Fixed #1404 

- Screenshot

![website-PR-004](https://github.com/SSWConsulting/SSW.Website/assets/106663901/62e3a0f6-fd30-4da3-ab30-e4cd25c16daa)
**Figure**: Updated tip message.
