### ISSUE TITLE
📄 Create new "Fabric" consulting page

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.Website#1405]
### 1. People in the loop:

@bradystroud @adamcogan @apforsyth @UlyssesMaclaren @pierssinclairssw 

### 2. Page template to copy:

https://www.ssw.com.au/consulting/power-platform

### 3. URI:

https://www.ssw.com.au/consulting/fabric

### 4. Title:

Want to bring your data into the era of AI?

### 5. Meta description:

Microsoft Fabric reshape how everyone accesses, manages, and acts on data and insights by connecting every data source and analytics service together - on a single, AI-powered platform.

### 6. Related URLs:

- https://www.ssw.com.au/consulting/power-bi
- https://www.ssw.com.au/consulting/azure-synapse

### 7. Content:

Microsoft Fabric offers an all-encompassing analytics solution, boasting a comprehensive suite of services covering data movement, data lakes, data engineering, data integration, data science, real-time analytics, and business intelligence. These capabilities are underpinned by a unified platform that ensures robust data security, governance, and compliance.

Say goodbye to the hassle of piecing together disparate analytics services from various vendors. Instead, opt for an integrated solution that is not only easy to connect and onboard but also straightforward to operate.

**Centralize your data environment**
Create an open and lake-centric hub within your organization, facilitating data engineers in the seamless connection and curation of data from diverse sources. This approach eliminates data sprawl and enables the customization of views tailored to individual needs.

**Streamline AI model management**
Expedite your analytical processes by developing AI models on a unified foundation, without the need for data movement. This reduces the time data scientists require to deliver valuable insights.

**Empower your entire workforce**
Promote innovation across your organization by enabling every member to act upon insights derived from Microsoft 365 applications like Microsoft Excel and Microsoft Teams.

**Govern data organization-wide**
Facilitate responsible data connection between individuals and data through an open and scalable solution. This empowers data stewards with enhanced control, thanks to built-in security, governance, and compliance features.

**Comment by tiagov8** [comment]
- [x] 1.  I have already created a new branch "new-fabric-page". Feel free to use it OR delete if not helpful
- [x] 2. The page should be under Platforms
- [x] 3. Please get the icon from https://learn.microsoft.com/en-us/fabric/get-started/icons

![Fabric_final_x256](https://github.com/SSWConsulting/SSW.Website/assets/12601228/5bd00274-c06b-4db8-b949-8c205aa8ebb7)

**Comment by tiagov8** [comment]
- [ ] The page should be under Platforms

**Comment by tiagov8** [comment]
Related to https://ssw.visualstudio.com/SSW%20TV/_workitems/edit/84397

**Comment by amankumarrr** [comment]
@tiagov8 @bradystroud this page has been created and is live now. Also I added its link in our mega menu after having discussion with @bradystroud therefore closing this issue. 
<img width="319" alt="image" src="https://github.com/SSWConsulting/SSW.Website/assets/71385247/8fe5bb58-e331-4285-996d-fb695d78a152">
**Figure: Fabric link in the mega menu**
