### ISSUE TITLE
📄 Migrate SSW Culture page

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.Website#1424]
(edited by Seth)
### 1. People in the loop:

@adamcogan @camillars 

### 2. Page template to copy:

https://www.ssw.com.au/company/about-us

### 3. URI:

https://www.ssw.com.au/company/culture

### 4. Title:

SSW Culture

### 5. Meta description:

SSW's company culture is rooted in .NET consultancy, Scrum methodologies, and software development best practices. Experience our "Make it happen" approach, commitment to workplace happiness, and innovative tech solutions in Australia and beyond.

### 6. Related URLs:

https://www.ssw.com.au/company/about-us
https://www.ssw.com.au/company/history
https://www.ssw.com.au/rules

### 7. Content:

Copied and edited from https://www.ssw.com.au/ssw/Company/Culture/

(pasted below)

---

H2 SSW Culture
A company's culture pervades everything a company does, and as such our reputation for delivering high quality software comes from the SSW culture. As one of Australia's longest-running .NET consultancies, SSW is mature but flexible, always evolving to include the best cumulative values, attitudes, standards, and beliefs of the employees.

Though culture can be nebulous and changeable, it is a point of pride at SSW that our culture is always underpinned by the following:

H2 "Make it happen"
We work together to provide solutions to problems for our clients every day, and this proactivity happens internally too.

We are effective and make sure our time counts.

We always leave meetings with clear action items and knowing what's expected from everyone.

We use [Scrum](https://www.ssw.com.au/ssw/consulting/Scrum.aspx) extensively to help with prioritization and work transparency.

H2 Appreciation
We understand that not everyone communicates and listens the same way, and that what's important to some may not be important to all. However, it is human to want to feel appreciated for our effort, so at SSW we keep this in mind when making an employee feel valued for their work.

See our interview with Kylie Hunt, workplace happiness guru, on [the 5 languages of love](https://tv.ssw.com/6931/the-5-languages-of-appreciation-in-the-workplace-with-kylie-hunt).

H2 Innovation
Keeping on the cutting edge of technology, we're always looking out for the latest and greatest way of doing everything. We use the latest version of everything, sometime while it’s still in Beta (or even Alpha) stage. Being flexible and able to pivot as required means we’re ready for anything.

H2 Consistency
We have documented all of the best practices we can possibly think of in our [Rules to Better 'Everything'](https://rules.ssw.com.au/), and are always trying to make sure we're following and updating them whenever possible. We have also made a number of apps that enforce our coding standards in our work, such as [SSW Link Auditor](https://linkauditor.com.au/) and [SSW Code Auditor](https://www.codeauditor.com/).

We also have an extensive induction program built on [SugarLearning](https://www.sugarlearning.com/), which ensures we’re all on the same page with regards to our roles, rights, and responsibilities at the company. Each person who undertakes this induction is asked to provide feedback, to make sure the process is as fresh and accurate as possible.

H2 Community involvement
We run multiple user groups including the [Sydney](https://www.ssw.com.au/ssw/NETUG/Sydney.aspx), [Melbourne](https://www.ssw.com.au/ssw/NETUG/Melbourne.aspx), and [Canberra](https://www.ssw.com.au/ssw/NETUG/Canberra.aspx) .NET User Groups, the [Brisbane](https://www.ssw.com.au/ssw/NETUG/Brisbane.aspx) Full Stack User Group and the Fire User Group in [Beijing and Hangzhou](https://fireusergroup.com/). We encourage as many of our employees as possible to share their tech passions by speaking at other User Groups and industry events such as Ignite, Build, NDC, etc.

SSW also runs our own TV channel called [SSW TV](http://tv.ssw.com/), filled with content on the latest technologies. SSW TV encompasses everything from recordings of presentations and conferences, videos from our training courses, webinars, interviews and more. All content on SSW TV is available to anyone, 100% free, no sign up required.

H2 SSW Retreats
Once or twice a year the SSW guys and their families escape Sydney, Melbourne and Brisbane to attend SSW Retreats and spend some time together outside the office.

During these getaways, we do a bunch of fun activities together, have a hearty and delicious meal, and take an epic walk someplace beautiful.

{{ VIDEO }}

**Comment by tiagov8** [comment]
When page is live, please

- [x] Update link on https://www.ssw.com.au/company/about-us
- [x] Update link on https://github.com/SSWConsulting
- [x] Add a redirect from the old page
- [x] Update link on https://www.ssw.fr/about-us
- [x] Update link on SugarLearning https://my.sugarlearning.com/SSW/items/8147/ssw-a-culture-of-learning

**Comment by camillars** [comment]
(Edited by Tiago)

@sethdailyssw 

1. Please update the content in this Issue with optimised SEO details

**Comment by sethdaily** [comment]
> 1. Please update the content in this Issue with optimised SEO details
Done

**Comment by Harry-Ross** [comment]
As per my conversation with @tiagov8, all of the tasks have been completed.
