### ISSUE TITLE
📄 Document - Old Website zz'ed folders

### ISSUE THREAD

**Issue by amankumarrr** [SSWConsulting/SSW.Website#1426]
cc @bradystroud 

After we've marked everything as 'zz' in our old website repository, we'll need to generate a report listing all the items that have been 'zz'ed. Additionally, we must ensure that these 'zz'ed items are not publicly accessible.

```[tasklist]
### Tasks
- [ ] Create a list of zz'ed items in a report
- [ ] Get it approved by @tiago
```

**Comment by tiagov8** [comment]
Example of a file in a zz'ed folder: https://www.ssw.com.au/ssw/marketing/images/Garage%20signs/Garagewhitelogo.pdf

**Comment by wicksipedia** [comment]
closing as it is in progress at https://github.com/SSWConsulting/SSW.Website-v1-Progress

**Comment by tiagov8** [comment]
> closing as it is in progress elsewhere

Hey @wicksipedia I would expect a link here :)
