### ISSUE TITLE
📄 Visit China (and France) website URL without the utm source

### ISSUE THREAD

**Issue by hveraus** [SSWConsulting/SSW.Website#1428]
cc @camillars @amankumarrr @bradystroud 

URL: https://www.ssw.com.au/offices/hangzhou + https://www.ssw.com.au/offices/strasbourg

**Screenshots**
![WechatIMG5929](https://github.com/SSWConsulting/SSW.Website/assets/4745861/36556d2f-aa87-4267-817f-067a5433b7da)

This URL is pointed to https://www.ssw.com.cn

But in the source code - https://github.com/SSWConsulting/SSW.Website/blob/main/content/offices/hangzhou.mdx
the URL has a utm source, which is - https://www.ssw.com.cn/?utm_source=referral\&utm_medium=sswaustralia

1. Why is this happening?
2. Can I have the utm source in the URL

<img width="836" alt="image" src="https://github.com/SSWConsulting/SSW.Website/assets/4745861/ab9edfce-76fd-4a29-84e3-6c5c64ec2f6f">
Figure: source code of Hangzhou office page

**Comment by tiagov8** [comment]
Same for France page: https://github.com/SSWConsulting/SSW.Website/pull/1269

@KristenHu Please fix for France page as well

**Comment by tiagov8** [comment]
This is my attempt to fix https://github.com/SSWConsulting/SSW.Website/pull/1439

**Comment by amankumarrr** [comment]
@wicksipedia @bradystroud @tiagov8 @KristenHu 

This issue has been resolved by introducing a new field called `Visit Us`, which displays a link along with its title. Initially, we suspected it might be a bug related to Tina's functionality, but upon further investigation, I attempted to reproduce the issue by forking their branch, and I couldn't replicate it.

![ezgif com-optimize (1)](https://github.com/SSWConsulting/SSW.Website/assets/71385247/ad559a2d-1dd3-4791-8bba-bd68daefe07e)

**GIF: Showing the links with param using new field**

**Comment by tiagov8** [comment]
Hi @amankumarrr 

What do you think about changing the field name to be more intuitive

from

> Visit Us

to

> Local website link

**Comment by camillars** [comment]
[https://outlook-1.cdn.office.net/assets/reaction/like.png]     Camilla Rosa Silva [SSW] reacted to your message:




[cid:ssw-circle(1)_4c7259a6-23f6-49e5-b933-230ca304562e.png]

Camilla Rosa Silva
SSW Marketing Manager
Stalk: SSW People<https://www.ssw.com.au/people/Camilla-Rosa%20Silva?utm_source=emailsignature>   |   Walk: SSW Sydney<https://www.ssw.com.au/ssw/Company/Offices/?utm_source=emailsignature>   |   Talk: +61 426 007 665<https://www.ssw.com.au/ssw/Company/ContactUs.aspx>
[cid:youtube-icon_b8b5cda9-a973-4973-8763-cf3d4922e060.png] <https://www.youtube.com/c/SSWTV>    [cid:linkedin-icon_b153ac9a-eb66-47d9-9c51-ad20b42b8a0a.png]  <https://www.linkedin.com/company/ssw/>    [cid:twitter-icon_16ddd2de-0a0c-4b56-9986-6c5968e517d2.png]  <https://twitter.com/SSW_TV>    [cid:teams-icon_552803c2-9c44-4267-b563-7fe1a7a0e589.png] ***@***.***>


        ⭐️ 2023 Microsoft Partner of the Year Finalist<https://www.ssw.com.au/SSW/Consulting/Case-Study/Shepherd-Centre.aspx>

________________________________

**Comment by amankumarrr** [comment]
@tiagov8 agreed and updated its label name.
