### ISSUE TITLE
✨ SSW France - embed a new AI powered chatbot 

### ISSUE THREAD

**Issue by amankumarrr** [SSWConsulting/SSW.Website#1429]
@sethdailyssw @JeanThirion @camillars 
URL: https://ssw.fr/
Subject: RE: Chatbot for SSW's China website

**Description:**
Just like SSW Australian website, we need to embed a chatbot to our SSW France website.

**Comment by sethdaily** [comment]
@amankumarrr @tiagov8 
FYI Aman - I wouldn't have made this issue in the SSW.Website repo - this repo is for the Australian website.

The french chatbot is trained and ready for the website.

1. To embed, use the script from [Chatbase](chatbase.co)

**Comment by amankumarrr** [comment]
@wicksipedia @sethdailyssw @bradystroud @JeanThirion @camillars  

This implementation is now in place, and I have responded to the email with the subject "RE: Chatbot for SSW's China website".

<img width="1271" alt="chatbotFrance" src="https://github.com/SSWConsulting/SSW.Website/assets/71385247/f83aa056-bd8b-4028-a40f-e1aca6a57dc0">

**Figure: Showing chatbot on SSW France's office**
