### ISSUE TITLE
💸 Tech Debt - webP not being used for image optimization for prod

### ISSUE THREAD

**Issue by duanxinhuan** [SSWConsulting/SSW.Website#1461]
It was observed that webP is being served for images during local dev but not prod

This affects pagespeed insights

```[tasklist]
### Tasks
- [ ] Ensure Image Optimization API is being used for images e.g. Tina, old SSW website (biggest improvements here)
```

**Comment by wicksipedia** [comment]
From reading the docs - https://nextjs.org/docs/app/api-reference/components/image#remotepatterns

Remote patterns needs to be setup so that the image optimization API can be used with Tina images

**Comment by Harry-Ross** [comment]
From my investigation, by changing to remote patterns, there has been no automatic conversation of images to webp on production:

![image](https://github.com/SSWConsulting/SSW.Website/assets/20507092/30d628e6-e8b8-4371-8873-88b2f960eca3)
**Figure: Same format used on next/image sourced images**

Test environment can be found here: https://app-sswwebsite-9eb3-pr-1515.azurewebsites.net/

However, it would still be good to move from using `domains` to `remotePatterns` as per the documentation: https://nextjs.org/docs/app/api-reference/components/image#remotepatterns

**Comment by wicksipedia** [comment]
looks like root cause is that `sharp` isn't running in the container

![image](https://github.com/SSWConsulting/SSW.Website/assets/600044/ba23276b-b382-4d39-a561-d0428d4ed497)

**Comment by wicksipedia** [comment]
Done - images are now being served with modern formats

![CleanShot 2023-10-20 at 11 47 05@2x](https://github.com/SSWConsulting/SSW.Website/assets/600044/57aa475f-c8db-4213-8546-96e88d18034e)
