### ISSUE TITLE
✨ Use SSR for SSW website

### ISSUE THREAD

**Issue by duanxinhuan** [SSWConsulting/SSW.Website#1462]
**Is your feature request related to a problem? Please describe.**
It looks like the content in Tina is not pre-generated
![image](https://github.com/SSWConsulting/SSW.Website/assets/48227836/2274dae6-de09-45ee-965b-3e26b7eebaa9)

**Describe the solution you'd like**
Just use async page component:
![image](https://github.com/SSWConsulting/SSW.Website/assets/48227836/c746dbba-3bcb-41b4-b643-cb5cb3c6569b)

**Comment by Harry-Ross** [comment]
We can't actually do this - as we are using the pages router and not the app router (as used in the screenshot above). We can only fetch from a page-level and not a component-level, which means we have to do client-side data fetching in some rare cases. 

Also, in the above screenshot you provided, SSR is used, the data comes in from `getStaticProps`, which means the props data that goes into the page is statically generated.

**Comment by wicksipedia** [comment]
As per our conversation, this can be closed.

We demo'd the fact that the first load experience is HTML, then the browser switches over to a React app and navigation is then done with less data (json) and React rendering pages (faster)
