### ISSUE TITLE
💸 CSS UI - Heading for content pages are weird

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.Website#1473]
**Description**  

We recently created this page which is basic content (headings, list, paragraphs)
https://www.ssw.com.au/privacy

The visual hierarchy of headings is weird and inconsistent. E.g. H3 is smaller and lighter than H4

<img width="776" alt="Screenshot 2023-09-28 at 8 42 17 AM" src="https://github.com/SSWConsulting/SSW.Website/assets/12601228/fec62779-7258-4813-8e14-01bd32804f85">

**Proposed solution**  

- [ ] 1. Please implement styles for headings as per https://getbootstrap.com/docs/5.0/content/typography/

**Note:** This should be the basic CSS, for any plain page. We do have different pages, like the consulting ones (e.g. https://www.ssw.com.au/consulting/web-applications) that have different styles and it is OK

**Comment by tiagov8** [comment]
Related to https://github.com/SSWConsulting/SSW.Website/issues/804

**Comment by tiagov8** [comment]
**Note:** @jaydenalchin is working on this new Design Library that is the master documentation of this: https://www.figma.com/file/MoIHv08pADh7dzQdH4mTNi/SSW-Design-Library?type=design&node-id=890%3A675&mode=design&t=oqFpIDfBCVqW16G5-1

**Comment by amankumarrr** [comment]
@tiagov8 

Done 

| Before | After |
|-----|------|
| **h1**| |
| font-weight | |
| 300 | 500 |
| margin-bottom | |
| 18px | 0.5rem |
| **h2** ||
| font-size ||
| 18px | 2rem|
| line-height||
|27px | 2.4rem |
| margin-bottom ||
| 11.25px | 0.5rem |
| font-weight||
| 300 | 500|
| **h3** | |
| font-weight||
| 300 | 500 | 
| margin-bottom||
| 7px | 0.5rem | 
| line-height || 
| 36px | 2.1rem|
| font-size ||
| 22.5px | 1.75rem |
| **h4** || 
|font-weight||
| 600 | 500 |
| line-height ||
| 33.75px | 1.8rem |
| margin-bottom ||
| 11.25px | 0.5rem |
| font-size ||
| 22.5px | 1.5rem | 


**Screenshot**
<img width="814" alt="image" src="https://github.com/SSWConsulting/SSW.Website/assets/71385247/19243815-b87e-42a6-a141-ae40969797f2">

**Figure: Privacy page after changing the typography's changes**

**Comment by tiagov8** [comment]
Hey @amankumarrr 

Although the font sizes are fixed, the H4 margins are bad...

- [x] 1. Please add a `1.5rem` margin top for H4s

**Comment by tiagov8** [comment]
Since you're dealing with CSS, we also want lists to be squared instead of circles.

- [x] 2. Please make content ULs to be `list-style-type: square;`

**Comment by amankumarrr** [comment]
@tiagov8 
Done 

<img width="699" alt="image" src="https://github.com/SSWConsulting/SSW.Website/assets/71385247/eb7f22d4-8042-4a82-b624-07ebdaf82136">

**Figure: h4s' margining and UL's styling**
