### ISSUE TITLE
✨ Events booking - add a '+GST' option

### ISSUE THREAD

**Issue by sethdaily** [SSWConsulting/SSW.Website#1518]
As per email subject: RE: Training page changes
cc @UlyssesMaclaren @bradystroud @Levijj22 

**Is your feature request related to a problem? Please describe.**
Events pages > Events Booking component - we should be able to choose 'inc GST' or '+GST'
Currently it is locked at 'inc GST'

**Describe the solution you'd like**
A dropdown menu to choose between 'inc GST or '+GST'

**Describe alternatives you've considered**
It could be a checkbox e.g. check the box for 'inc GST'

![image](https://github.com/SSWConsulting/SSW.Website/assets/130118701/a2bf4b04-3fc6-4fc2-a232-e917424785aa)
Figure: Put the option on the left

**Comment by amankumarrr** [comment]
@sethdailyssw 
Dropdown added to select the options for GST. 

**screenshots**
<img width="764" alt="image" src="https://github.com/SSWConsulting/SSW.Website/assets/71385247/613d26c5-8d62-4fec-97b1-63612938b087">
**Figure: GST text coming from the GST Text option from the dropdown**

**Comment by amankumarrr** [comment]
@sethdailyssw @bradystroud 
This change is now live, and I've also resolved the Recaptcha key error. This was necessary because we recently added the booking inquiry form to our `customized-courses` page, which required a site key.
