### ISSUE TITLE
💸 TinaCMS - Improve COLLECTIONS titles 

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.Website#1522]
cc @bradystroud @jaydenalchin @adamcogan 

Hi @Harry-Ross 

I think we can make the sections' (collections) titles more friendly/consistent in TinaCMS

- [x] 1. Change from "Employment Pages" to "Employment - Index"
- [x] 2. Change from "Opportunities" to "Employment - Opportunities"
- [x] 3. Change from "Technology Cards" to "Consulting -  Technology Cards"
- [x] 4. Change from "Technology Badges" to "Consulting -  Technology Badges"
- [x] 5. Change from "Office - Index" to "Offices - Index"
- [x] 5. Change from "Office Pages" to "Offices Pages"
- [x] 6. Move Offices sections to be together (Make index the 1st)
- [x] 7. Change from "Presenters" to "Events - Presenters"
- [x] 8. Change from "Locations" to "Events - Locations"
- [x] 9. Move Events sections to be together (Make index the 1st)
- [x] 10. Change from "Marketing" to "Marketing Pages"
- [x] 11. Change from "Payment Details" to "Company - Payment Details"
- [x] 12. Move Company sections to be together (Make index the 1st)
- [x] 13. Change from "Testimonial Categories" to "Testimonials - Categories"
- [ ] 14. Why is "newsletters.mdx" under "Pages" and not "Newsletters"? Should we have a new section "Newsletters - Index" to put that file there?

---

- [x] Once all the above is done please send a test please to @tiagov8 

<img width="385" alt="Screenshot 2023-10-10 at 9 20 59 AM" src="https://github.com/SSWConsulting/SSW.Website/assets/12601228/fe81f582-c97a-4696-b6ae-ba34ce043b30">

**Comment by amankumarrr** [comment]
@wicksipedia @bradystroud 

Hi @tiagov8, 

I believe it would be beneficial to reorganize the content in a more logical order and group it by starting word characters. This approach will enhance the ease of searching for pages. What are your thoughts on this idea?

<img width="172" alt="image" src="https://github.com/SSWConsulting/SSW.Website/assets/71385247/dd0687be-47df-4d57-8da9-7eb807d72ff2">
<br>
<img width="169" alt="image" src="https://github.com/SSWConsulting/SSW.Website/assets/71385247/fbaa7f2b-3979-4c4b-aba1-122bf6699953">

**Figure: Collections in logical order**

**Comment by amankumarrr** [comment]
here is the PR for testing - https://github.com/SSWConsulting/SSW.Website/pull/1537

**Comment by tiagov8** [comment]
Hi @amankumarrr , 

I see your point but I do prefer to group by area (Consulting, Training, Company, Employment etc).

Hey @jaydenalchin 

Can we have your thoughts?

**Comment by jaydenalchin** [comment]
> Hey @jaydenalchin
> 
> Can we have your thoughts?

I think grouping by area makes sense. Organising these in a way that reflects the site structure would make things easiest to find.

**Comment by wicksipedia** [comment]
Prefix by area should be a no-brainer... we do it for PBI titles, commit messages, email subjects

**Comment by amankumarrr** [comment]
@wicksipedia @bradystroud 

Hi @tiagov8, 

> 14. Why is "newsletters.mdx" under "Pages" and not "Newsletters"? Should we have a new section "Newsletters - Index" to put that file there?

We are currently utilizing a shared template for all pages that do not have child pages under their route. As a result, `newsletters.mdx` resides in the `Pages` directory along with other standalone pages. While it's possible to create a new section for `Newsletters - Index`, it appears that this would duplicate the existing code and serve no specific purpose. Please let me know what your thoughts are.

**Comment by tiagov8** [comment]
@amankumarrr 

> We are currently utilizing a shared template for all pages that do not have child pages under their route. As a result, newsletters.mdx resides in the Pages directory along with other standalone pages. While it's possible to create a new section for Newsletters - Index, it appears that this would duplicate the existing code and serve no specific purpose. Please let me know what your thoughts are.

Not very clear on the reasons. If we think about it, every monthly newsletter will be a child of "Newsletters".

Anyways, for consistency, I think having the "Newsletter - Index" collection makes it more intuitive.

**Comment by bradystroud** [comment]
Hey @tiagov8 

Thanks for your assistance with this one 🙂

Although I agree `Newsletter - Index` would be clearer it would require a bit of refactoring.

Happy for you to make a PBI but I think its low ROI.

**Comment by amankumarrr** [comment]
@tiagov8 @bradystroud @wicksipedia @jaydenalchin 
I've updated the order and labels of our collections as per requested by @tiagov8. 

>  14. Why is "newsletters.mdx" under "Pages" and not "Newsletters"? Should we have a new section "Newsletters - Index" to put that file there?

I will close this issue after deciding on the task above. 

<img width="256" alt="image" src="https://github.com/SSWConsulting/SSW.Website/assets/71385247/bc459c6c-014b-4465-a11a-468b864b2a45">
<br>
<img width="257" alt="image" src="https://github.com/SSWConsulting/SSW.Website/assets/71385247/88488b6d-81ca-4d5e-88df-6de7ea8b4f14">

**Figure: Collections order by area**

**Comment by amankumarrr** [comment]
as per my conversation with @tiagov8, he's happy to close this issue.
