### ISSUE TITLE
💸 Update "Work Experience" position 

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.Website#1526]
cc @wicksipedia @BrookJeynes @bradystroud 

**Description**  

as per my conversation with @PennyWalker and @adamcogan 

Looking at https://www.ssw.com.au/employment we see the position "Word Experience" marked as **'filled'** . 
We assume it's because we have the page https://www.ssw.com.au/training/internship-fullstack to take care of these candidates.

However, having the opportunity there as 'filled' is confusing. Candidates might assume we are simply not accepting application for it any longer.

**Proposed solution**  

- [x] Change from "Work Experience" to "Work Experience / Internship"
- [x] Make that position available
- [x] Add a link to the Internship page

   **Note:** People get to this list by clicking "[Experienced Professionals](https://www.ssw.com.au/employment#available)" button

**Comment by adamcogan** [comment]
1. See image - feels like a wall of text
2. Can you add an image from the internship page
3. Can you make the link to the internship page more obvious 
4. The big red banana button has a link to Lucia's email who has left SSW. Before fixing, can you check for any other instances
5. See if we have a generic email like sswwdailyscrum@

![image](https://github.com/SSWConsulting/SSW.Website/assets/1222712/4aa49de0-321f-48da-83dd-18f17bcd5053)

**Comment by tiagov8** [comment]
For reference:

<img width="718" alt="Screenshot 2023-10-19 at 1 25 59 PM" src="https://github.com/SSWConsulting/SSW.Website/assets/12601228/73128178-70cd-43d8-af10-a8c5fd18a623">
