### ISSUE TITLE
🐛 New Mega Menu - Call us link

### ISSUE THREAD

**Issue by 2fernandez** [SSWConsulting/SSW.Website#1534]
**Describe the bug**

Hi, 
this issue was previously reported and fixed in this issue:
https://github.com/SSWConsulting/SSW.Website/issues/1300

- [ ] Can you please ensure that the functionality of "Contact us" on desktop and "Call us" on mobile are maintained in the new version of the mega menu

![Screenshot 2023-10-13 at 10 49 39 am](https://github.com/SSWConsulting/SSW.Website/assets/27670973/82acc6f5-ce84-46ae-91ae-08eb2db992f7)

**Comment by wicksipedia** [comment]
Done

![CleanShot 2023-10-20 at 16 16 26](https://github.com/SSWConsulting/SSW.Website/assets/600044/c9982899-e52c-4cf6-82fb-65e8eb422286)

![CleanShot 2023-10-20 at 15 52 38](https://github.com/SSWConsulting/SSW.Website/assets/600044/32c09191-2c7f-47ad-a2b3-ce255748fcab)
