### ISSUE TITLE
🐛 Outdated Twitter Logo

### ISSUE THREAD

**Issue by YalalCakirSSW** [SSWConsulting/SSW.Website#1536]
cc @camillars @hveraus 

(Checked by @amankumarrr )
**Describe the bug**
On the website footer, we are still using the old Twitter logo. We need to update it to X logo.

**Expected behavior**
X logo is shown for the Twitter shortcut. 

More info https://about.twitter.com/en/who-we-are/brand-toolkit

**Screenshots/Video**

<img width="287" alt="outdatedlogo" src="https://github.com/SSWConsulting/SSW.Website/assets/144093109/56b7b2a3-7a08-428c-a844-5a5d8afb6b21">

Figure: Outdated Twitter Logo

**Comment by amankumarrr** [comment]
@YalalCakirSSW @camillars @hveraus @wicksipedia 

Updated the Twitter's logo
<img width="327" alt="image" src="https://github.com/SSWConsulting/SSW.Website/assets/71385247/b01b09bc-44e3-44bc-9f3b-3a302ff94982">
