### ISSUE TITLE
🐛 New Mega Menu - Make dropdown close after a click

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.Website#1538]
cc @hveraus @wicksipedia @adamcogan 

The new menu looks awesome. However, we need to make the dropdown automatically close after a click... 
Keeping it open is unexpected (bug) + makes it hard to see the selected page has actually open 

**To Reproduce**
1. Click on `Services` from the navbar 
2. Menu - Click on `Application Development` 
3. Menu - Now click on `Website Development` - dropdown will stay open here 

**Expected behavior**
It should close its menu when navigating to a new page. 

 
- [x] 1. Please fix

https://github.com/SSWConsulting/SSW.Website/assets/12601228/12780ab8-82b1-4322-8fd0-5a16633281f6

**Comment by amankumarrr** [comment]
@tiagov8 @wicksipedia @bradystroud @Harry-Ross 
This issue has been fixed.

![7A0A2901-14A7-45EC-A51A-4D53AFA95F72](https://github.com/SSWConsulting/SSW.Website/assets/71385247/a0c70e8c-ab04-497d-a480-4a2bcb5330a6)

**GIF: Showing Megamenu being closed on navigation**
