### ISSUE TITLE
🐛 Megamenu - Does not automatically close when navigating

### ISSUE THREAD

**Issue by amankumarrr** [SSWConsulting/SSW.Website#1545]
**Describe the bug**
Our new mega menu doesn't close when we click on a specific category and then navigate to a page within the same category.

**To Reproduce**
1. Click on `Services` from the navbar 
2. Menu - Click on `Application Development` 
3. Menn- Now click on `Website Development` - Menu will stay open here 

**Expected behavior**
It should close its menu when navigating to a new page. 

**Screenshots/Video**

https://github.com/SSWConsulting/SSW.Website/assets/71385247/65037396-c9aa-4d30-8ea0-3406056e389e 
**Video: Showing the error when navigating to a page within the same category**

**Comment by tiagov8** [comment]
Hi @amankumarrr 

I believe this is a duplicate of https://github.com/SSWConsulting/SSW.Website/issues/1538

1. Please confirm and close this one with a link
2. Add more details to the other Issue if you think it's necessary

**Comment by amankumarrr** [comment]
@wicksipedia @bradystroud 

Hi @tiagov8, 

Yes, it's a duplication of #1538, therefore, I'm closing this issue.

Thanks
