### ISSUE TITLE
📄 Footer - Improve social media icons

### ISSUE THREAD

**Issue by hveraus** [SSWConsulting/SSW.Website#1549]
URL: ssw.com.au 

- [x] 1. Change the Github icon bg color to  for better contrast with the bg
<img width="192" alt="Screenshot 2023-10-18 at 11 49 54" src="https://github.com/SSWConsulting/SSW.Website/assets/4745861/e7ee7fe9-d4f6-4632-bda8-615e838f0c95">

- [x] 2. Change the hover style. 
Hover with 70% opacity.
![image](https://github.com/SSWConsulting/SSW.Website/assets/4745861/d62006a7-35e0-4ab6-8b06-3a297ef966c4)

- [x] 3. Updated twitter icon as related to - https://github.com/SSWConsulting/SSW.Website/issues/1536

**Comment by amankumarrr** [comment]
@hveraus @wicksipedia
Done 
<img width="374" alt="image" src="https://github.com/SSWConsulting/SSW.Website/assets/71385247/ef595266-3684-4261-8136-fbe1a96a6bd0">

**Figure: Social Icons on the homepage**
