### ISSUE TITLE
📄 Megamenu - Chinafy needs to stand out more e.g. add a China flag

### ISSUE THREAD

**Issue by piers-sinclair** [SSWConsulting/SSW.Website#1551]
URL: MEGA MENU

**From:**

No Chinese flag

**To:**

Include Chinese Flag

**Screenshots**
![Figure: Make Chinafy service stand out more with something like a Chinese flag](https://github.com/SSWConsulting/SSW.Website/assets/79821522/c5becf10-6cf6-45d3-a815-39a2cada9b9b)

**Comment by amankumarrr** [comment]
@pierssinclairssw @wicksipedia 

Done - Flag added for Chinafy in megamenu. Test pass by @hveraus 
<img width="688" alt="image" src="https://github.com/SSWConsulting/SSW.Website/assets/71385247/4ae98ed9-f9f5-4bd8-a3f8-dfd243cc2c69">

**Figure: Chinafy with Chinese's flag in megamenu**
