### ISSUE TITLE
✨ Testimonial boxes should be editable

### ISSUE THREAD

**Issue by sethdaily** [SSWConsulting/SSW.Website#1556]
@samsmithssw @UlyssesMaclaren @camillars @amankumarrr @bradystroud 
**Is your feature request related to a problem? Please describe.**
When editing a consulting page, there is no way to choose the testimonials.

**Describe the solution you'd like**
A feature that lets the user choose which testimonials should be on the page (identical to technology boxes)

**Describe alternatives you've considered**
no

**Additional context**
![image](https://github.com/SSWConsulting/SSW.Website/assets/130118701/e3167782-3a77-4201-b4d5-f422420fba23)
**Figure: Put the feature here**

**Comment by Harry-Ross** [comment]
I think with the number of consulting pages, it may also be an option to have optional references to testimonial categories in each consulting page.

**Comment by sethdaily** [comment]
@Harry-Ross can you give an example? I'm not exactly sure what you mean

**Comment by Harry-Ross** [comment]
Right now, we have a couple specific testimonial categories such as video, internship, clean architecture workshop - so we could create a category for web development or Blazor or something. This means we can reuse web development testimonials across web development pages for example.

**Comment by sethdaily** [comment]
Can you make a category option and a custom option so we can use just a category when it suits, but we can cutsomize if needed?

**Comment by bradystroud** [comment]
Allowing custom testimonials will add a lot of maintenance work. 👎
Categories are a great way of having specific testimonials on each page without all the maintenance. This is already implemented.

Allowing custom testimonials on each page has low ROI. The focus should be on migrating the old website not adding new functionality.

This PBI is on hold for now.

**Comment by sethdaily** [comment]
@bradystroud
Disagree about the ROI...but maybe the categories will suffice for now

1. Can you call me Monday and show me how to choose the testimonial category

![image](https://github.com/SSWConsulting/SSW.Website/assets/130118701/c425141e-c9d7-46a4-bda5-34d14d8a0995)
**Figure: This is all I see**

**Comment by tiagov8** [comment]
Hi @sethdaily 

1. Please watch https://youtu.be/UR-PCeOaNZY from https://github.com/SSWConsulting/SSW.Website/issues/2008 by @amankumarrr 

2. See if that solves this Issue (Then close it if yes)

**Comment by sethdaily** [comment]
Hi @tiagov8 

> Please watch https://youtu.be/UR-PCeOaNZY from ✨ Testimonials - Make them reorderable and filterable  #2008 by @amankumarrr

Done

> See if that solves this Issue (Then close it if yes)

Done - issue closed - it makes the testimonials reorderable.
