### ISSUE TITLE
📄 Index page - Kill Application Development category

### ISSUE THREAD

**Issue by sethdaily** [SSWConsulting/SSW.Website#1557]
@bradystroud @UlyssesMaclaren @samsmithssw @jaydenalchin 
URL: https://www.ssw.com.au/consulting?tag=Application-Development
Pain: There are too many categories.
Solution (one of many): Everything in the Application Development category could be in either Mobile or Website Development

1. Redistribute everything in Application Development
2. Kill the Application Development category
3. Move PowerBI to Platform
4. Move Enterprise Reporting to Database

**Screenshots**
![image](https://github.com/SSWConsulting/SSW.Website/assets/130118701/c7759349-c127-44e5-a6ff-b3c549a454c9)
**Figure: Get rid of this**

**Comment by UlyssesMaclaren** [comment]
Hey Seth,

Agreed.


  1.  Can we also change from
                Website Development
To
                Web Development?











Ulysses Maclaren   |   SSW General Manager<http://www.ssw.com.au/People/Ulysses-Maclaren?utm_source=emailsignature>   |    +61 419 418 232<https://www.ssw.com.au/ssw/Company/Offices/?utm_source=emailsignature>   |   Ping me on ***@***.***>

From: Seth Daily [SSW] ***@***.***>
Sent: Thursday, October 19, 2023 12:46 PM
To: SSWConsulting/SSW.Website ***@***.***>
Cc: Ulysses Maclaren [SSW] ***@***.***>; Mention ***@***.***>
Subject: [SSWConsulting/SSW.Website] 📄 Index page - Kill Application Development category (Issue #1557)


@bradystroud<https://github.com/bradystroud> @UlyssesMaclaren<https://github.com/UlyssesMaclaren> @samsmithssw<https://github.com/samsmithssw> @jaydenalchin<https://github.com/jaydenalchin>
URL: https://www.ssw.com.au/consulting?tag=Application-Development
Pain: There are too many categories.
Solution (one of many): Everything in the Application Development category could be in either Mobile or Website Development

  1.  Redistribute everything in Application Development
  2.  Kill the Application Development category
  3.  Move PowerBI to Platform
  4.  Move Enterprise Reporting to Database

Screenshots
[image]<https://user-images.githubusercontent.com/130118701/276450307-c7759349-c127-44e5-a6ff-b3c549a454c9.png>
Figure: Get rid of this

**Comment by sethdaily** [comment]
@Harry-Ross I don't think you changed this in the megamenu

From
                Website Development
To
                Web Development?

1. Check please and change

**Comment by Harry-Ross** [comment]
@sethdailyssw 
> I don't think you changed this in the megamenu

Completed in https://github.com/SSWConsulting/SSW.Website/pull/1572
