### ISSUE TITLE
💸 Megamenu - export it as a component

### ISSUE THREAD

**Issue by wicksipedia** [SSWConsulting/SSW.Website#1560]
**Description**  
In order to get the new megamenu out sooner, we shipped a version that is only built on the main website.

This needs to be able to be used on `/people` and `/rules`

**Proposed solution**  

1. This is blocked by #1559
2. Add an api endpoint to retrieve the layout as configured in Tina
3. Move the megamenu code to `/lib`
4. Megamenu - if layout data prop is not passed in, go to api endpoint to retrieve layout data (maybe store in local storage for 1 hour so that we don't have to call it all the time)
5. Megamenu - add a new prop to generate the link (remove the dependency on next/link since rules and people use gatsby - they should inject their own implementation)
6. Publish megamenu as a new npm package that can be picked up by people and rules

```[tasklist]
### Tasks
- [ ] https://github.com/SSWConsulting/SSW.Rules/issues/1188
- [ ] https://github.com/SSWConsulting/SSW.Website/issues/2115
```

**Comment by Harry-Ross** [comment]
Update:

I have the menu working with Rules locally:



![Image](https://github.com/SSWConsulting/SSW.Website/assets/20507092/6a2c3c91-845d-4fd1-85f3-badff242a577)
**Figure: Before**

![Image](https://github.com/SSWConsulting/SSW.Website/assets/20507092/c32a87dc-a672-432f-9691-a5f54a5b89cc)
**Figure: After**

This is with an optional logo override value in the menu props, to allow for different logos on People + Rules
