### ISSUE TITLE
🧑‍💻 DevOps - Fix Broken Issue Action

### ISSUE THREAD

**Issue by Harry-Ross** [SSWConsulting/SSW.Website#1574]
cc @bradystroud 

Currently, https://github.com/SSWConsulting/SSW.Website/actions/workflows/issue-add-to-project.yml is broken. This already happens automatically via GitHub - so we don't need it.

```[tasklist]
### Tasks
- [x] Remove the broken projects action
```

**Comment by bradystroud** [comment]
Done - Deleted in PR #1575
