### ISSUE TITLE
💸 Tech Debt - .NET UG Fallback Image

### ISSUE THREAD

**Issue by Harry-Ross** [SSWConsulting/SSW.Website#1600]
As per my conversation with @amankumarrr, the current .NET UG page when no SharePoint data has been provided looks off. 

```[tasklist]
### Tasks
- [x] Add a fallback banner similar to events with the .NET UG logo in the centre
- [x] Get it approved from designer
```

**Comment by hveraus** [comment]
@Harry-Ross @amankumarrr 
Hi guys, the idea I had before was to keep the last presenter and the topic and link off to the youtube event replay. 
would that be easier to implement and we can still direct some traffic to our YouTube channel?

**Comment by amankumarrr** [comment]
> @Harry-Ross @amankumarrr Hi guys, the idea I had before was to keep the last presenter and the topic and link off to the youtube event replay. would that be easier to implement and we can still direct some traffic to our YouTube channel?

@camillars @bradystroud @wicksipedia can we show the old user group instead of not showing anything?

**Comment by amankumarrr** [comment]
@wicksipedia @bradystroud @Harry-Ross 
Hi Team, 

As per my conversation with @camillars, @hveraus, and @MarcusIrmscherSSW, we've agreed on displaying the most recent user group information on the User Group pages. This change is desired to improve the User Group pages, as they currently appear incomplete without the upcoming User Group data.

**Comment by amankumarrr** [comment]
@Harry-Ross @wicksipedia @bradystroud @hveraus 

Done - We are displaying the latest UG now and it's live now

<img width="800" alt="image" src="https://github.com/SSWConsulting/SSW.Website/assets/71385247/9f51332d-97d8-4e69-8dc9-854febf990d1">

**Figure: Melbourne's UG page on production**
