### ISSUE TITLE
🐛 Testimonials - Rating are not showing properly

### ISSUE THREAD

**Issue by hveraus** [SSWConsulting/SSW.Website#1607]
**Describe the bug**

The rating for testimonials cards is not showing correctly. 

URL - https://www.ssw.com.au/admin/index.html#/collections/edit/testimonials/Chinafy-Ma
<img width="1111" alt="image" src="https://github.com/SSWConsulting/SSW.Website/assets/4745861/e3274a9e-8320-4817-80c1-824526df3a9e">

URL - https://www.ssw.com.au/admin/index.html#/collections/edit/testimonials/Chinafy-Neil
<img width="1102" alt="image" src="https://github.com/SSWConsulting/SSW.Website/assets/4745861/3f65b895-2a10-42a7-a7a6-436f99f70ba6">

**Comment by jeoffreyfischer** [comment]
**Description**: 
The rating was not showing the current value in the testimonial Edit page - all values were set to -1. 

**Solution**: 
The rating is now showing the current value in the testimonial Edit page (reason: default value was wrongly called).

- Affected routes: /admin

- Fixed #1607

**Screenshots**

![website-PR-002a](https://github.com/SSWConsulting/SSW.Website/assets/106663901/e556c0ec-baf7-49ea-b883-9b0d1c7064e7)
**Figure**: Stored rating value is 5 in this example.

![website-PR-002b](https://github.com/SSWConsulting/SSW.Website/assets/106663901/f9b773de-e461-4c12-ba03-76fe30912597)
**Figure**: The value 5 is properly rendered in the UI (this was already the case before working on this PBI).

![website-PR-002c](https://github.com/SSWConsulting/SSW.Website/assets/106663901/9c615a25-4651-4f3a-b77d-6ca60e8bbc14)
**Figure**: Now, the value 5 is also rendered in the testimonial Edit page (it used to be -1 for all testimonials).

**Comment by jeoffreyfischer** [comment]
**Extra fix**: 
I have added an error message if the rating value is not within the range [-1; 5]. 

**Screenshots**:

![website-PR-002d](https://github.com/SSWConsulting/SSW.Website/assets/106663901/9a1a2c9a-0e02-45f8-9a6d-5d5c075583af)
**Figure**: If the rating is outside of the [-1; 5] range ...

![website-PR-002e](https://github.com/SSWConsulting/SSW.Website/assets/106663901/0cafa7be-56e1-46b2-bc9d-fa1d4aa2ee2f)
**Figure**: ... an error message is shown in the UI
