### ISSUE TITLE
📄 Clean Architecture SuperPowers Tour

### ISSUE THREAD

**Issue by danielmackay** [SSWConsulting/SSW.Website#1610]
Hi @amankumarrr,

As per our conversation, please update so that the agenda of the SuperPowers and Workshop are the same

URL: https://ssw.com.au/events/clean-architecture-superpowers-tour

**From:**

  
![image](https://github.com/SSWConsulting/SSW.Website/assets/2636640/3b16c741-f20c-4a91-bb6c-00b6a5d52a77)

**To:**

  
![image](https://github.com/SSWConsulting/SSW.Website/assets/2636640/285e3a86-2592-4a35-8b14-76c06e4a4a82)

**Comment by amankumarrr** [comment]
@danielmackay @wicksipedia 
done.
<img width="674" alt="image" src="https://github.com/SSWConsulting/SSW.Website/assets/71385247/5966569c-8472-4936-b589-74c5a01767fe">

**Figure: Showing updated agenda for the CA superpower page**
