### ISSUE TITLE
📄.NET UG Events Archive - Migrate to SharePoint

### ISSUE THREAD

**Issue by Harry-Ross** [SSWConsulting/SSW.Website#1629]
As per my conversation with @adamcogan, @bradystroud, @pierssinclairssw, @wicksipedia, we have chosen to migrate the events on [ssw.com.au/ssw/NETUG/PastSessions.aspx](https://www.ssw.com.au/ssw/NETUG/PastSessions.aspx) to SharePoint. 

```[tasklist]
### Tasks
- [x] Migrate all events to the SSW Events calendar
```

**Comment by jeoffreyfischer** [comment]
**Description**: 
The events must be migrated :
From 
 &nbsp; &nbsp; SSW main website (URL: https://www.ssw.com.au/ssw/NETUG/PastSessions.aspx ) 
To 
  &nbsp; &nbsp; Sharepoint (URL: https://sswcom.sharepoint.com/sites/Events/Lists/Events/Events%20Calendar.aspx ). 

**Solution**: 
The events have been migrated.


**Screenshots**: 

![website-PR-001a](https://github.com/SSWConsulting/SSW.Website/assets/106663901/8175eccf-6dd5-4de2-af79-22d6fdd26b10)
**Figure**: First event in Sharepoint

![website-PR-001b](https://github.com/SSWConsulting/SSW.Website/assets/106663901/690e56de-26e3-4a73-8ca6-5e8e70409333)
**Figure**: Last event in Sharepoint
