### ISSUE TITLE
📄 Migrate Awards page

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.Website#1681]
### 1. People in the loop:

@tiagov8 @bradystroud 

https://ssw.com.au/ssw/Company/Awards/

### 2. Page template to copy:

https://www.ssw.com.au/company/news

### 3. CRM Record (only for consulting service pages):

This shouldn't be required if is only for Consulting

### 4. URI:

https://www.ssw.com.au/company/awards

### 5. Title:

Awards

### 6. Meta description:

SSW is a multi-award winning Australian company. We have many Microsoft Certifications, several MVPs, and a Microsoft Regional Director. Here are some of our awards and recognitions.

### 7. Related URLs:

https://www.ssw.com.au/company/news

### 8. Content:

From https://ssw.com.au/ssw/Company/Awards/

**Comment by UlyssesMaclaren** [comment]
change title from Premier to Leading

**Comment by amankumarrr** [comment]
@tiagov8 @UlyssesMaclaren 

Done 


> Here are some of our awards and recognitions. 

For meta description, this is removed due to the limit on description field

- [x] Include done video or screenshots
<img width="947" alt="Awards" src="https://github.com/SSWConsulting/SSW.Website/assets/71385247/6061ec3f-5387-41f0-8cbf-e86097040953">

**Figure: Newly migrated Awards page**

**Comment by tiagov8** [comment]
Hi @amankumarrr 

- [x] 1. Can we make the Awards section divided in 2 columns (to avoid the huge white space)?

<img width="1501" alt="Screenshot 2023-12-15 at 10 38 35 AM" src="https://github.com/SSWConsulting/SSW.Website/assets/12601228/718ba125-9430-46a3-b87b-6740f6b5e3d7">

**Comment by amankumarrr** [comment]
Hi @tiagov8,

Done - Please see 
<img width="928" alt="image" src="https://github.com/SSWConsulting/SSW.Website/assets/71385247/431397cd-aaa0-4c60-9930-0c38cc5e930e">

**Figure: Awards' in horizontal to remove whitespace**

**Comment by tiagov8** [comment]
Related Issue: https://github.com/SSWConsulting/SSW.Website/issues/2296
