### ISSUE TITLE
🐛 Double slash in the URL opens the site but breaks things

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.Website#1683]
Hi team, 

If I go to https://www.ssw.com.au// (2 slashes at the end) the website opens, but the menu does't open and the rotating banners neither. Events don't show, offices section also won't work. I believe it pretty much disables anything with javascripts

- [x] 1. Please investigate and fix

<img width="1392" alt="Screenshot 2023-11-08 at 9 06 59 AM" src="https://github.com/SSWConsulting/SSW.Website/assets/12601228/e6563d51-f2c4-48b4-8132-be19599b13e4">

**Comment by andrewwaltosssw** [comment]
Re-checked this. Navigating to https://www.ssw.com.au// now re-directs to https://www.ssw.com.au (no double slashes) and elements on the website seem to be working fine.
