### ISSUE TITLE
🐛 SEO checklist is mentioned twice

### ISSUE THREAD

**Issue by sethdaily** [SSWConsulting/SSW.Website#1718]
@bradystroud @GordonBeeming @camillars 
As per my conversation with Camilla, the SEO checklist is mentioned in the New Webpage issue template, so it doesn't need to be in the Pull Request template.
Plus, just the SEO checklist is not enough - people need to do the full issue template.

**Expected behavior**
Every new page should be started through the [New Webpage](https://github.com/SSWConsulting/SSW.Website/issues/new?assignees=&labels=&projects=&template=new_webpage.yml&title=%F0%9F%93%84+%7B%7B+TITLE+%7D%7D+) template

![image](https://github.com/SSWConsulting/SSW.Website/assets/130118701/2eead3bc-19a1-4f66-8483-dcedefe2864e)
**Figure: ❌ Bad example - Brady thought he did the right process, but he didn't**

**Comment by GordonBeeming** [comment]
@bradystroud please update the repo pr template so that it by default will ask for the right information for a pr 😊

**Comment by sethdaily** [comment]
@GordonBeeming 

    > please update the repo pr template so that it by default will ask for the right information for a pr 😊
check PR https://github.com/SSWConsulting/SSW.Website/pull/1716
