### ISSUE TITLE
📄 Update ALM Azure DevOps consulting service to ALM Tooling 

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.Website#1736]
cc @wicksipedia @camillars @sethdailyssw 

as per @GordonBeeming and @pierssinclairssw request

### Hi team 

URL: https://www.ssw.com.au/consulting/alm-azure-devops

- [x] 1. Please review my PR: https://github.com/SSWConsulting/SSW.Website/pull/1737
       I am especially concerned about the canonical URL that I changed (did I do it right?)
       
**Note:** The rest of the PR changes are valid and needed

- [x] 2. Update URL (in case my PR didn't already)

**From:**
> https://www.ssw.com.au/consulting/alm-azure-devops
      
**To:**
> https://www.ssw.com.au/consulting/alm-tooling

- [x] 3. Redirect the old URL

**Comment by tiagov8** [comment]
Hey @Harry-Ross 

1. Please check ☑️ the tasks in this Issue before closing. It's basically missing the 3rd task... redirect is not working

<img width="1147" alt="Screenshot 2023-11-29 at 9 22 42 AM" src="https://github.com/SSWConsulting/SSW.Website/assets/12601228/ac411caa-2630-4baa-8310-8207e4bd9c55">

**Comment by Harry-Ross** [comment]
My bad, GitHub automatically closes the issue when a PR is merged. 

I created a Pull Request for the redirect a couple of days ago as a part of working on this issue. Now as its been merged (https://github.com/SSWConsulting/SSW.FrontDoor/pull/119) the redirect is now active.
