### ISSUE TITLE
💸 Main Menu - Events - Move "Hack Days" to be under "User Groups"

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.Website#1749]
cc @jaydenalchin @amankumarrr @adamcogan @camillars @jeoffreyfischer 

- [x] 1. Please improve the Events & Training menu look and feel by moving "Hack Days" to be under "User Groups"

<img width="1429" alt="Screenshot 2023-11-23 at 1 45 58 PM" src="https://github.com/SSWConsulting/SSW.Website/assets/12601228/114d0873-20ba-41dc-addd-fba8642cda1f">

**Comment by tiagov8** [comment]
Hi team, 

as per my conversation with @camillars 

We are also considering adding a label "FREE" next to User Groups and Hack Days.

We understand that in the tech community, these terms makes it implicit that they are free events, but maybe this could be helpful for juniors and others.

- [ ] 2. Please discuss with the Product Owner and include the labels if agreed

**Comment by amankumarrr** [comment]
@tiagov8 
The first task seems to be completed.


![Image](https://github.com/SSWConsulting/SSW.Website/assets/71385247/302d5da4-46d8-4994-9ba2-4afc75dbfe68)

**Figure: Hack Days menu under the User Groups**
