### ISSUE TITLE
💸 Less is more - CTA phone number and Chinafy section - Reduce words

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.Website#1750]
@jaydenalchin @2fernandez @UlyssesMaclaren 

Hey team, 

- [x] 1. Could we change from

> or call us on +61 2 9953 3000

to

> or call +61 2 9953 3000

<img width="556" alt="Screenshot 2023-11-23 at 1 55 05 PM" src="https://github.com/SSWConsulting/SSW.Website/assets/12601228/646ddd75-e707-4de5-b275-dfd0de25ac05">

**Comment by UlyssesMaclaren** [comment]
Agreed. Please action

**Comment by tiagov8** [comment]
Hey @UlyssesMaclaren 

Chinafy section on homepage - 

1. Can you approve this one too?

- [x] Change from

> China is a booming market and now is the time to take advantage of this growing user base. If you have a successful application that you would like to bring to the Chinese market, then working with [SSW can help](https://www.ssw.com.au/consulting/chinafy-app) streamline your entry into this market.

to

> Seize the opportunity to smoothly introduce your successful application in China's thriving market. See [how SSW can help](https://www.ssw.com.au/consulting/chinafy-app).

---

<img width="1305" alt="Screenshot 2023-11-24 at 2 38 35 PM" src="https://github.com/SSWConsulting/SSW.Website/assets/12601228/040d7dd2-eb36-4358-944d-9277e9db2dab">

**Comment by uly1** [comment]
@tiagov8 approved

**Comment by tiagov8** [comment]
All done
