### ISSUE TITLE
💄 UI - Mega Menu hover effect needs improvements

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.Website#1751]
@jaydenalchin @2fernandez @hveraus @bettybondoc 

Hi team, 

The hover effects on the main menu isn't ideal...

2 items (SSW Rules and SSW TV) don't even have a hover effect...

On the search 🔎 and flags it is especially weird (lacks of margin between them and other items)

- [x] 1. Please change the hover effect to make the text/icon in a different color instead of adding a grey background to items
       I suggest SSW red `#cc4141` 

- [x] 2. For Services and Products, where items have a little blurb, only the service/product name should change to red

~~**Note:** The exemption are the language flags... I don't think they need the hover effect at all~~

<img width="1241" alt="Screenshot 2023-11-23 at 1 58 53 PM" src="https://github.com/SSWConsulting/SSW.Website/assets/12601228/5c8f235e-8973-4614-9b4e-df53fb1573d8">

**Figure: Search icon hover is weird and lacks margins**

---

<img width="207" alt="Screenshot 2023-11-23 at 2 01 22 PM" src="https://github.com/SSWConsulting/SSW.Website/assets/12601228/0c40282b-585f-454c-b615-bae3ea4af395">

**Figure: Flag icon hover is weird and lacks margins**

---

<img width="658" alt="Screenshot 2023-11-23 at 2 01 18 PM" src="https://github.com/SSWConsulting/SSW.Website/assets/12601228/b4e3dde1-e914-4dd5-bd85-3bc632a23d5b">

**Figure: If you click 1 item (to open submenu), then hover the other next to it... it's weird and lacks margins**

**Comment by tiagov8** [comment]
Hey @Calinator444 

Should this be moved to https://github.com/SSWConsulting/SSW.MegaMenu/issues ?

- [ ] 1. Please move if agreed
- [ ] 2. Then action the Issue

Kind of related to https://github.com/SSWConsulting/SSW.MegaMenu/issues/93#issuecomment-2261819338

**Comment by jaydenalchin** [comment]
Totally agree with @tiagov8 - and those 2 menu items lacking hover styling is pretty bad! 

However, I don't agree the language flags should have no hover state. Instead of changing background color on-hover, I would recommend scaling the flag slightly on hover so it's clearly clickable i.e. https://v2.tailwindcss.com/docs/scale 

Alternatively, just open the language menu on-hover (consistent with [ssw.cn](https://ssw.cn/))

**Comment by Calinator444** [comment]
@tiagov8 dragged this into the current sprint

**Comment by Calinator444** [comment]
The last thing to do for this is bump the dependency for the latest release. 

However, there's a jest test failing whenever I attempt to install new dependencies.

https://github.com/SSWConsulting/SSW.Website/actions/runs/10555932692/job/29240458427

I've tried the following
- downgrading to the LTS version of node before installing dependencies
- bumping our Next JS version locally (We would need to switch to the Canary version of Next to fix this: https://github.com/babel/babel/issues/16754#issuecomment-2300013668
- Installing the dependencies using PNPM v9 (used by the Githubaction for the website)

**Comment by Calinator444** [comment]
I've got the branch for this building in staging. I had to make some changes to the test because our pipeline was installing using an earlier version of node, causing the tests to break when I installed using pnpm.

I've also updated the action for running the tests to use the LTS version of node.

![Image](https://github.com/user-attachments/assets/7572bd40-48e3-45f5-a46e-d576abb70c1d)

**Figure**:

**Comment by Calinator444** [comment]
@wicksipedia This is live on the main Website but the dependency still needs to be bumped on /People and /Rules

**Comment by Calinator444** [comment]
@wicksipedia This is live on the main Website but the dependency still needs to be bumped on /People and /Rules

**Comment by Calinator444** [comment]
I've merged this with main on Poeple and Brady has evaluated it in Staging. I'll push this to Prod on Poeple, then for rules. Rules will take longer because the deployment takes an hour.

**Comment by Calinator444** [comment]
Done - I've deployed the new megamenu on People and Rules as well as the main site


![Image](https://github.com/user-attachments/assets/4066565f-2290-417a-942c-82d2f23b8104)
**Figure**: **Updated megamenu on ssw people**
<br>

![Image](https://github.com/user-attachments/assets/ad633e81-1ba2-418f-84f0-a954f6b0a858)
**Figure**: **Updated megamenu on Rules**

<br>

![Image](https://github.com/user-attachments/assets/7572bd40-48e3-45f5-a46e-d576abb70c1d)

**Figure**: **Updated megamenu on website**
