### ISSUE TITLE
🚧 Code Auditor - Reduce Broken Links count #7

### ISSUE THREAD

**Issue by bradystroud** [SSWConsulting/SSW.Website#1756]
**Description**
On https://codeauditor.com/explore
Check the broken links count for ssw.com.au

**Task**
- [x] Work with @zacharykeeping and @tombui99 to weekly reduce the amount of broken links by 10% until it is close to 0.

**Screenshots**
![image](https://github.com/SSWConsulting/SSW.Website/assets/106663901/c9e3ccec-60fe-4382-9131-8b93e9959d4c)
Figure: Code Auditor explore page

**Comment by jeoffreyfischer** [comment]
As per my conversation with Tom B., we have sent two emails to investigate the high numbers of broken links.

Email: Code Auditor - Broken Links
Email: Code Auditor - Broken Links on SSW Website

Link to SSW Website spike: https://codeauditor.com/build/7ce816d9-1783-40a8-caf2-f17d5959b065
Link to SSW People spike: https://codeauditor.com/build/30282a7e-7622-4b58-953c-6a6d605b8409
Link to SSW Rules spike: https://codeauditor.com/build/d013945d-593c-4eae-c9d2-ab4af2399367
