### ISSUE TITLE
📄 Case Study - Event Cinema

### ISSUE THREAD

**Issue by amankumarrr** [SSWConsulting/SSW.Website#1781]
Migrate - URL: https://www.ssw.com.au/SSW/Consulting/Case-Study/EventCinemas.aspx

```[tasklist]
### Tasks
- [x] Migrate the content
- [x] Add redirects in Front Door
```

**Comment by jeoffreyfischer** [comment]
**Description**

The case study is now accessible on http://www.ssw.com.au/company/clients/event-cinemas

**Screenshots**

![image](https://github.com/SSWConsulting/SSW.Website/assets/106663901/c588bc34-5daa-4fec-8f5e-d235e01e6dd3)
**Figure**: Event Cinemas case study migrated page
