### ISSUE TITLE
📄 Case Study - Brisbane Catholic Education

### ISSUE THREAD

**Issue by amankumarrr** [SSWConsulting/SSW.Website#1783]
Migrate - URL: https://www.ssw.com.au/SSW/Consulting/Case-Study/BCE.aspx

```[tasklist]
### Tasks
- [x] Migrate the content
- [x] Add redirects in Front Door
```

**Comment by jeoffreyfischer** [comment]
The case study is now accessible on https://www.ssw.com.au/company/clients/bce

- [x] Include done video or screenshots

**Figure**: Migrated page
