### ISSUE TITLE
📄 Case Study - Ausgrid

### ISSUE THREAD

**Issue by amankumarrr** [SSWConsulting/SSW.Website#1785]
Migrate - URL: https://www.ssw.com.au/SSW/Consulting/Case-Study/Ausgrid.aspx

```[tasklist]
### Tasks
- [x] Migrate the content
- [x] Add redirects in Front Door
```

**Comment by jeoffreyfischer** [comment]
The case study is now accessible on https://www.ssw.com.au/company/clients/ausgrid

- [x] Include done video or screenshots

![image](https://github.com/SSWConsulting/SSW.Website/assets/106663901/221e3bc2-9374-4801-bc2c-2eaf3fb507cb)
**Figure**: Migrated page
