### ISSUE TITLE
📄Case Study - Estate Master

### ISSUE THREAD

**Issue by amankumarrr** [SSWConsulting/SSW.Website#1786]
Migrate - URL: https://www.ssw.com.au/SSW/Consulting/Case-Study/EstateMaster.aspx

```[tasklist]
### Tasks
- [x] Migrate the content
- [x] Add redirects in Front Door
```

**Comment by jeoffreyfischer** [comment]
The case study is now accessible on https://www.ssw.com.au/company/clients/estate-master

- [x] Include done video or screenshots

![image](https://github.com/SSWConsulting/SSW.Website/assets/106663901/a162071f-33c1-447b-b791-e3064e5bfdbc)
**Figure**: Migrated page
