### ISSUE TITLE
📄 Case Study - Microsoft Australia 

### ISSUE THREAD

**Issue by amankumarrr** [SSWConsulting/SSW.Website#1787]
Migrate - URL: https://www.ssw.com.au/SSW/Consulting/Case-Study/SharePoint-Office-Forum.aspx

```[tasklist]
### Tasks
- [x] Migrate the content
- [x] Add redirects in Front Door
```

**Comment by jeoffreyfischer** [comment]
The case study is now accessible on https://www.ssw.com.au/company/clients/microsoft-sharepoint-office-forum

- [x] Include done video or screenshots

![Image](https://github.com/SSWConsulting/SSW.Website/assets/106663901/5d0c490e-6153-482c-849e-057c8586ceac)
**Figure**: Migrated page
