### ISSUE TITLE
📄Case Study - Worley Parsons

### ISSUE THREAD

**Issue by amankumarrr** [SSWConsulting/SSW.Website#1789]
Migrate - URL: https://www.ssw.com.au/ssw/consulting/case-study/WorleyParsons.aspx

```[tasklist]
### Tasks
- [x] Migrate the content
- [x] Add redirects in Front Door
```

**Comment by jeoffreyfischer** [comment]
The case study is now accessible on https://www.ssw.com.au/company/clients/worley-parsons

- [x] Include done video or screenshots

![image](https://github.com/SSWConsulting/SSW.Website/assets/106663901/7b7ea14e-6515-4778-a936-2427e55843c9)
**Figure**: Worley Parsons Case Study page
