### ISSUE TITLE
📄 Case Study - eMove

### ISSUE THREAD

**Issue by amankumarrr** [SSWConsulting/SSW.Website#1790]
Migrate - URL: https://www.ssw.com.au/SSW/Consulting/Case-Study/eMove.aspx

```[tasklist]
### Tasks
- [x] Migrate the content
- [x] Add redirects in Front Door
```

**Comment by jeoffreyfischer** [comment]
As per my conversation with @tiagov8, the two images carousel can be replaced with two figures next to each other (or under each other to allow bigger images).

**Comment by jeoffreyfischer** [comment]
**Description**

The page has been migrated to http://www.ssw.com.au/company/clients/emove

**Screenshots**



![Image](https://github.com/SSWConsulting/SSW.Website/assets/106663901/de9247ef-f830-4c8e-9448-1d03917db319)
**Figure**: Emove case study migrated page
