### ISSUE TITLE
📄Case Study - Maximus Imprint

### ISSUE THREAD

**Issue by amankumarrr** [SSWConsulting/SSW.Website#1791]
Migrate - URL: https://prod.ssw.com.au/SSW/Consulting/Case-Study/Maximus.aspx

```[tasklist]
### Tasks
- [x] Migrate the content
- [x] Add redirects in Front Door
```

**Comment by jeoffreyfischer** [comment]
The URL is broken. The correct on is: https://ssw.com.au/SSW/Consulting/Case-Study/Maximus.aspx

**Comment by jeoffreyfischer** [comment]
The case study is now accessible on https://www.ssw.com.au/company/clients/maximus-imprint

- [x] Include done video or screenshots

![Image](https://github.com/SSWConsulting/SSW.Website/assets/106663901/7d4ed36c-07ba-4528-a146-24b2dfb4ca3d)
**Figure**: Migrated page
