### ISSUE TITLE
🐛 Event page - profile photo out of place

### ISSUE THREAD

**Issue by hveraus** [SSWConsulting/SSW.Website#1797]
**Describe the bug**
<img width="389" alt="Screenshot 2023-11-29 at 14 57 05" src="https://github.com/SSWConsulting/SSW.Website/assets/4745861/210cbf27-1e34-41c9-b83b-efa5f9773b63">
<img width="598" alt="Screenshot 2023-11-29 at 14 57 59" src="https://github.com/SSWConsulting/SSW.Website/assets/4745861/65e79613-c652-478d-8eaa-3efef6c4f84e">

**Comment by amankumarrr** [comment]
@hveraus 
this issue has been resolved and doesn't persist any more.

![Image](https://github.com/SSWConsulting/SSW.Website/assets/71385247/dba45ade-1666-45bf-8a20-44b87aa4b2f1)

**Figure: Presenter images looks fine on User Group page**
