### ISSUE TITLE
🐛 Buttons - text are not centered 

### ISSUE THREAD

**Issue by hveraus** [SSWConsulting/SSW.Website#1798]
**Describe the bug**

https://www.ssw.com.au/netug/canberra 

The button on join discussion card it not aligned. 
It might be a universal things. 

<img width="516" alt="Screenshot 2023-11-29 at 14 59 09" src="https://github.com/SSWConsulting/SSW.Website/assets/4745861/6d589bad-fda2-49ef-96b1-cca04a5a6dcb">

**Comment by amankumarrr** [comment]
this one is fixed with this PR - https://github.com/SSWConsulting/SSW.Website/pull/2096 therefore closing this issue
