### ISSUE TITLE
💄 Live page - Create component for Youtube playlist videos

### ISSUE THREAD

**Issue by jeoffreyfischer** [SSWConsulting/SSW.Website#1820]
**Describe the bug**
On https://www.ssw.com.au/live
The red coloured text in the title is created with the bold option in Tina.

**To Reproduce**
1. Go to https://www.ssw.com.au/live
2. Observe the group of videos showing in the "Recent Broadcast" section

**Expected behavior**
There should be a separate component to create this group of videos.

**Screenshots/Video**

![Issue001a](https://github.com/SSWConsulting/SSW.Website/assets/106663901/4904a358-929f-44f4-b1a4-1b05c6414dd6)
**Figure**: Group of videos coming from a YouTube playlist

**Comment by amankumarrr** [comment]
Closing this as it is already done with this issue - https://github.com/SSWConsulting/SSW.Website/issues/2007
