### ISSUE TITLE
📄 Add new AI Banner to the home page

### ISSUE THREAD

**Issue by hveraus** [SSWConsulting/SSW.Website#1854]
URL: https://www.ssw.com.au

As per request from Seth @sethdailyssw 

 1. Add a new banner (don't replace) in position #2

![Boost-Business-with-AI](https://github.com/SSWConsulting/SSW.Website/assets/4745861/9d493205-d88e-413e-ba63-1ad2ce43c3ef)

**Comment by andrewwaltosssw** [comment]
Completed in #2348 

![Image](https://github.com/SSWConsulting/SSW.Website/assets/87786621/7478d4f5-3170-4c43-b03b-019baf12a503)
Figure: Homepage showing AI banner
