### ISSUE TITLE
💄 .NET UG - Broken Images

### ISSUE THREAD

**Issue by Harry-Ross** [SSWConsulting/SSW.Website#1870]
cc @bradystroud @PennyWalker 

As per @camillars's email, the presenter + organiser profile images on the .NET UG pages are cut off. 

![image](https://github.com/SSWConsulting/SSW.Website/assets/20507092/f89820cf-0a42-4671-8a18-1a4c5efdc14f)
**Figure: the cut off presenter image, despite the image uploaded having no crop**

```[tasklist]
### Tasks
- [x] Investigate and fix
```

**Comment by amankumarrr** [comment]
@camillars @PennyWalker @hveraus 
Done - changes are live now.
<img width="806" alt="image" src="https://github.com/SSWConsulting/SSW.Website/assets/71385247/82d88f6f-8769-4b93-8acb-abf35e27380e">
**Figure: Presenters and organizers on netug page**
