### ISSUE TITLE
Clean up some of the many branches in this project

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.Website#1950]
See https://github.com/SSWConsulting/SSW.Website/branches/active

I assume most of these are forgotten branches

**Comment by Harry-Ross** [comment]
**Stale Before:**
![Image](https://github.com/SSWConsulting/SSW.Website/assets/20507092/a997faf6-e4bf-441c-b9bc-0a3d48004dca)

**Stale After:**
![Image](https://github.com/SSWConsulting/SSW.Website/assets/20507092/08651545-75b2-4afe-ae67-ddb823f07a7a)

**Active Before:**
![Image](https://github.com/SSWConsulting/SSW.Website/assets/20507092/938e60a7-3905-406b-ba77-914e2cd6b73c)
![Image](https://github.com/SSWConsulting/SSW.Website/assets/20507092/fea50a65-ef27-4e39-a167-ce107bf5f1cb)

**Active After:**
![Image](https://github.com/SSWConsulting/SSW.Website/assets/20507092/dba46ef9-08df-49de-a651-ecc76f40e4c6)

**All branches:**
![Image](https://github.com/SSWConsulting/SSW.Website/assets/20507092/c508e0dd-53d3-4ea8-ba2e-8c67f10b39ca)
