### ISSUE TITLE
🐛 Fix broken image on Intune page

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.Website#1966]
cc @bradystroud @johnxu16 @Harry-Ross 

Team,

https://www.ssw.com.au/consulting/intune

- [x] 1. Please fix broken image

Cheers,

<img width="894" alt="Screenshot 2023-12-26 at 3 25 23 PM" src="https://github.com/SSWConsulting/SSW.Website/assets/12601228/b36f9a24-610f-4364-9048-07b538ffb24f">

**Comment by Harry-Ross** [comment]
![image](https://github.com/SSWConsulting/SSW.Website/assets/20507092/b108fb9f-52d5-43cd-a5bd-ca886f88d793)
**Figure: fixed image on https://www.ssw.com.au/consulting/intune**
