### ISSUE TITLE
🐛 TinaCMS - allow button editing on User Group pages

### ISSUE THREAD

**Issue by sethdaily** [SSWConsulting/SSW.Website#2017]
cc @camillars @Harry-Ross 
(checked by Aman)

Hi Aman,
https://www.ssw.com.au/netug/melbourne
https://www.ssw.com.au/netug/brisbane
https://www.ssw.com.au/netug/canberra
https://www.ssw.com.au/netug/sydney (this is the only correct one)

**Is your feature request related to a problem? Please describe.**
The 'Register for free' buttons have a hardcode link to the wrong page.

**Describe the solution you'd like**
Make this button editable in TinaCMS

![image](https://github.com/SSWConsulting/SSW.Website/assets/130118701/92428292-9046-4032-ae43-2e899658be1e)
Figure: This button takes me to the wrong link, and I can't change it

**Comment by amankumarrr** [comment]
@sethdailyssw @camillars 

Done 

**Screenshots:** 

### We are going to use `Register URL` for both header and action section button. 

<img width="217" alt="image" src="https://github.com/SSWConsulting/SSW.Website/assets/71385247/a13db128-baf4-44bb-aa27-7bf39145f2fc">

**Figure: Register URL field in Tina**

### Title and Button text can be updated in Tina now 
<img width="228" alt="image" src="https://github.com/SSWConsulting/SSW.Website/assets/71385247/0dcb0d11-53ed-4f7e-871a-9cbc4e975766">

**Figure: Meetup button and title fields in Tina**
