### ISSUE TITLE
Should .NET 8 be in AI category?

### ISSUE THREAD

**Issue by UlyssesMaclaren** [SSWConsulting/SSW.Website#2018]
![Image](https://github.com/SSWConsulting/SSW.Website/assets/45545178/1fe51210-f4e4-4477-8cfe-c8e3bfbfc08e)

Figure: https://www.ssw.com.au/consulting?tag=AI-Development

**Comment by wicksipedia** [comment]
I'd say yes

![CleanShot 2024-01-30 at 16 53 39](https://github.com/SSWConsulting/SSW.Website/assets/600044/ac6b3822-385a-47b9-b271-69e1045cdebe)
Figure: https://dotnet.microsoft.com/en-us/

This issue doesn't look ready yet, should have at least 1 actionable task

**Comment by wicksipedia** [comment]
closing as stale
