### ISSUE TITLE
💄 UX - Not Enough Events Showing 

### ISSUE THREAD

**Issue by Harry-Ross** [SSWConsulting/SSW.Website#2145]
cc @camillars 

As per Camilla's email, the 15 events shown on https://www.ssw.com.au/events isn't enough. 

```[tasklist]
### Tasks
- [x] Increase the number of events displayed to 20
```

**Comment by amankumarrr** [comment]
Done 
<img width="1055" alt="image" src="https://github.com/SSWConsulting/SSW.Website/assets/71385247/14ab7d31-4534-4072-9291-7037dae89241">
**Figure: Events pages on production**
