### ISSUE TITLE
📄 Migrate "Domain for Sale" page

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.Website#2146]
### 1. People in the loop:

cc @adamcogan @kikibianc @AshAnil @chrisschultzssw 

 

### 2. Page template to copy:

N/A

### 3. CRM Record (only for consulting service pages):

N/A

### 4. URI:

https://www.ssw.com.au/ssw/domains-for-sale.aspx

### 5. Page Title:

Domain for sale

### 6. Meta description:

Hey @camillars 

- [ ] 1. Do you think we need this for this page?

### 7. Related URLs:

N/A

### 8. Content:

https://www.ssw.com.au/ssw/domains-for-sale.aspx

This page is the end point of many redirections I believe. Ideally we should have a list of them.

- [x] 1. Please create a document showing ALL domains that point to this page
- [ ] 2. Create a new page in the new environment
- [ ] 3. Redirect the old one

**Comment by chrisschultzssw** [comment]
Hey @tiagov8 

  > 1. Please create a document showing ALL domains that point to this page

We have a list of domains with a column for redirects here:
https://sswcom.sharepoint.com/sites/SSWSysAdmins/SitePages/Domains.aspx

I have just gone through it and updated quite a few of the domains, so it should be correct.

**Comment by tiagov8** [comment]
Hi @chrisschultzssw 

Please see the related email I just sent: **Domains and redirects - Improvements**

Some suggestions to improve this document.

BTW - I marked the 1st task as done

**Comment by chrisschultzssw** [comment]
Whoever picks this up... I wonder if it's worthwhile adding the ability to display the original domain name on the page?

We can add a query string to our existing redirects (see example image below). 
It would still need generic text that loads if there's no query string in the URL.

![image](https://github.com/SSWConsulting/SSW.Website/assets/94873295/9556b9ff-af64-4ae8-a98d-a2195bf4c3fa)

**Comment by chrisschultzssw** [comment]
Whoever picks this up... 

Is it worthwhile showing the original domain on the page?
We can add a query string on most of our existing redirects (see image below) - would that work?

There would still need to be generic text shown if there is no query string provided.

![image](https://github.com/SSWConsulting/SSW.Website/assets/94873295/3d673698-83fc-48aa-966b-0c17dd7f3acd)

**Comment by wicksipedia** [comment]
Closing as done in #2381 and #2445
