### ISSUE TITLE
🐛 Broken Banner Links

### ISSUE THREAD

**Issue by 2fernandez** [SSWConsulting/SSW.Website#2163]
(Checked by @amankumarrr)

**Describe the bug**
When I go to https://www.ssw.com.au, I see two banners that are broken. 

- Meet us at NDC (https://www.ssw.com.au/%20https:/ndcsydney.com)
- Lesson from 42 years of coding (https://www.ssw.com.au/https:/www.ssw.com.au/netug/brisbane)

- [x] Can you please fix these links?

**Expected behavior**
I expect these banners to go to their relevant pages.

![Screenshot 2024-02-19 at 3 36 23 pm](https://github.com/SSWConsulting/SSW.Website/assets/27670973/0c0a6f80-4734-480b-952d-6dc3ecfe709a)
**Figure "Website Banner - NDC Image broken link"**

**Comment by amankumarrr** [comment]
@2fernandez 

Done - The issue has been resolved, and it was identified as a human error. To prevent such incidents in the future, I've included additional information in TinaCMS. 

<img width="538" alt="image" src="https://github.com/SSWConsulting/SSW.Website/assets/71385247/f9531506-21d7-42a4-9900-0a75b42eeefc">

**Figure: Tina fields with the additional description**
