### ISSUE TITLE
📄 Update Products Page

### ISSUE THREAD

**Issue by bettybondoc** [SSWConsulting/SSW.Website#2169]
URL: https://ssw.com.au/products

- [x] 1. Change copy at the top
**From:**
Used by thousands of customers around the world
**To:**
Explore the future of enterprise development with our scalable, cutting-edge products
- [x] 2. Add EagleEye and place at the top right (where TimePro is)
- [x] 3. Remove Link Auditor from the page

**Screenshots**
![image](https://github.com/SSWConsulting/SSW.Website/assets/33026270/b016a5a3-668d-438b-9762-a4c52636a84c)
**Figure: Updates on the Products Page**

**Additional context**
As per @danielmackay's request to add EagleEye to the Products page and my Teams call with @adamcogan to hide LinkAuditor and update the intro copy. Updated copy written by GPT and updated/checked by @camillars

Relates to [Task 90607](https://dev.azure.com/ssw/SSW.Design/_workitems/edit/90607): SSW Website | Update Products Index Page

**Comment by bettybondoc** [comment]
As per my conversation with @amankumarrr, I have finished tasks #2 and #3 but could not finish #1 because the subtitle field is missing from TinaCMS. I will merge the changes for items 2 and 3 and reopen/reassign this issue to him to finish #1.

**Comment by amankumarrr** [comment]
Hi @bettybondoc 

This has been fixed and live now. 
<img width="946" alt="image" src="https://github.com/SSWConsulting/SSW.Website/assets/71385247/840dac63-3032-4178-b81d-182ab2a8108d">

**FIgure: Product page with new title**
