### ISSUE TITLE
🕵️ Investigate - Azure App Insight failed requests #2

### ISSUE THREAD

**Issue by jeoffreyfischer** [SSWConsulting/SSW.Website#2173]
**Description**  
[SSW.Website - App Insights report](https://portal.azure.com/#view/AppInsightsExtension/UsageNotebookBlade/ComponentId/%2Fsubscriptions%2Fb8b18dcf-d83b-47e2-9886-00c2e983629e%2FresourceGroups%2Fssw.com.au%2Fproviders%2FMicrosoft.Insights%2Fcomponents%2FappInsight-sswwebsite-9eb3/ConfigurationId/%2Fsubscriptions%2Fb8b18dcf-d83b-47e2-9886-00c2e983629e%2Fresourcegroups%2Fssw.com.au%2Fproviders%2Fmicrosoft.insights%2Fworkbooks%2F0be4e8a1-c1e9-4043-b8c1-167bb8d73085/Type/workbook/WorkbookTemplateName/Failed%20Requests%20-%20With%20less%20noise)
As per my conversation with @wicksipedia, several spikes have been found on app Insight over the last 2 weeks. We need to investigate what caused them.

**Proposed solution**  
- [x] Investigate the origin of the spikes.
- [ ] Fix them.

**Screenshot**
![2024-02-22_16-07-30](https://github.com/SSWConsulting/SSW.Website/assets/106663901/b994cbd3-6e0b-4293-8c9c-4346c357037d)
**Figure: Several spikes were recently found on App Insights**

**Comment by jeoffreyfischer** [comment]
The two spikes in the failed request were investigated:

For **Spike 1**, the main requests came from:
- /gists/cache
- .local
- .production
- .remote

For **Spike 2**, the main requests came from:
- /_next/image

![2024-02-22_16-03-50](https://github.com/SSWConsulting/SSW.Website/assets/106663901/b06f9271-be1e-46f9-98b7-e033e03ab353)
**Figure: Spike 1**

![2024-02-22_16-05-45](https://github.com/SSWConsulting/SSW.Website/assets/106663901/ee2925f1-afeb-425b-8bb0-3fe698dda23f)
**Figure 2: Spike 2**

**Comment by jeoffreyfischer** [comment]
@wicksipedia Can you please have a look at the previous comment and tell me which of the listed paths should be filtered out in "Failed Requests - with less noise"

**Comment by wicksipedia** [comment]
It doesn’t look like there’s anything worth filtering out… It looks like random background noise

the only one that may require a redirect is the extreme email request but that page is being archived soon

**Comment by jeoffreyfischer** [comment]
Thanks Matt, in this case I will take no further action and close this issue.
