### ISSUE TITLE
💸 Make buttons consistent

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.Website#2175]
cc @bettybondoc @jaydenalchin 

**Description**  

Buttons are inconsistent in terms of border radius

<img width="1024" alt="Screenshot 2024-02-22 at 10 39 38 AM" src="https://github.com/SSWConsulting/SSW.Website/assets/12601228/4aa7ec94-2f1b-4475-b1c3-7470f43dcf56">

**Proposed solution**  

Make all buttons on the website to be `border-radius:.25rem;` (as per the "Book a FREE..." button) - Prefered by designers

- [x] 1. Update the big CONTACT US button border-radius

**Comment by tiagov8** [comment]
PS. This may be better in the Menu repo... if so, please move the Issue

**Comment by tiagov8** [comment]
Hi team, 

If you open the megamenu, the other "Book now" button also needs fixes:

- [x] 1. Make border-radius .25rem;
- [x] 2. Also fix the border-radius for the Featured dark boxes
- [x] 3. Make the phone icon exacly the same as "CONTACT US"
- [x] 4. Make the words ALL UPPERCASE

<img width="1611" alt="Screenshot 2024-02-22 at 2 29 32 PM" src="https://github.com/SSWConsulting/SSW.Website/assets/12601228/e43bd77b-076b-4af7-b8f6-1f1e2b74f7c4">

**Comment by andrewwaltosssw** [comment]
Done - Buttons and cards have been updated as per items in [comment](https://github.com/SSWConsulting/SSW.Website/issues/2175#issuecomment-1960436046)


![Image](https://github.com/SSWConsulting/SSW.Website/assets/87786621/c91bb317-986a-4b5d-9231-2414ec53ae49)
**Figure: Menu on prod site after changes**

**Comment by tiagov8** [comment]
Hey @bettybondoc 

Make sure the new "web standard" page is consistent with this (buttons border redius)
