### ISSUE TITLE
SpendOps - Clean up old images in ACR

### ISSUE THREAD

**Issue by wicksipedia** [SSWConsulting/SSW.Website#2210]
As per conversation with @leahy268 - we're exceeding our ACR usage, which is costing $

We need to create some automation to help manage the images in the repository.

![Image](https://github.com/SSWConsulting/SSW.Website/assets/600044/8ca63709-63d5-43bc-92cb-ffbfa0764fbb)

```[tasklist]
### Tasks
- [x] PR Cleanup - delete docker image used for the PR
- [x] Weekly Cleanup - delete any docker images not tagged as pr/prod/staging
```

**Comment by amankumarrr** [comment]
@wicksipedia @jeoffreyfischer @Harry-Ross @andrewwaltosssw 
Done 

- Removed around **4.5k** to **9** docker images
- Created a new pipeline named `Weekly ACR images cleanup`, which is scheduled to run on every Monday to clean up untagged and tagged docker images that are not required anymore.
- Reduced space from **995GB** to **1.5GB** 


<img width="390" alt="image" src="https://github.com/SSWConsulting/SSW.Website/assets/71385247/c98aa82b-ab45-46ef-955b-2cb9ac998732">

**Figure: Current occupied storage**

<img width="807" alt="image" src="https://github.com/SSWConsulting/SSW.Website/assets/71385247/8ed64c8e-a933-4589-a63f-d81b80eeab48">

**Figure: Remaining docker images in our ACR**
