### ISSUE TITLE
💸 What to do with https://www.ssw.com.au/ssw/hosting/ ?

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.Website#2233]
cc @bradystroud @william-liebenberg @BrookJeynes 

**Description**  

Hi team, 

We have this ASPX page live https://www.ssw.com.au/ssw/hosting/

**Proposed solution**  

Should we  

A. Move it as a new page to SSW.Website V3 

  OR

B. Just redirect to https://ssw.com.au/consulting/azure ?

**Comment by andrewwaltosssw** [comment]
Option B implemented based on this https://github.com/SSWConsulting/SSW.Website/issues/2339#issuecomment-2014049964

Fixed by: https://github.com/SSWConsulting/SSW.FrontDoor/pull/176

cc @amankumarrr
