### ISSUE TITLE
Events - Show SSW chapel for the city of the event 

### ISSUE THREAD

**Issue by amankumarrr** [SSWConsulting/SSW.Website#2254]
URL: https://www.ssw.com.au/events

@camillars 

Currently, we rely on the URL field from SharePoint to determine whether to display SSW's chapel. If the URL contains "ssw.com.au," we show the chapel; otherwise, we display the link to the event with the city. Ideally, there should be a dedicated field in SharePoint to determine the content to be shown.

```[tasklist]
### Tasks
- [ ] Add a field to show/hide the SSW Chappel in Sharepoint for the event
- [ ] Update the current logic in code
```

**Screenshots/Video**
![image](https://github.com/SSWConsulting/SSW.Website/assets/71385247/89b864cc-b4b6-442f-a1f8-22fbf8c81aff)

**Figure: Event with location link**

<img width="468" alt="image" src="https://github.com/SSWConsulting/SSW.Website/assets/71385247/1e7d8314-f95f-4e77-b03e-c874f4f53d07">

**Figure: Code to check the URL field**

**Comment by Calinator444** [comment]
@wicksipedia 

Done - I added a field on sharepoint that indicates whether or not something was hosted at ssw

![Image](https://github.com/SSWConsulting/SSW.Website/assets/65635198/9e347238-2b1e-432d-952d-bf457e0a285e)
