### ISSUE TITLE
📄Migration | Logo | SophieHub page 

### ISSUE THREAD

**Issue by amankumarrr** [SSWConsulting/SSW.Website#2268]
URL: https://ssw.com.au/ssw/logo/SophieHub/

- [x] Migrate the page  
- [x] Add FrontDoor redirects

**Comment by andrewwaltosssw** [comment]
Blocked - waiting on updated logo files to SharePoint drive. Emailed Ken S to action this

**Comment by andrewwaltosssw** [comment]
Update on image files: Joseph is taking care of this. Task tracked on https://dev.azure.com/ssw/SSW.Design/_workitems/edit/91795

**Comment by andrewwaltosssw** [comment]
Page migrated:
![image](https://github.com/SSWConsulting/SSW.Website/assets/87786621/8e37fb68-d117-4059-b4fa-a3aa3b93bfea)
**Figure: SophieHub logo page on new website https://www.ssw.com.au/logo/sophiehub**
