### ISSUE TITLE
📄Migration | Logo | CodeAuditor page

### ISSUE THREAD

**Issue by amankumarrr** [SSWConsulting/SSW.Website#2270]
URL: https://ssw.com.au/ssw/logo/CodeAuditor/

- [x] Migrate the page  
- [x] Add FrontDoor redirects

**Comment by andrewwaltosssw** [comment]
Blocked - waiting on logos to be added for this product. Have asked Ken and Joseph to help

**Comment by andrewwaltosssw** [comment]
Update on image files: Joseph is taking care of this. Task tracked on https://dev.azure.com/ssw/SSW.Design/_workitems/edit/91795

**Comment by andrewwaltosssw** [comment]
As per conversation with @jeoffreyfischer whilst waiting on the images to come from the designers, we will be migrating pages without SVGs for now and add them in later. PBI to track addition of SVGs #2315

Design work being tracked on https://dev.azure.com/ssw/SSW.Design/_workitems/edit/91795

cc: @amankumarrr @Harry-Ross @wicksipedia

**Comment by andrewwaltosssw** [comment]
Page migrated:
![Image](https://github.com/SSWConsulting/SSW.Website/assets/87786621/b74911a7-e037-449f-97b1-c96a7e667453)
**Figure: CodeAuditor logo on new website https://www.ssw.com.au/logo/codeauditor**
