### ISSUE TITLE
📄Migration | Logo | SmashingBarrier page 

### ISSUE THREAD

**Issue by amankumarrr** [SSWConsulting/SSW.Website#2271]
URL: https://ssw.com.au/ssw/logo/SmashingBarrier/

- [x] Migrate the page  
- [x] Add FrontDoor redirects

**Comment by andrewwaltosssw** [comment]
Page migrated
![Image](https://github.com/SSWConsulting/SSW.Website/assets/87786621/784bc643-02d5-4645-8bf1-861c32b37194)
**Figure: Migrated page on prod website https://www.ssw.com.au/logo/smashingbarrier**
