### ISSUE TITLE
📄Migration | Logo | Dory page 

### ISSUE THREAD

**Issue by amankumarrr** [SSWConsulting/SSW.Website#2273]
URL: https://ssw.com.au/ssw/logo/Dory/

- [x] Migrate the page  
- [x] Add FrontDoor redirects

**Comment by andrewwaltosssw** [comment]
Page migrated
![Image](https://github.com/SSWConsulting/SSW.Website/assets/87786621/d6816a6d-0f74-4101-a46c-e81827094719)
**Figure: New Dory logo page https://www.ssw.com.au/logo/dory**
