### ISSUE TITLE
📄Migration | Logo | Rewards page 

### ISSUE THREAD

**Issue by amankumarrr** [SSWConsulting/SSW.Website#2275]
URL: https://ssw.com.au/ssw/logo/SSWRewards/

- [x] Migrate the page  
- [x] Add FrontDoor redirects

**Comment by andrewwaltosssw** [comment]
Page migrated:
![Image](https://github.com/SSWConsulting/SSW.Website/assets/87786621/03f68765-28b6-48d5-8050-ac49e3f6e683)
**Figure: SSW Rewards logo page on new website https://www.ssw.com.au/logo/ssw-rewards**
