### ISSUE TITLE
📄Migration | Logo | UG page

### ISSUE THREAD

**Issue by jeoffreyfischer** [SSWConsulting/SSW.Website#2277]
URL: https://ssw.com.au/ssw/logo/NETUG/

- [x] Migrate the page  
- [x] Add FrontDoor redirects

**Comment by andrewwaltosssw** [comment]
Page migrated to https://www.ssw.com.au/logo/netug
![Image](https://github.com/SSWConsulting/SSW.Website/assets/87786621/eb6614d2-adff-40ca-bc5c-c43d0ebc4d8f)
**Figure: New page for .NET UG logo**
