### ISSUE TITLE
📄Migration | Logo | FBC page

### ISSUE THREAD

**Issue by jeoffreyfischer** [SSWConsulting/SSW.Website#2278]
URL: https://ssw.com.au/ssw/logo/FireBootCamp/

- [x] Migrate the page  
- [x] Add FrontDoor redirects

**Comment by amankumarrr** [comment]
done 
<img width="891" alt="image" src="https://github.com/SSWConsulting/SSW.Website/assets/71385247/2e2da2b0-a186-41a6-9b92-a0af395e1437">
