### ISSUE TITLE
📄Migration | Logo | Angular Hackday page

### ISSUE THREAD

**Issue by jeoffreyfischer** [SSWConsulting/SSW.Website#2279]
URL: https://ssw.com.au/ssw/logo/AngularHackDay/

- [x] Migrate the page  
- [x] Add FrontDoor redirects

**Comment by amankumarrr** [comment]
Done 
<img width="804" alt="image" src="https://github.com/SSWConsulting/SSW.Website/assets/71385247/cff18159-304a-46b1-bfa9-4759b8e2a68f">

Figure: Logo - New Angular Hackday page
