### ISSUE TITLE
📄Migration | Logo | AI Hackday page

### ISSUE THREAD

**Issue by jeoffreyfischer** [SSWConsulting/SSW.Website#2280]
URL: https://ssw.com.au/ssw/logo/AIHackDay/

- [x] Migrate the page  
- [x] Add FrontDoor redirects

**Comment by amankumarrr** [comment]
done 
<img width="1046" alt="image" src="https://github.com/SSWConsulting/SSW.Website/assets/71385247/aa8a84ec-c753-4310-bc3e-fe15fd181306">
