### ISSUE TITLE
📄Migration | Logo | MAUI Hackday page

### ISSUE THREAD

**Issue by jeoffreyfischer** [SSWConsulting/SSW.Website#2281]
URL: https://ssw.com.au/ssw/logo/MAUIHackDay/

- [x] Migrate the page  
- [x] Add FrontDoor redirects

**Comment by andrewwaltosssw** [comment]
![Image](https://github.com/SSWConsulting/SSW.Website/assets/87786621/1bd213a3-b7f3-4add-af43-2842ff6539a2)
**Figure: New page for MAUI Hackday logo https://www.ssw.com.au/logo/maui-hackday**
