### ISSUE TITLE
📄Migration | Logo | SSW Typography page - Part 1/2 - Template

### ISSUE THREAD

**Issue by jeoffreyfischer** [SSWConsulting/SSW.Website#2282]
URL: https://ssw.com.au/ssw/company/Web-Reference.aspx

- [x] Take a screenshot of the page - this will help to keep track of the migrated content
- [x] Create the page - not the whole content yet - under the route /company/typography
- [x] Migrate the content that looks important - use your own judgment and/or ask another Team member
- [x] Once completed, copy paste the screenshot below into a new comment and edit it using red boxes to show what content has been migrated - this will help keeping track of the progress

Note: The remaining content will be investigated in the following PBI: https://github.com/SSWConsulting/SSW.Website/issues/2341

**Screenshot**
![typography page](https://github.com/SSWConsulting/SSW.Website/assets/106663901/e73c56d8-e7dd-445e-90d2-a94bfd5b459e)
**Figure: Screenshot of the original Typography page**

**Comment by andrewwaltosssw** [comment]
Page migrated. Comparison below
![Typography-diff](https://github.com/SSWConsulting/SSW.Website/assets/87786621/74efd00a-f84b-409d-bd30-f7dacb6651e4)
**Figure: Comparison between the old (left) and the new (right) Typography page. The red boxes highlight content that has not been migrated yet. See PBI #2341 for final version of the page**

cc @bettybondoc @tiagov8 @jaydenalchin

**Comment by andrewwaltosssw** [comment]
https://github.com/SSWConsulting/SSW.Website/issues/2341#issuecomment-2048639537 for final design check
