### ISSUE TITLE
🐛Newsletters - Email validation 

### ISSUE THREAD

**Issue by amankumarrr** [SSWConsulting/SSW.Website#2287]
**Describe the bug**
Recently, there was an attempt to probe into our Power Automate flow, highlighting a lack of proper email validation measures in place.

**To Reproduce**
1. Go to https://www.ssw.com.au/newsletters
2. Fill all fields and email field without a valid email 
3. Submit the form

**Expected behavior**
It should not allow user to submit any invalid input

**Screenshots/Video**
![e8b37ab5-5854-473b-a4f0-d7731cd28151](https://github.com/SSWConsulting/SSW.Website/assets/71385247/c23d5aef-6823-43d4-b36e-fb0fc68afaf8)

**Figure: PowerAutomate flow's payload for newsletter's subscription**

**Comment by amankumarrr** [comment]
@wicksipedia @johnxu16 @andrewwaltosssw 

We will not need to add this validation in our code if we transition to using JotForm with this issue #2288.

- [x] Test email validation on JotForm's email field

**Comment by Calinator444** [comment]
@wicksipedia can we remove this item from the backlog if it's no longer relevant please? It's a little confusing having it there.

**Comment by andrewwaltosssw** [comment]
Form was converted to JotForm which uses built-in email validation. Fixed in issue: #2288 and fixed by: https://github.com/SSWConsulting/SSW.Website/pull/2451

See donegif at https://github.com/SSWConsulting/SSW.Website/issues/2288#issuecomment-2058197205 for working validation
