### ISSUE TITLE
💄 SSW Awards Page - Improve tile design

### ISSUE THREAD

**Issue by bettybondoc** [SSWConsulting/SSW.Website#2296]
cc @uly1 @adamcogan @tiagov8 @amankumarrr @jaydenalchin @camillars 

Based on:
Email Subject - **What’s the worst page? - About Us**
PBI - **[Product Backlog Item 88682](https://dev.azure.com/ssw/SSW.Design/_workitems/edit/88682): 💄 SSW.Website - Improve /Awards page design**

**Is your feature request related to a problem? Please describe.**
The items under the SSW Awards page look like they're floating because of the different sizes/length of the logos and text.

**Describe the solution you'd like**
Implement a new tile design to this page to manage the irregular-sized images.

- [x] 1. Implement new design - see [Figma Design](https://www.figma.com/file/AyCKcrEVIWl5AdGSXa24dQ/SSW-Website---Awards-Page-(BBondoc)?type=design&node-id=0%3A1&mode=dev) (images can be exported from Figma but ask @bettybondoc for images if needed)
- [x] 2. Get a 'test pass' from @bettybondoc and @camillars 

**Additional context**
![image](https://github.com/SSWConsulting/SSW.Website/assets/33026270/3cf72c81-b150-4da1-8a70-60dcdec0c25b)
**Figure: SSW Awards - Current Live Design**

![image](https://github.com/SSWConsulting/SSW.Website/assets/33026270/7ce41adb-da31-40c7-a1e5-128c89a9bd92)
**Figure: SSW Awards - New Design (Figma Mockup)**

**Comment by amankumarrr** [comment]
Test passed by @bettybondoc and @camillars 

✅ Fixed layout on Testimonials page 
✅ Added spacing on live page 
✅ Fixed the imports path on company pages
✅ Added Azure footer banner with layout to fix the position

**Screenshot**:
![image](https://github.com/SSWConsulting/SSW.Website/assets/71385247/2b091033-785b-49fe-a946-12b7a5feb4b1)

**Figure: New Awards page**  

![image](https://github.com/SSWConsulting/SSW.Website/assets/71385247/cc6caff9-6f88-44c1-83b1-d44aaa289223)

**Figure: Fixed testimonials page layout from 2 testimonials to 3 testimonials a row**


![image](https://github.com/SSWConsulting/SSW.Website/assets/71385247/309926a7-78bb-4047-a3b2-012ea6ce440a)

**Figure: Fixed spacing between text and presenter on live page**
