### ISSUE TITLE
🐛 Captions not editing Correctly - Tina

### ISSUE THREAD

**Issue by Geordie88** [SSWConsulting/SSW.Website#2302]
**Describe the bug**
On the [Events cinema page](https://www.ssw.com.au/company/clients/event-cinemas) the captions are too far from the images. 

@amankumarrr and I attempted a solution in Tina, adding a custom image component and editing the "my" values in custom Class but this did not behave as expected. 

**To Reproduce**
1. Open Tina
2. Go to the [Events cinema page](https://www.ssw.com.au/company/clients/event-cinemas)
3. Create a custom image 
4. Add a caption 
5. Add my-0 to custom class

**Expected behavior**
Removing the extra space between the caption and the image. While the class helped it did not match the distance used other locations (rules, SL ect)

**Screenshots/Video**
If applicable, add screenshots/video to help explain your problem.
Remember to mark the area in the application thats impacted.
![image](https://github.com/SSWConsulting/SSW.Website/assets/97079655/46186521-30b8-4a3c-b72e-1d77381996c6)
Figure: current page layout

![image](https://github.com/SSWConsulting/SSW.Website/assets/97079655/09466b6b-64b7-45ad-bfbd-dd1ff1a5cf60)
Figure: edited page layout in Tina

**Comment by andrewwaltosssw** [comment]
Done - reduced distance between caption and image for CustomImage components. Also added back ability to remove block margin for CustomImage component in Tina.
![Image](https://github.com/SSWConsulting/SSW.Website/assets/87786621/f7ea19c4-7f28-4913-a6dd-5dc1d7be7ea9)
**Figure: Gap between figure and image before (left) vs after (right)**
