### ISSUE TITLE
Logo - PNG download button should trigger a file save

### ISSUE THREAD

**Issue by andrewwaltosssw** [SSWConsulting/SSW.Website#2340]
**Describe the bug**
When clicking a download PNG button from any logo page (e.g. https://www.ssw.com.au/logo/timepro)

**To Reproduce**
1. Go to https://www.ssw.com.au/logo/timepro 
2. Click PNG download button
3. Note that the PNG opens in the new tab (navigates to link to the asset)

**Expected behavior**
File download is triggered. As per behaviour when clicking the SVG download button

**Screenshots/Video**
![Image](https://github.com/SSWConsulting/SSW.Website/assets/87786621/31068f06-1ab5-4463-8963-9becbc437449)
**Figure: screenshot of the PNG download button**

**Comment by andrewwaltosssw** [comment]
Use package https://www.npmjs.com/package/file-saver to get this functionality

**Comment by andrewwaltosssw** [comment]
As per Teams conversation with @wicksipedia I will use native attributes for anchor tag instead of an external package to achieve the expected behaviour.

**Comment by andrewwaltosssw** [comment]
Native download functionality not working (<a src="" download />) on PR environments and higher due to the asset coming from a different origin. File download behaviour is blocked in this scenario: https://developer.chrome.com/blog/chrome-65-deprecations#block_cross-origin_a_download  
  
file-saver defaults to using native functionality, but we can opt to fetch the asset and convert it to a blob use file-saver to force the download via browser.
  
This is working well in local where the file is hosted on the local server but we get blocked in higher environments where the file is hosted on assets.tina.io causing a CORS error trying to fetch.

I have added https://assets.tina.io to the PR slot CORS config in Azure but still getting CORS blocked. Tina Cloud config does have the PR slot URL in the "Site URLs" array but there is no specific mention that the setting has an effect on CORS.

Parking work for now as the issue will need more investigation to find a solution.

**Comment by andrewwaltosssw** [comment]
As per my conversation with @wicksipedia current download behaviour is fine. Due to default browser handling for certain file types, we will leave behaviour as:
- PNG files: open in new tab
- PDF files: open in new tab
- SVG files: file download via browser

**Comment by Calinator444** [comment]
@andrewwaltosssw 

CC: @wicksipedia 

Hi Andrew, Is this bug still relevant? If not can we close it please?
