### ISSUE TITLE
📄Migration | Logo | SSW Typography page - Part 2/2 - Content

### ISSUE THREAD

**Issue by jeoffreyfischer** [SSWConsulting/SSW.Website#2341]
URL: https://ssw.com.au/ssw/company/Web-Reference.aspx

Once https://github.com/SSWConsulting/SSW.Website/issues/2282 is completed:

- [x] Talk to a Designer about the content of the page - what needs to be kept, edited and/or deleted.
- [x] Implement the changes
- [x] Add a FrontDoor redirect

**Comment by andrewwaltosssw** [comment]
Page migrated:
![image](https://github.com/SSWConsulting/SSW.Website/assets/87786621/e148a5f0-80b1-4bf1-948c-81187cb40d75)
**Figure: Typography page on production site**

**Comment by andrewwaltosssw** [comment]
Final design checked by @jaydenalchin as per https://github.com/SSWConsulting/SSW.Website/pull/2390#issuecomment-2024466611

This page will be replaced in the future with re-designed content. Design PBI for this re-design: https://dev.azure.com/ssw/SSW.Design/_workitems/edit/89158
