### ISSUE TITLE
🐛 UG live feed PIP stacking issue 

### ISSUE THREAD

**Issue by andrewwaltosssw** [SSWConsulting/SSW.Website#2355]
**Describe the bug**
Elements of the menu are rendered on top of the PIP for the UG live feed YouTube video

**To Reproduce**
1. Wait for UG to go live/Trigger this locally
2. Visit SSW.Website home page
3. Scroll down until right side of menu is on top of the YouTube PIP (may need to adjust screen width)

**Expected behaviour**
Video is on top of menu items

**Screenshots/Video**
![](https://github.com/SSWConsulting/SSW.Website/assets/87786621/2727f38c-d938-4884-8286-204add378b09)
**Figure: Menu elements on top of PIP**

**Comment by Calinator444** [comment]
@wicksipedia 

@BrookJeynes has approved my pull request and the changes have been deployed. I've only been able to test this locally as the event only triggers during a live stream.

<img width="983" alt="image" src="https://github.com/SSWConsulting/SSW.Website/assets/65635198/3e1fa10f-09f2-4c20-a62e-27f4ce86f762">

**Figure**: **Live stream window overlaying navbar links**
