### ISSUE TITLE
🐛 Production build - Sharp is missing 

### ISSUE THREAD

**Issue by amankumarrr** [SSWConsulting/SSW.Website#2366]
**Describe the bug**

Azure log stream generates error stating "'sharp' is required to be installed in standalone mode for the image optimization to function correctly".

Expected behavior: 
This will fix the issue : https://nextjs.org/docs/messages/sharp-missing-in-production

**Screenshots/Video**
<img width="838" alt="image" src="https://github.com/SSWConsulting/SSW.Website/assets/71385247/cd4f4238-424c-4b2e-843f-3bc12ec85b29">
**Figure: Logs from Azure Container logstream**

**Comment by Calinator444** [comment]
I was unable to diagnose this as I don't have access to Azure. I did some investigating with @andrewwaltosssw and he found that the sharp dependency is already installed. So if the issue still persists it's likely an environment variable issue.
