### ISSUE TITLE
💸 Website v1 - Redirect links | Fix up GA

### ISSUE THREAD

**Issue by wicksipedia** [SSWConsulting/SSW.Website#2372]
As per conversation with @SSWConsulting/ssw-website-maintainers and @adamcogan 

There are 2953 links in `/ssw/redirect`

For the ones that do not result in 404s:

1. Update the GA code to use GA4 and current key
1. In 2 weeks - #2374
   zz the redirect pages that received 0 hits
1. Migrate the remaining redirect links to Website v3
   (implementation will depend on how many are left)

```[tasklist]
### Tasks
- [x] Update the GA code to use GA4 and current key
```

**Comment by Harry-Ross** [comment]
![Image](https://github.com/SSWConsulting/SSW.Website/assets/20507092/b6112162-b2d3-434d-a45c-0a4b24338c24)
**Figure: Files in redirect without the new GA tag**

```
find . -type f -name "*.htm" -exec grep -L 'Google tag (gtag.js)' {} \;
```

**Comment by Harry-Ross** [comment]
This has been implemented on all redirect pages with the new GA tag. 

**Changeset:** https://dev.azure.com/ssw2/SSW.Website/_versionControl/changeset/80040/**

![Image](https://github.com/SSWConsulting/SSW.Website/assets/20507092/d88f9879-6f3c-4009-b339-4896e057b8e2)
**Figure: An example of the new format of all of the redirect files**
