### ISSUE TITLE
📄 Migration | Printable Resources page

### ISSUE THREAD

**Issue by jeoffreyfischer** [SSWConsulting/SSW.Website#2375]
Migrate the following page to the new SSW website: https://www.ssw.com.au/ssw/Company/Resources.aspx

Note: The broken images can be taken from the existing rules linked on the page.

- [x] Migrate the page
- [x] Create FrontDoor Redirect

**Comment by amankumarrr** [comment]
done 
![image](https://github.com/SSWConsulting/SSW.Website/assets/71385247/9d3675a7-aa2c-41c2-ab6c-e656fbde585e)
