### ISSUE TITLE
📄 Migration | Advertising page

### ISSUE THREAD

**Issue by jeoffreyfischer** [SSWConsulting/SSW.Website#2376]
Migrate the following page to the new SSW website: https://www.ssw.com.au/ssw/Advertising/Default.aspx
Note: 

- [x] Migrate the page
- [x] Update links on the page
- [x] Create FrontDoor Redirect

**Comment by andrewwaltosssw** [comment]
Page migrated using content as agreed upon with Uly - [comment](https://github.com/SSWConsulting/SSW.Website/pull/2404#issuecomment-2033354481)

![Image](https://github.com/SSWConsulting/SSW.Website/assets/87786621/077975dd-d217-404a-9086-b6ab31b72db2)
**Figure: New Advertising page**
