### ISSUE TITLE
📄 Migration | Crash Plan Pro page

### ISSUE THREAD

**Issue by jeoffreyfischer** [SSWConsulting/SSW.Website#2377]
Migrate the following page to the new SSW website: https://www.ssw.com.au/ssw/Consulting/Crash-Plan-Pro.aspx

- [x] Check with Sys Admin if they want this page migrated

~~If Yes~~: 
- [ ] ~~Migrate the page~~
- [ ] ~~Create FrontDoor Redirect~~

If No:
- [x] Ask them where it should be redirected to
- [x] Create FrontDoor Redirect

**Comment by andrewwaltosssw** [comment]
As per Teams conversation with @kikibianc, the page will not be migrated and the URL should redirect to https://www.ssw.com.au/consulting/backup-recovery

**Comment by andrewwaltosssw** [comment]
Old page (not migrated):
![image](https://github.com/SSWConsulting/SSW.Website/assets/87786621/352fbef3-50b6-4731-992f-6cb1ee56cc8e)
**Figure: Old CrashPlan Pro page previously at https://www.ssw.com.au/ssw/Consulting/Crash-Plan-Pro.aspx**

Now redirecting to:
![image](https://github.com/SSWConsulting/SSW.Website/assets/87786621/1d940825-d8f5-40f6-9a43-6b1a28cb88de)
**Figure: Backup and recovery page https://www.ssw.com.au/consulting/backup-recovery**

**Comment by andrewwaltosssw** [comment]
@wicksipedia do we need to migrate this page to `/history` ?
