### ISSUE TITLE
📄 Migration | Maps Development page

### ISSUE THREAD

**Issue by jeoffreyfischer** [SSWConsulting/SSW.Website#2378]
Migrate the following page to the new SSW website: https://www.ssw.com.au/ssw/Consulting/Maps-Development.aspx

- [x] Check with @UlyssesMaclaren whether he want this page migrated

If yes: 
~- [ ] Migrate the page~
~- [ ] Create FrontDoor Redirect~

If No:
- [x] Ask him what actions he proposes
- [x] Confirm with @wicksipedia 
- [ ] Action the changes

Reference:
![image](https://github.com/SSWConsulting/SSW.Website/assets/87786621/a872ac2c-9d73-4fcc-8b97-6a5bf6d4a934)
**Figure: Old Maps dev page for reference**

**Comment by andrewwaltosssw** [comment]
As per Teams conversation with @UlyssesMaclaren, we do not need to migrate this page. Redirect should be created to https://www.ssw.com.au/consulting

@wicksipedia please confirm you're ok with the above

**Comment by wicksipedia** [comment]
Yes, Uly is one of the owners of the consulting page content

**Comment by andrewwaltosssw** [comment]
Old Maps Development page at https://www.ssw.com.au/ssw/Consulting/Maps-Development.aspx now redirecting to https://www.ssw.com.au/consulting
![image](https://github.com/SSWConsulting/SSW.Website/assets/87786621/1e148168-31fd-4787-9bbc-b81a941c05c1)
**Figure: Destination page from above redirection**
