### ISSUE TITLE
📄 Migration | Courses page

### ISSUE THREAD

**Issue by jeoffreyfischer** [SSWConsulting/SSW.Website#2379]
Create a redirect for following page: https://www.ssw.com.au/ssw/Courses.aspx
Link to redirect it to: https://ssw.com.au/events/customized-courses

- [ ] Create FrontDoor Redirect

**Comment by andrewwaltosssw** [comment]
Page not migrated:
![image](https://github.com/SSWConsulting/SSW.Website/assets/87786621/f157e7b1-21a2-423e-bd93-37ec7b247fa6)
**Figure: Old courses page for reference**

Redirect added to https://www.ssw.com.au/events/customized-courses
![image](https://github.com/SSWConsulting/SSW.Website/assets/87786621/7c636536-f6e4-4946-a93c-0de37376d154)
**Figure: Page being redirected to customized courses**
