### ISSUE TITLE
📄 Migration | Domains for Sale page

### ISSUE THREAD

**Issue by jeoffreyfischer** [SSWConsulting/SSW.Website#2381]
Migrate the following page to the new SSW website: https://www.ssw.com.au/ssw/Domains-For-Sale.aspx

- [x] Talk to a Sys Admin to propose a solution to handle multiple domains being redirected to that page e.g. githubhackday.com
- [x] Migrate the page
- [x] Create FrontDoor Redirect

**Comment by wicksipedia** [comment]
As per conversation with @chrisschultzssw - VentraIP can do domain redirects for us https://ventraip.com.au/support-centre/adding-domain-redirects-using-vipcontrol/

Redirect will have the domain as part of the querystring - it will be good to show that on the page

**Comment by andrewwaltosssw** [comment]
As per conversation with @chrisschultzssw query param will be using `domain` for the key. 

2 redirects we can test are: 
- www.devopsindex.org redirects to https://ssw.com.au/domains-for-sale?domain=devopsindex.org (migrated page)
- www.devopsindex.com redirects to https://ssw.com.au/ssw/domains-for-sale.aspx?domain=devopsindex.org (old page)
![image](https://github.com/SSWConsulting/SSW.Website/assets/87786621/c2426d8d-6abe-4115-a04c-632f9fe8c314)
**Figure: Redirects in VentraIP dashboard**


FrontDoor redirect passes query string to target url

**Comment by andrewwaltosssw** [comment]
![image](https://github.com/SSWConsulting/SSW.Website/assets/87786621/1c68a7de-60be-4e71-a41e-bff09dd8938d)
**Figure: Page migrated and now displaying domain from redirection**

Page migrated as per design team mockups https://www.figma.com/file/0tPh6fgi4SSlE3Gx9knJhX/SSW.Website-Mockups-(BBondoc)?type=design&node-id=15-2&mode=design&t=t5ESznWo71R2fPdk-0 

Copy as per design team + approval by @camillars 

cc: @bettybondoc @jaydenalchin
