### ISSUE TITLE
📄 Migration | HackDay page

### ISSUE THREAD

**Issue by jeoffreyfischer** [SSWConsulting/SSW.Website#2382]
Migrate the following page to the new SSW website: https://www.ssw.com.au/ssw/HackDay/Default.aspx
Note: 

- [x] Migrate the page
- [ ] Make it an index page and create child pages to Angular Hackday, etc.
- [x] Create FrontDoor Redirect

**Comment by amankumarrr** [comment]
Done - 

✅ Fixed white spacing and added `title` and `subTitle` for all `/pages`
✅ Added Link to the megamenu
✅ Ordered the page blocks alphabetically to search them easier 

- [x] Include done video or screenshots:

![Discarded-content](https://github.com/SSWConsulting/SSW.Website/assets/71385247/1e87a699-f35e-4023-8e18-573f7232e693)

**Figure: Discarded content** 

![image](https://github.com/SSWConsulting/SSW.Website/assets/71385247/cc82abd4-c281-4946-af34-e9a42ccb0212)
**Figure: New Hack Day page** 

![Megamenu-hackday](https://github.com/SSWConsulting/SSW.Website/assets/71385247/6ce326e3-e761-49f2-b3d2-bb2fc8f4bf0d)

**Figure: Mega menu with All Hack days link**
