### ISSUE TITLE
✨ Power Automate - Email Notification For Manual Created Lead

### ISSUE THREAD

**Issue by zl24622** [SSWConsulting/SSW.Website#2409]
Email Subject: RE: VR and Development assistance
From: @UlyssesMaclaren 
CC: @zl24622 @Levijj22 @PennyWalker @miichaelsmedley @samsmithssw 

> Hi Lu,
Is there a way to not have this automation happen if we create the lead manually in CRM

As per my conversation with @amankumarrr 
1. Add an environment variable to store the service user's id 
2. Send email notification only if the RunAsSystemUserId = service user id in the Power Automate flow

- [x] zz old newsletter signup flow from CRM once changes on https://github.com/SSWConsulting/SSW.Website/issues/2288 are deployed

**Comment by amankumarrr** [comment]
Done - I've created a variable named `CRM_TIMEPRO_SYNC_USER_ID` to check if the lead is created via the websites using the CRMTIMEPROSYNC user ID in CRM. If it is, then the email notification will be sent out; otherwise, manual creation will not trigger any email notification.
