### ISSUE TITLE
📄 Update text around "FREE INITIAL BOOKING" button

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.Website#2411]
cc @jaydenalchin @adamcogan 

As per my conversation with @bettybondoc and approval from @UlyssesMaclaren

**URL:** All Consulting pages (e.g. https://ssw.com.au/consulting/web-applications)

- [ ] 1. Change from:
 
  **Jump on a call with one of our Account Managers to discuss how we can help you.
  [BUTTON]
  or call us on +61 2 9953 3000**
 
  to
 
  **Connect with our Account Managers to discuss how we can help.
  [BUTTON]
  or call +61 2 9953 3000**

### Screenshots

Places where the text should be changed:

<img width="994" alt="Screenshot 2024-04-03 at 10 49 01 AM" src="https://github.com/SSWConsulting/SSW.Website/assets/12601228/ba08cacd-c000-49c1-8e62-af69171411f3">

<img width="966" alt="Screenshot 2024-04-03 at 10 48 54 AM" src="https://github.com/SSWConsulting/SSW.Website/assets/12601228/37737763-3e01-424b-879e-e49e78d3b7e5">

**Additional context**

This change was initiatiated when looking to approve the UI on this other Issue: https://github.com/SSWConsulting/SSW.Website/issues/2410

**Comment by tiagov8** [comment]
cc @Calinator444 @jeoffreyfischer 

Hi @johnxu16 

The text **after** button is updated but I still see the old text **before** the button...

- [x] 1. Please make sure it's updated
- [x] 2. Include a screenshot from the live page when you close the Issue again ;)



![Image](https://github.com/SSWConsulting/SSW.Website/assets/12601228/ae487a3e-b854-4114-adc0-3a2c65798722)

**Comment by johnxu16** [comment]
![Image](https://github.com/SSWConsulting/SSW.Website/assets/113034339/ce254ce5-0f93-488a-984e-6a04547d48d1)
