### ISSUE TITLE
🐛 UI Employement- floating text

### ISSUE THREAD

**Issue by amankumarrr** [SSWConsulting/SSW.Website#2414]
URL: https://www.ssw.com.au/employment

@camillars 

**Describe the bug**
Text on the page looks unaligned.

**Expected behavior**
It should be either left or centered aligned. 

- [x] Investigate and fix 

**Screenshots/Video**
![image](https://github.com/SSWConsulting/SSW.Website/assets/71385247/685f33a7-30ac-49fa-b998-03d5955cdfb9)

**Figure: Bullets points on the employment page**

**Comment by camillars** [comment]
@amankumarrr 

please make it centered :)

**Comment by amankumarrr** [comment]
@camillars done 
![image](https://github.com/SSWConsulting/SSW.Website/assets/71385247/40ba8102-924c-44f1-9582-4f7347a74f9f)
