### ISSUE TITLE
📄 Migration | Past Logos Page Redirect

### ISSUE THREAD

**Issue by jeoffreyfischer** [SSWConsulting/SSW.Website#2441]
The following pages contain old logos that have been migrated to the Past Logos page: https://www.ssw.com.au/logo/past
However, they have not been redirected yet.

List of pages:
https://www.ssw.com.au/ssw/Logo/XamarinHackDay/Default.aspx
https://www.ssw.com.au/ssw/Logo/TimePRO-old/Default.aspx
https://www.ssw.com.au/ssw/Logo/SSW-TV-2009/Default.aspx
https://www.ssw.com.au/ssw/Logo/SSW-1994/Default.aspx
https://www.ssw.com.au/ssw/Logo/SQLDeploy/Default.aspx
https://www.ssw.com.au/ssw/Logo/SSRS/Default.aspx
https://www.ssw.com.au/ssw/Logo/HealthCheck/Default.aspx
https://www.ssw.com.au/ssw/Logo/DataOnion/Default.aspx

- [x] Create FrontDoor Redirect for all these pages to the Past Logos page

**Comment by andrewwaltosssw** [comment]
All pages listed in issue description now redirecting to https://www.ssw.com.au/logo/past
