### ISSUE TITLE
💸 Use platform colors in Tailwind config for Typography reference

### ISSUE THREAD

**Issue by andrewwaltosssw** [SSWConsulting/SSW.Website#2444]
In https://github.com/SSWConsulting/SSW.Website/issues/2341 a platform color palette was added to the [Typography](https://www.ssw.com.au/company/typography) page.

![Image](https://github.com/SSWConsulting/SSW.Website/assets/87786621/e95fdd02-c6c0-4fa7-bc54-f1fcc33ba42f)
**Figure: The color palette**

These should be dynamic based on the colors definition in the Tailwind config

**Comment by johnxu16** [comment]
>These should be dynamic based on the colors definition in the Tailwind config

Does it need to be dynamic(configurable to my recognition) to the developers and designers or only developers?

**Comment by wicksipedia** [comment]
The configuration is the tailwind config - any colors there should be rendered out
