### ISSUE TITLE
💸 SSW.Website - Events thumbnails images

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.Website#2449]
cc @camillars @sethdaily @PennyWalker @wicksipedia @adamcogan @Calinator444 

### Hi team, 

On https://ssw.com.au/events we have a thumbnail for each event.

Those thumbs are (or most of them are) stored in the [old ASPX website solution](https://ssw2.visualstudio.com/SSW.Website)... ❌

E.g.:
- [ssw.com.au/ssw/NETUG/Images/thumbs/thumb-SydneyUG.jpg](https://ssw.com.au/_next/image?url=https%3A%2F%2Fwww.ssw.com.au%2Fssw%2FNETUG%2FImages%2Fthumbs%2Fthumb-SydneyUG.jpg&w=256&q=75)
- [ssw.com.au/ssw/EventsCalendar/Images/AHD-thumb.jpg](https://ssw.com.au/_next/image?url=https%3A%2F%2Fwww.ssw.com.au%2Fssw%2FEventsCalendar%2FImages%2FAHD-thumb.jpg&w=256&q=75)

**Note:** To add the thumb to events, we use SharePoint, among with the rest of the information of the event. I don't think we intend to change that.

We don't want to rely on that ASPX solution any longer so we need to figure out another place to store those images.

- [x] 1. Please define the new location for those images
- [x] 2. Migrate all thumbs to the new location
       I assume everything from:
       - trunk/SSW.Website.WebUI/EventsCalendar/Images
       and
       - trunk/SSW.Website.WebUI/NETUG/Images/thumbs
- [x] 3. Tell the marketing team to update the image paths in SharePoint (at least for all future events + the 20 most recent past events)

Related to https://github.com/SSWConsulting/SSW.Website/issues/2617

**Comment by andrewwaltosssw** [comment]
> Please define the new location for those images

We are already using `images/thumbs/` , `images/Newsletters/` and `images/events/` dirs to store event thumbnail images. As discussed with @bradystroud we are going to reuse these locations until we migrate events to Tina when it makes sense to centralise all thumb assets

> Migrate all thumbs to the new location

Done. Moved referenced thumbs that were not present in v3 site

> Tell the marketing team to update the image paths in SharePoint (at least for all future events + the 20 most recent past events)

Done differently. I did this myself. Updated all references to event thumbs for all future events and previous 40 events - to April 2023 (which is the furthest that our website currently will display)
