### ISSUE TITLE
📄 New consulting page for TinaCMS

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.Website#2450]
### 1. People in the loop:

From @uly1 @UlyssesMaclaren 

### 2. Page template to copy:

https://www.ssw.com.au/consulting/mobile-application-development

### 3. CRM Record (only for consulting service pages):

https://ssw.crm6.dynamics.com/main.aspx?appid=05daa2a9-8768-446e-b9d3-580c8a6f9b8b&pagetype=entityrecord&etn=ssw_consultingservice&id=6487ac24-87f7-ee11-a1fe-00224812b9e4&lid=1712787040412

### 4. URI:

https://www.ssw.com.au/consulting/tinacms

### 5. Page Title:

Enterprise Development and Consulting for TinaCMS

### 6. Meta description:

Boost your website with TinaCMS consulting. Our experts provide personalized guidance for seamless content management integration.

### 7. Related URLs:

https://www.ssw.com.au/consulting/alm-tooling

### 8. Content:

**Want to build a TinaCMS website?**
Take advantage of the best fully open-source headless CMS for Git

**The benefits of TinaCMS**
TinaCMS revolutionizes collaboration between developers and content editors through its Git-based content management system, integrating content and code into a single source of truth. This setup enhances workflow efficiency, enabling direct content changes in the repository with robust version control and history tracking.

Enhancing the user experience, TinaCMS offers a real-time visual editing feature, allowing for intuitive content creation and management directly within the website or app interface. Customizable content blocks and a real-time preview function ensure high-quality content publication. Emphasizing user control and scalability, TinaCMS is open-source and optionally self-hosted, designed to maintain optimal performance and flexibility for projects of any size, making content as manageable as if it were in a database.

Video: https://www.youtube.com/watch?v=zRkeKSZjlyw

Tina is an open-source, Git-backed headless content management system (CMS) that empowers both developers and content creators to collaborate seamlessly on a single platform. Tina enables developers to craft a custom visual editing experience perfectly tailored to their website or application while supporting a broad range of content types such as Markdown, MDX, and JSON.

**Own Your Content**
Don't lock your content in a 3rd-party service. Tina writes to files in your repository (MDX, Markdown, JSON, etc)

**An API for your Content**
Easily fetch your file-based content using Tina's Data Layer

**Configure with Code**
Tina is code-first and fully typed. Define your CMS in the Tina config file in your repository

**Merge With Confidence**
Tina Cloud Enterprise customers can review, approve, and manage content on different branches

**Unbeatable UX**
Editing content in Markdown, MDX, and JSON files doesn't need to feel clunky. Tina supports a live preview that takes the UX to the next level

**Composable Blocks**
Create reusable components that you can edit with Tina. Let your team assemble pages like a site-builder.

Technologies:

GitHub 
Responsive sites

**Comment by wicksipedia** [comment]
Hey @uly1 @adamcogan @camillars @sethdaily 

Page is now live - https://www.ssw.com.au/consulting/tinacms


![Image](https://github.com/SSWConsulting/SSW.Website/assets/600044/c0595664-5ab8-4c5d-b463-2b7ba1b7f3e4)
**Figure: Listing under CMS**



![Image](https://github.com/SSWConsulting/SSW.Website/assets/600044/e793016d-fddb-4f78-8e4d-736ba1d8fcee)
**Figure: TinaCMS consulting page**
