### ISSUE TITLE
💸 Duplicated Employment Opportunity? SharePoint Developer

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.Website#2459]
cc @PennyWalker @adamcogan @JeanThirion 

### Hi team,

Looking at Employment opportunites, I've found:

- content/opportunities/Senior-SharePoint-Developer.mdx
- content/opportunities/Senior-SharePoint-and-Web-Developer.mdx

- [x] 1. Please consider removing one of them since they are too similar (get approval from Penny)

**Note:** Both are marked as "filled"

![Image](https://github.com/SSWConsulting/SSW.Website/assets/12601228/01237db6-af8d-404e-80d0-31255a1124f2)

**Comment by PennyWalker** [comment]
Hi @tiagov8 approved - my preference would be to remove Sharepoint Developer, I think we tend to hire people like Jean who can do both. :)

**Comment by wicksipedia** [comment]
closing as these roles are not shown on page



![Image](https://github.com/SSWConsulting/SSW.Website/assets/600044/42e2495d-78d0-4a25-bd75-d995150ea288)

**Comment by tiagov8** [comment]
Hey @wicksipedia 

They are not showing in the "Available" filter, but both are there as "Filled". This is still to be actioned so I am reopening issue

**Comment by tiagov8** [comment]
> Hey [@wicksipedia](https://github.com/wicksipedia)
> 
> They are not showing in the "Available" filter, but both are there as "Filled". This is still to be actioned so I am reopening issue

Done - https://github.com/SSWConsulting/SSW.Website/pull/2523
