### ISSUE TITLE
✨ Add TinaCMS to the Products menu and index page

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.Website#2479]
cc @UlyssesMaclaren @camillars 

Since we now have a new CMS…it was confirmed @adamcogan wants it in the menu from Tuesday May 14th...

- [x] 1. Add the new CMS **Main Menu | Products**
   and to **Products index page** (https://www.ssw.com.au/products) - links should go to the new CMS website
- [x] 2. Make these changes go live on the Tuesday just before /NEW

![Image](https://github.com/SSWConsulting/SSW.Website/assets/12601228/5dafe4d8-ed76-4069-af1e-acfe202accd7)

Related to https://github.com/SSWConsulting/SSW.Website/issues/2450

**Comment by andrewwaltosssw** [comment]
cc: @wicksipedia 
Done:

![Image](https://github.com/SSWConsulting/SSW.Website/assets/87786621/10fa99ed-c0fb-4c9c-bc1c-5bf89a8084c8)
**Figure: Tina is 1st in the Products | Web list**

![Image](https://github.com/SSWConsulting/SSW.Website/assets/87786621/6688567b-3639-4f7a-9744-3aed9bbf60cf)
**Figure: Tina is 1st in the products index list**
