### ISSUE TITLE
⚡Google Tag Manager - review tags being used

### ISSUE THREAD

**Issue by wicksipedia** [SSWConsulting/SSW.Website#248]
Liase with @camillars

GTM currently loads a lot of tags - do an audit and clean up where possible

Install MS Clairty at the same time #722

**Comment by amankumarrr** [comment]
@bradystroud 

We are using following tags with our GTM:

![Image](https://github.com/SSWConsulting/SSW.Website/assets/71385247/9d5968bc-ce17-4b9c-a430-ee6bfae88d22)

**Figure: list of tags with GTM** - https://tagmanager.google.com/?authuser=1#/container/accounts/362468/containers/407674/workspaces/1000037/tags

@camillars, we need a list of tags that are redundant, need to clean up to improve the performance of the website. 
@wicksipedia this #722 issue has been closed as the Microsoft Clarity is already used as a tag in GTM.

**Comment by camillars** [comment]
Hi @amankumarrr 

here's a preview list. Yellow means I am unsure (under investigation), green stays, and red can go.

![image](https://github.com/SSWConsulting/SSW.Website/assets/53064613/b1679c3b-ca57-42e9-bff3-72a5fdf20ffc)

**Comment by amankumarrr** [comment]
@bradystroud @wicksipedia 

Hi @camillars 

Here is the preview of tags after removing the mentioned ones above. Please let me know if we need some more cleanup.

<img width="947" alt="image" src="https://github.com/SSWConsulting/SSW.Website/assets/71385247/c193b703-aea1-45df-a9cd-17e5e5f4a8dc">

**Figure: GTM tags after a clean-up**

**Comment by wicksipedia** [comment]
Is AppInsights required? At minimum, it looks like it is misconfigured ATM

<img width="1436" alt="CleanShot 2023-06-27 at 10 34 32@2x" src="https://github.com/SSWConsulting/SSW.Website/assets/600044/d04fad7f-fce9-4675-93fc-d01f1cd47aab">

**Comment by wicksipedia** [comment]
should GTM be loaded on `lazyOnload` instead of `afterInteractive` (default)?
see: https://nextjs.org/docs/pages/api-reference/components/script#strategy

it looks like it is the biggest contributor to 3rd patry code impact
<img width="1317" alt="CleanShot 2023-06-27 at 10 37 20@2x" src="https://github.com/SSWConsulting/SSW.Website/assets/600044/f6b60e7b-ba38-40a4-bcec-37c0cea3fc30">

**Comment by amankumarrr** [comment]
@camillars we have a separate appInsight for the website, the one with GTM seems broken, do we need it with GTM?

**Comment by camillars** [comment]
> @camillars we have a separate appInsight for the website, the one with GTM seems broken, do we need it with GTM?

I don't use it, I don't know what it is used for or who added it.

**Comment by amankumarrr** [comment]
@camillars I removed AppInsight as it was broken after discussing it with @bradystroud. 

@wicksipedia I tried to load GTM scripts as LazyLoading strategy but I don't see the significance drop from the PageSpeed Insights. Should we implement this - https://github.com/SSWConsulting/SSW.Website/pull/875

Before LazyLoading:

<img width="491" alt="image" src="https://github.com/SSWConsulting/SSW.Website/assets/71385247/6318d8e8-2d1c-4ad2-8512-64bc19866a63">

**Figure: Page Speed Insight**

After LazyLoading:

<img width="489" alt="image" src="https://github.com/SSWConsulting/SSW.Website/assets/71385247/08378682-eeb3-42fd-8a8a-9e04bd8b95dd">

**Figure: Page Speed Insight after Lazyloading**

**Comment by amankumarrr** [comment]
@camillars @bradystroud 

@wicksipedia should we mark this as closed or is there anything else we need to do with this issue?

**Comment by amankumarrr** [comment]
@camillars @bradystroud 

As per my discussion with @wicksipedia, I'm closing this issue as we have cleaned up the unused and redundant tags, although our attempt to improve performance by implementing lazy loading for GTM did not yield the desired results. In light of this, I have created new issues #910 and #911 to conduct further investigations and explore potential solutions for improving performance.
