### ISSUE TITLE
💸 CMS page doesn't have links... Please add them!

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.Website#2483]
**Description**  

On https://www.ssw.com.au/consulting/cms we have mentions of different CMS in the cards "Related Technologies". 

But those are not clickable + they are very inconsistent from the other consulting pages cards...

![Image](https://github.com/SSWConsulting/SSW.Website/assets/12601228/fd020a54-472f-4b8a-9cd1-5d820569a819)

**Proposed solution**  

- [x] 1. Change the current inconsistent cards to be like the other pages (e.g. https://www.ssw.com.au/consulting/sharepoint) where you have 1 card per technology with their logos and "read more" links

- [x]  Add TinaCMS as the 1st card

--- 

Related issue: https://github.com/SSWConsulting/SSW.Website/issues/2481

**Comment by andrewwaltosssw** [comment]
cc: @wicksipedia @tiagov8 
Done - page update to include new CMS tech cards. Tina is #1 🦙 

![Image](https://github.com/SSWConsulting/SSW.Website/assets/87786621/293be233-91d3-48b4-bcd7-5c74d15d7f0b)
**Figure: New cards at bottom of CMS page**
