### ISSUE TITLE
✨ Analytics | Tracking newsletter signups

### ISSUE THREAD

**Issue by andrewwaltosssw** [SSWConsulting/SSW.Website#2489]
cc: @camillars @PennyWalker @wicksipedia 

There is currently no automated way to track users who sign up to the SSW newsletter.

Improve the current newsletter signup tracking.

- [x] Track newsletter signups in GA as a conversion. 
- [x] Investigate capturing the URL from submission on this event. JotForm has an article on this https://www.jotform.com/help/1076-how-to-track-online-form-submissions-using-google-analytics/

**Comment by wicksipedia** [comment]
This sounds like at least 2 PBIs. 
Tracking in GA seems straightforward as 1 pbi.

I’d get help/input from the CRM team for the rest of the tasks

**Comment by andrewwaltosssw** [comment]
> This sounds like at least 2 PBIs. Tracking in GA seems straightforward as 1 pbi.
> 
> I’d get help/input from the CRM team for the rest of the tasks

Done - I have split the second task set to a new PBI https://github.com/SSWConsulting/SSW.Website/issues/2497

**Comment by andrewwaltosssw** [comment]
May not be achievable due to form being embedded via iframe. Current testing shows that submissions are not being tracked in GA4 after setup as per JotForm docs.

JotForm does have their own analytics: https://www.jotform.com/form-analytics/

Still investigating this.

**Comment by andrewwaltosssw** [comment]
Working on a solution by sending a custom GA event using API during Power Automate Flow on user signup. Waiting on support from SysAdmins for permissions on using secret from Azure KV. Ticket raised: [#14019](https://pdi-ssw.zendesk.com/hc/en-us/requests/14019&theme=hc&locale=en-us&brand_id=3050568&auth_origin=3050568,false,true)

**Comment by andrewwaltosssw** [comment]
Still waiting on support from SysAdmins as per above comment

**Comment by andrewwaltosssw** [comment]
Changed existing PA Flow to include a call to Google Analytics endpoint sending an event if a new email was successfully added to CRM from the newsletter signup flow.
Capturing the URL from submission was not required.
![Image](https://github.com/SSWConsulting/SSW.Website/assets/87786621/bd9986da-9be5-4ef8-9cca-7ea795d3ed1b)
**Figure: The newsletter signup event registered in Google Analytics**
