### ISSUE TITLE
🚧 MegaMenu - Fix deprecated links

### ISSUE THREAD

**Issue by jeoffreyfischer** [SSWConsulting/SSW.Website#2515]
On the https://www.ssw.com.au/ MegaMenu, some links are directing to the old website. This is a problem as we are planning on turning off the These links can be found under: 
- Events & Training | Resources | Past Sessions
- Events & Training | Resources | Evaluation Survey
- Events & Training | Resources | Developer Links
- Products | Support | Report a bug

1. Action the following tasks:

- [x]  Past Session: redirect to https://www.ssw.com.au/events (with past events preselected)

- [x] Evaluation Survey: ~~TODO~~ confirm with Matt W if we can remove it- Replace with a link to past user groups https://www.youtube.com/playlist?list=PLpiOR7CBNvlpmhfwQeIVhbqZKxV-do0wY 

- [x] Developer Links: ~~TODO~~ confirm with Matt W if we can remove it- Yes, remove it
  
- [x] Report a bug link: replace with https://www.ssw.com.au/rules/report-bugs-and-suggestions/

**Screenshot**

![Image](https://github.com/SSWConsulting/SSW.Website/assets/106663901/324beda9-41cd-4196-a300-0689d0280ebc)
**Figure: MegaMenu | Events links that direct to the old website**

![Image](https://github.com/SSWConsulting/SSW.Website/assets/87786621/4962d016-7738-4513-8d4d-6a7bca594150)
**Figure: MegaMenu | Products links that direct to the old website**

**Comment by andrewwaltosssw** [comment]
Done.

- Past events link goes to events page with past events tab seleccted:
![Image](https://github.com/SSWConsulting/SSW.Website/assets/87786621/d3973ed8-85a3-43bc-95ae-115e42b745a6)
**Figure: Landing on past events page after clicking Past Sessions**

- Developer Links link removed
- Report a bug Link changed to https://www.ssw.com.au/rules/report-bugs-and-suggestions/
