### ISSUE TITLE
📄 New consulting page "Clean Architecture"

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.Website#2539]
### 1. People in the loop:

From @adamcogan and @Hona 
cc @sethdaily 

**Re: Website - Consulting services for CA & VSA**
https://github.com/orgs/SSWConsulting/projects/24/views/1?pane=issue&itemId=59118567

### 2. Page template to copy:

https://www.ssw.com.au/consulting/strategic-architecture

### 3. CRM Record (only for consulting service pages):

https://ssw.crm6.dynamics.com/main.aspx?appid=05daa2a9-8768-446e-b9d3-580c8a6f9b8b&pagetype=entityrecord&etn=ssw_consultingservice&id=07cd1d22-9b01-ef11-9f89-00224891e87b&lid=1713895146446

### 4. URI:

https://www.ssw.com.au/consulting/clean-architecture

### 5. Page Title:

Enterprise Consulting for Clean Architecture

### 6. Meta description:

Discover how Clean Architecture can enhance software scalability, maintainability, and flexibility for your development projects.

### 7. Related URLs:

https://www.ssw.com.au/consulting/web-applications
https://www.ssw.com.au/consulting/database-development
https://www.ssw.com.au/consulting/devops

And the new to be created https://www.ssw.com.au/consulting/vertical-slice-architecture (https://github.com/SSWConsulting/SSW.Website/issues/2540)

### 8. Content:

# Want to ensure your software is flexible and maintainable?

## Clean Architecture organizes software into layers with strict dependencies to improve flexibility and maintainability.

{{ CTA }}

The benefits of having a Clean Architecture

Video: https://www.youtube.com/watch?v=B9owh0BL7Y4

Clean Architecture is a strategic framework that revolutionizes software development by ensuring your applications are not only robust but also flexible and future-proof. This architecture style is distinguished by its emphasis on the separation of concerns, creating a system that is easier to manage and evolve over time.

**Enhanced Maintainability**   
Clean Architecture simplifies code changes and minimizes bugs through clear, layered responsibilities.

**Increased Flexibility**   
It allows easy adaptation to new technologies and business needs by decoupling system components.

**Improved Testability**   
Centralized business logic enables straightforward, reliable testing away from UI and database influences.

**Long-term Scalability**   
Clean Architecture supports scalable growth, managing increasing complexity without hindering development.

**Comment by tiagov8** [comment]
Created PR: https://github.com/SSWConsulting/SSW.Website/pull/2829

**Comment by Calinator444** [comment]
✅Done - Here's the live version of the page

https://www.ssw.com.au/consulting/clean-architecture
