### ISSUE TITLE
🐛 Zendesk - chat window doesn't reopen after navigation

### ISSUE THREAD

**Issue by wicksipedia** [SSWConsulting/SSW.Website#255]
Zendesk chat window does not reopen after refreshing page or opening a link in a new tab

Works as expected when clicking a link and navigating in same tab though

https://user-images.githubusercontent.com/600044/220796359-983026ab-504d-4819-be78-e6445ff5bf13.mp4

**Comment by johnxu16** [comment]
As per pr #989, the issue recurred.

**Comment by wicksipedia** [comment]
@johnxu77 i'd recommend opening a new ticket if it isn't working as expected - so it doesn't get confused with the original development
that way you can log details about the issue e.g. a video showing whats happening
