### ISSUE TITLE
🐛The march newsletter page points too a 404

### ISSUE THREAD

**Issue by Calinator444** [SSWConsulting/SSW.Website#2567]
**Describe the bug**
The link to the march newsletter on the Newsletters page points to a 404 on the live site

**To Reproduce**
1. Navigate to newsletters page
2. click on Past Newsletters | 2024 | March

**Expected behavior**
I should see the march newsletter for .Net 8 migrations

**Screenshots/Video**
If applicable, add screenshots/video to help explain your problem.
Remember to mark the area in the application thats impacted.

![Image](https://github.com/SSWConsulting/SSW.Website/assets/65635198/dea319d3-8192-4844-b130-379bd15f41f9)
**Figure**: **Broken link on newlsetter page**

![Image](https://github.com/SSWConsulting/SSW.Website/assets/65635198/3be869a6-f4cd-45ad-a38a-659cbab5f462)
**Figure**: **Route that should point to march newsletter**

**Comment by andrewwaltosssw** [comment]
Retested and can see that the link is working:

![Image](https://github.com/SSWConsulting/SSW.Website/assets/87786621/365a1792-033a-4c1a-b725-7985f6879fc8)
**Figure: Screen after clicking the link to March 2024 newsletter**
