### ISSUE TITLE
Website Version History page: does not show version history, has redundant references to TFS and has broken hyperlinks

### ISSUE THREAD

**Issue by leehawkinsssw** [SSWConsulting/SSW.Website#257]
Selecting the "HERE" link in the footer of https://www.ssw.com.au/ssw/ 

![image](https://user-images.githubusercontent.com/106290015/221081005-0b875a5e-eb83-4e45-888b-ac7f65a8f635.png)

opens the Website Version History page. This page has several issues:

1. There is an authorization error at the top of the page (perhaps explaining why no version history is actually shown on this page):

![image](https://user-images.githubusercontent.com/106290015/221081474-5441c0a3-a12d-475d-8748-7b66675a5705.png)

2. The "constant deployment" hyperlink is broken.
3. The anchor in the http://www.ssw.com.au/ssw/Standards/Rules/RulesToBetterSourceControlwithTFS.aspx#CheckInPolicy hyperlink doesn't exist on the page it redirects to.
4. Still refers to "Microsoft TFS" as the website's source control system.

**Comment by bradystroud** [comment]
Hey @leehawkinsssw 

All Done - These issues were solved in the new home page (https://ssw.com.au)
