### ISSUE TITLE
🐛 Home - 💄Banner is cutting off

### ISSUE THREAD

**Issue by amankumarrr** [SSWConsulting/SSW.Website#2588]
**Describe the bug**
Following the recent update, the height of the banner has been altered, causing the image to be cut off from the top. As per my conversation with @wicksipedia and @bettybondoc, we've decided that we need to either correct the height or revert the change responsible for this issue.

- [x] Fix the issue 

**Screenshots/Video**

![Image](https://github.com/SSWConsulting/SSW.Website/assets/71385247/18070449-0b0e-4fad-8cd9-a7632b8aee1e)

**Figure: Penny is being cut off in the banner**

**Comment by amankumarrr** [comment]
@bettybondoc @wicksipedia 

Reverted the changes made by this pr - https://github.com/SSWConsulting/SSW.Website/pull/2531, we can't use `fill` with `object-fit:cover` as it will crop the image and as a result, some objects in the image will be cut off. 

✅ Also added Turbo in config to improve the local development
✅ Reducing the icons size to reduce the image load 

![Image](https://github.com/SSWConsulting/SSW.Website/assets/71385247/2005bf8b-cfa8-4c0d-81c6-0d7c28a45296)

**Comment by bettybondoc** [comment]
[https://outlook-1.cdn.office.net/assets/reaction/heart.png]    Betty Bondoc [SSW] reacted to your message:




[cid:ssw-circle(1)_4c7259a6-23f6-49e5-b933-230ca304562e.png]

Betty Bondoc
SSW UI/UX Designer
Stalk: SSW People<https://www.ssw.com.au/people/Betty-Bondoc?utm_source=emailsignature>   |   Walk: SSW Sydney<https://www.ssw.com.au/ssw/Company/Offices/?utm_source=emailsignature>   |   Talk: +61 497 283 065<https://www.ssw.com.au/ssw/Company/ContactUs.aspx>
[cid:youtube-icon_b8b5cda9-a973-4973-8763-cf3d4922e060.png] <https://www.youtube.com/c/SSWTV>    [cid:linkedin-icon_b153ac9a-eb66-47d9-9c51-ad20b42b8a0a.png]  <https://www.linkedin.com/company/ssw/>    [cid:twitter-icon_16ddd2de-0a0c-4b56-9986-6c5968e517d2.png]  <https://twitter.com/SSW_TV>    [cid:teams-icon_552803c2-9c44-4267-b563-7fe1a7a0e589.png] ***@***.***>


        Level up your AI game at the SSW AI 2-day Workshop<https://www.ssw.com.au/events/ai-workshop?utm_source=emailsignature>

________________________________
