### ISSUE TITLE
📄 Redirect/Archive/Migrate BrowseXML.aspx

### ISSUE THREAD

**Issue by chrisschultzssw** [SSWConsulting/SSW.Website#2599]
cc: @bahjatalaadelssw @tiagov8 

URL: https://www.ssw.com.au/ssw/BrowseXML.aspx/Browse.aspx

As per my conversation with @amankumarrr yesterday, Bahjat found this page from a Google search (see his email below). 

1. Please decide what to do with this page (Redirect/Archive/Migrate/other?).

---

Email from Bahjat:

Hi SysAdmins,

As per my conversation with Kiki, a Google search of “SSW standards” resulted in this link
              https://www.ssw.com.au/ssw/BrowseXML.aspx/8Steps/8Steps/8Steps/Access2007/AccessReporter/Advertising/AgileTemplate/Angular/App_Readme/App_Start/App_Themes/blog/Bot/browse.aspx

![Image](https://github.com/SSWConsulting/SSW.Website/assets/94873295/f9871a2f-5817-482d-b893-616f59d0e4da)
Figure: Search results

![Image](https://github.com/SSWConsulting/SSW.Website/assets/94873295/0670c209-6c13-4efa-8e6e-9fb820dc4120)
Figure: XML site for SSW

**Comment by jeoffreyfischer** [comment]
As per my conversation with @wicksipedia, we will add this BrowseXML path in the Azure Failed Requests query so that it is ignored in the count.

**Comment by Calinator444** [comment]
I'll be adding these to the `Robots.txt` file for now. As these pages haven't been archived these will become valid 404's once the VM is switched off. We will probably need to add some redirects in place if any of the archive pages reference these files. I'd recommend searching app insights to figure out which pages are referencing browse.aspx.

**Comment by Calinator444** [comment]
@wicksipedia I've added the links to robots.txt. We haven't gotten any new requests from google for nearly 2 days but there links are still being crawled by bots.

![Image](https://github.com/user-attachments/assets/38debe6b-04ea-45e0-8690-c0cc38ae451d)

**Figure**: **App Insights results**

<br>

![Image](https://github.com/user-attachments/assets/eee01660-d551-4d9c-b567-659e8186b235)

**Figure**: **Parameters used in App Insights**
