### ISSUE TITLE
♻️ App Router migration - Add error boundary

### ISSUE THREAD

**Issue by amankumarrr** [SSWConsulting/SSW.Website#2600]
**Description:**

As per my conversation with @wicksipedia, we've decided to migrate the `/company` pages incrementally to App Routing, following our recent migration of the `/products` route. This approach allows us to manage the transition effectively.

- [x] Add Web Vitals 
- [x] Add Error Boundary 
- [ ] Update not found pages to use  app routing
- [x] #3238

**Comment by Calinator444** [comment]
@wicksipedia wanted me to monitor traffic to the app router pages


![Image](https://github.com/user-attachments/assets/9d67d80d-8183-41ff-afb1-3c4767301fcd)

**Comment by amankumarrr** [comment]
for reference - https://nextjs.org/docs/canary/app/api-reference/file-conventions/error

**Comment by Calinator444** [comment]
I have configured the error boundary but the logging inside of `global-error.tsx` aren't appearing in app insights.

I've tried:
- Logging a separate exception in staging (to ensure the app insights key was correct)
- copying the contents of `global-error.tsx` into `layout.tsx` to ensure that the app insights context provider was being initialized correctly
- Checking the console logs to ensure that `useEffect` was being called inside of `layout.tsx`

![Image](https://github.com/user-attachments/assets/059f164d-22f8-4e3f-968f-fbbbd69eff12)
**Figure**: **App Insights logs & code samples for error page**

**Comment by Calinator444** [comment]
TODO - make sure hydration issues get logged

**Comment by Calinator444** [comment]
As per my conversation with @wicksipedia I will also create a not found page as part of this PBI

**Comment by Calinator444** [comment]
Betty asked me to clean up the mobile layout for the error page
![Image](https://github.com/user-attachments/assets/f1cc41a2-25f0-4bb6-850e-9fe737bc1a2f)


I also added a subtle fade in for the background image below the navbar


![Image](https://github.com/user-attachments/assets/aa2b8e75-1184-470f-90b0-7f06be5e0244)

**Comment by Calinator444** [comment]
**Done** - I tested sending logs from the error page from staging to app insights and was successful. 

I may still need to test throwing an exception within the layout in staging as we do not have any exceptions I can manually trigger in production.

![image](https://github.com/user-attachments/assets/cc7b368b-62b2-49f0-afcd-d5b3b622598b)
**Figure**: **Runtime error in root layout being caught in app insights**

![image](https://github.com/user-attachments/assets/7025cbaa-de3f-433e-aa51-f015f01644dd)

**Figure**: **Error inside of error.tsx being logged (from local)**
