### ISSUE TITLE
🔎 Semrush - Weekly track and improve SEO #5

### ISSUE THREAD

**Issue by Calinator444** [SSWConsulting/SSW.Website#2602]
Improve SEO using semrush

URL: [https://www.semrush.com/siteaudit/campaign/16078651/review#overview](https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.semrush.com%2Fsiteaudit%2Fcampaign%2F16078651%2Freview%23overview&data=05%7C02%7CJeoffreyFischer%40ssw.com.au%7C844a6b7d94314a096dbd08dc59c68ac7%7Cac2f7c34b93548e9abdc11e5d4fcb2b0%7C0%7C0%7C638483956578243635%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=cYelQwC0XmTPzXZSING%2F09XjZnN9PVEBAcxSwyTvO5c%3D&reserved=0)

**Comment by andrewwaltosssw** [comment]
Work done this sprint:
- Fixed duplicate page titles on 3 pages https://github.com/SSWConsulting/SSW.Website/pull/2650 (new page titles test-passed by @camillars )
- Uploaded 80 toxic backlink domains to disavow tool in Google. New count of disavowed domains: 439

![Image](https://github.com/SSWConsulting/SSW.Website/assets/87786621/64f52f01-0b32-45da-ae09-edc82f545867)
**Figure: Screenshot of disavowed links**
