### ISSUE TITLE
💸 Front Door - Adding redirect for Archive pages

### ISSUE THREAD

**Issue by amankumarrr** [SSWConsulting/SSW.Website#2603]
**Description**  
Add Front Door redirects for all `/history` pages from old to new urls.

```[tasklist]
### Tasks
- [ ] ~Create FrontDoor Rule~
- [ ] ~Add redirects~
```

```[tasklist]
### Tasks
- [x] Get a solution approved
```

**Comment by amankumarrr** [comment]
@wicksipedia 

I've organized the redirects for the Front Door Rulesets. I've identified some conflicts and identified some extensive redirects that need further subdivision to adhere to the limit of 100 redirects per rule.

Considering the numbers, it appears that we'll need at least 30 rulesets to accommodate all of them.

❌ = Conflict with existing routes
📈 = Huge that needs further subdivision
✅ = Can be added for the Front Door 

![Image](https://github.com/SSWConsulting/SSW.Website/assets/71385247/83e945cd-5971-4af4-a327-1bd0256f81ad)

**Figure: Redirects by per path from the script**

**Comment by amankumarrr** [comment]
@wicksipedia 

The challenge we're facing is the need to create 10 new routes to accommodate all 595 redirects. This arises from the constraint of only being able to have 100 redirects per route. While adding new routes will increase load times, we can alleviate this by incorporating some of the redirects into existing routes.

## Recommendation plan:

The plan is to create 10 new routes to accommodate 490 redirects, as they cannot fit into the current routes. The remaining 105 redirects will be accommodated within the existing routes.

**Total Redirects: 595**

| Route                        | Path               | Existing Route | Available Room | We Can Use for /archive |
|------------------------------|--------------------|----------------|----------------|--------------------------|
| legacy-redirect              | '/'                | 6              | 94             | 94                       |
| static-redirect-consulting   | '/ssw/consulting' | 90             | 10             | 1                        |
| static-redirect-events       | '/ssw/events/'    | 14             | 86             | 86                       |
| static-redirectss            | '/'                | 81             | 19             | 20                       |
| website-redirect             | '/'                | 6              | 94             | 0                        |



![Image](https://github.com/SSWConsulting/SSW.Website/assets/71385247/1c9364f1-eaca-4db8-bfb1-da4bccece668)

**Figure: list of routes that can be accommodate in the existing ones** 



![Image](https://github.com/SSWConsulting/SSW.Website/assets/71385247/6846dd4e-c093-44b5-8880-5f69d0c93929)

**Figure: List of routes that needs to be created**

**Comment by amankumarrr** [comment]
As of now, four new routes have been added to the Front Door. Currently, all redirects are directed to "/archived," but once we create the folder named "archive," we will replace these redirects. Approximately 400 redirects have been added. Below are the routes affected:

- NetToolKit/
- Events/
- Standards/Better Software/
- Standards/

**Comment by amankumarrr** [comment]
We have **added redirection for 535** routes out of **595** so far. However, **60 routes are left** because we have reached the limit of 800 resources per resource group.

**Comment by amankumarrr** [comment]
@wicksipedia 

To solve this problem, I have the following suggestion:

We should use a script or possibly a Cloudflare Worker to handle the redirection for us. Initially, this will apply only to routes under /archive. We can then incrementally handle the remaining routes.

We need to create a ruleset for the following routes. Based on the request, we can redirect the user to the new domain with the same path. Upon matching in that script, the user will redirected accordingly.

![Image](https://github.com/SSWConsulting/SSW.Website/assets/71385247/b1f1843a-2e5e-4ce4-ae0e-059e1ef26c35)

✅ Advantages:
- Ease of deployment
- Scalable - No limit on redirects
- Can incrementally move all traffic to the worker URL

❌ Disadvantages:
- Maintainability
- Development cost - new service
- On-going cost (~$120/year)


This approach will help us stay within the resource group limits while efficiently managing the redirects.

**Comment by amankumarrr** [comment]
@wicksipedia @bradystroud @andrewwaltosssw @Calinator444 

I have tested the worker from Cloudflare, and it seems to be working absolutely fine as expected. I think we should use this for the /archive routes on the free tier, as I don't anticipate much traffic on those pages.

Here is the URL that is being redirected by the worker: https://tfs365.com/ssw/download/padfiles/pad_ssw.nettoolkit.htm

**Comment by Calinator444** [comment]
> [@wicksipedia](https://github.com/wicksipedia) [@bradystroud](https://github.com/bradystroud) [@andrewwaltosssw](https://github.com/andrewwaltosssw) [@Calinator444](https://github.com/Calinator444)
> 
> I have tested the worker from Cloudflare, and it seems to be working absolutely fine as expected. I think we should use this for the /archive routes on the free tier, as I don't anticipate much traffic on those pages.
> 
> Here is the URL that is being redirected by the worker: https://tfs365.com/ssw/download/padfiles/pad_ssw.nettoolkit.htm

I got a little confused when I clicked the link and it took me to a page that 404s but then I remembered that the front door configuration for changing /history to archived hasn't been finished yet.

**Comment by amankumarrr** [comment]
@wicksipedia 
It also provides version control and some logs as well.

![Image](https://github.com/SSWConsulting/SSW.Website/assets/71385247/bf2eb928-22b2-4a3c-a973-08b6dbbbe317)

**Figure: Showing the graphical stats for the redirects**

**Comment by amankumarrr** [comment]
@wicksipedia @bradystroud @andrewwaltosssw @Calinator444 

From Front Door Stats of `/ssw/` route, I found some stats for the requested URLs for the past 30 days, 


![Image](https://github.com/SSWConsulting/SSW.Website/assets/71385247/41d3d31d-cc47-4a1d-a4a2-259a3aab03a1)

**Figure: Stats from Front Door logs for /ssw/ route grouped by request URL**

Interestingly, most of the traffic was from `/ssw/` 


![Image](https://github.com/SSWConsulting/SSW.Website/assets/71385247/df964a46-b709-411f-8ef4-baafa6bcf97f)

**Figure: stats for overall traffic from the Front Door logs**

If we turn off the VM, it will drastically reduce the traffic from the Front Door. Most of the traffic seems to be coming from the v1 server, likely due to some bugs.

And our v3 has only 2.5 million traffic.



![Image](https://github.com/SSWConsulting/SSW.Website/assets/71385247/e67aed80-0601-4ba8-8d6b-7aa90bf680df)

**Figure: Stats for ssw.com.au v3 from Front Door logs**

**Comment by amankumarrr** [comment]
@wicksipedia 

❌ I'm blocked on this as I'm waiting for a quote from FASTLY.

**Comment by amankumarrr** [comment]
We decided to go with Cloudflare and purchase please approved with the email subject "SSW.Website - Move from Front Door to Cloudflare"
