### ISSUE TITLE
💤 Migration | Turn off /ssw route - soft turn off of VM

### ISSUE THREAD

**Issue by andrewwaltosssw** [SSWConsulting/SSW.Website#2604]
We still need the VM for Rules and People at the moment so we want to 'soft' turn off the old website by turning the /ssw route off

- [x] Make sure ~FrontDoor~ Cloudflare redirects are in place and working from #2603 
- [x] Blocked by #2785 and reciprocal change to https://github.com/sswconsulting/ssw.people
- [x] Turn off `/ssw` route

**Comment by Calinator444** [comment]
This PBI is blocked until we can set up the Cloudflare redirects. Moving this back to backlog ready.

**Comment by jeoffreyfischer** [comment]
This was Done as part of this PBI #2699
