### ISSUE TITLE
📝 README to edit pages in /history

### ISSUE THREAD

**Issue by jeoffreyfischer** [SSWConsulting/SSW.Website#2609]
**Description**
As per my conversation with @adamcogan, there is currently no documentation on how to edit pages in the /history folder
Link to history folder: https://ssw.com.au/history
We need a document that explains step by step how to make a change on one of theses pages.

**Tasks**
- [ ] Create the ReadMe that details the steps to edit an .HTML page
- [ ] Get another Developer to follow the ReadMe and make a change on an .HTML page

**Screenshot**
![Image](https://github.com/SSWConsulting/SSW.Website/assets/106663901/f43e21cf-211d-4243-9eaf-591587f1dfb4)
**Figure: Column that contains all the .HTML pages that need to be editable**

**Comment by jeoffreyfischer** [comment]
Closed as the file already exists under Teams | SSW Website v3 | General | Files | SSW Website - How to Edit Archived Pages
Link: https://sswcom.sharepoint.com/:w:/s/SSWWebsitev3/ET51Dr2asjdNn89XtekVjpkBBMRAHrSwP-8q9g9ERJ6Etw?e=WjEWHv


**Screenshot**
![Image](https://github.com/SSWConsulting/SSW.Website/assets/106663901/1eccd1cd-141f-46da-a59f-5be1300be58a)
**Figure: location of the Word file that explains how to Edit archived pages**

**Comment by bradystroud** [comment]
Closing as @jeoffreyfischer forgot to click close 🙂
