### ISSUE TITLE
Update /history route to /archive

### ISSUE THREAD

**Issue by Calinator444** [SSWConsulting/SSW.Website#2614]
As per my conversation with @tiagov8  the route for the migrated pages should be changed from `/history` to `/archive`

```[tasklist]
- [x] Change the route for the archived pages from /history to point to /archive
- [x] Update the navbar links within the previously archived pages to point to /archive
- [x] Update any image urls within the pages so that they point to /archive
- [x] Update the archive script so that any future migrated pages will point to /archive
- [x] Update any previously ported CSS files so that the urls will point to /archive instead of /history
```

**Comment by wicksipedia** [comment]
Changed route to the noun

**Comment by Calinator444** [comment]
The pages have been moved in blob storage and the links have been updated, but the redirects haven't been set up yet



![Image](https://github.com/SSWConsulting/SSW.Website/assets/65635198/77e3ee66-5779-4257-9199-8920ed201287)

**Comment by Calinator444** [comment]
The pages have been moved in blob storage and all of the CSS links and images have been fixed up. Marking this as done.

![Image](https://github.com/SSWConsulting/SSW.Website/assets/65635198/63b99dec-b060-43ee-9346-0ec2b4e6a01c)

**Comment by tiagov8** [comment]
Hi @Calinator444 

The page https://www.ssw.com.au/ssw/CodeAuditor/ is still up. 

- [ ] 1. Can we have the redirection in the definition of done?
- [ ] 2. This CodeAuditor page is used on the Notepad exercise in SugarLearning, so it's importatn that the page is accessible from a Google Search for "CodeAuditor"

![Image](https://github.com/SSWConsulting/SSW.Website/assets/12601228/2fa4abd2-e816-4c5a-bc0a-8c421b73ded4)

**Comment by Calinator444** [comment]
Hi @tiagov8 

\> 1. Can we have the redirection in the definition of done?

Aman has a PBI to set up the redirects (See here: [#2603](https://github.com/SSWConsulting/SSW.Website/issues/2603)) should this still be in the definition of done?

**Comment by tiagov8** [comment]
> #2603

Yes, please close this Issue only when the redirects are set

**Comment by Calinator444** [comment]
CC: @tiagov8 

As per my conversation with @wicksipedia  setting up the redirects is the last step. This PBI just involves moving the files to `/archive` and fixing any references within the files (which has been done).

Marking this as done.
