### ISSUE TITLE
💸 Newsletter template images currently stored in ASPX need to be migrated

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.Website#2617]
cc @camillars @sethdaily @PennyWalker @wicksipedia @adamcogan @Calinator444 

Hi team,
On the newsletters we have template images that are stored in the old ASPX solution ❌

Newsletter example: https://ssw.com.au/images/newsletter-uploads/2024/_2024_03__.NET%20Migrations%20Made%20Easy__.html
Image example: https://ssw.com.au/ssw/NETUG/SSWUpdate/Images/Template/NETUG-Melbourne-Dark-Mode.png 

Those images are (or most of them are) stored in the [old ASPX website solution](https://ssw2.visualstudio.com/SSW.Website)...

We don't want to rely on that ASPX solution anymore, we need to figure out another place to store those images.

- [x]  1. Please define the new location for those images

- [x]  2. Migrate all images to the new location

- [x]  3. Tell the marketing team to update the image paths in the template

- [x]  4. Capture redirects needed to preserve existing links in emails

Related to https://github.com/SSWConsulting/SSW.Website/issues/2449

**Comment by andrewwaltosssw** [comment]
cc: @wicksipedia 

> Please define the new location for those images

Some images had already been moved to `public/images/Newsletters/`, `public/images/Newsletters/EventsBanners/` , and `public/images/Newsletters/Template/`. Used the same dirs for these changes

>Migrate all images to the new location

Done. #2687 

> Tell the marketing team to update the image paths in the template

Done. Updated and shared latest newsletter template with @PennyWalker 

 > Capture redirects needed to preserve existing links in emails

Done. Captured [Redirects](https://sswcom-my.sharepoint.com/:x:/g/personal/andrewwaltos_ssw_com_au/EePqDU6hkIJImgo0PBA6ET4B9D4wPelwOQE5udpt0tKsww?e=2fppqD)
