### ISSUE TITLE
✨ Character count within TinaCMS

### ISSUE THREAD

**Issue by samsmithssw** [SSWConsulting/SSW.Website#2633]
**Is your feature request related to a problem? Please describe.**

When adding content to a consulting service page, some free text boxes have character limits. There is no indication of how many characters over or under I am, so I have to go to a different software to get a character count.

See screenshot for example:
![Image](https://github.com/SSWConsulting/SSW.Website/assets/115435510/2a700d04-dcfb-4a4c-9e8c-a5faaaed8713)

**Describe the solution you'd like**
As per my conversation with @andrewwaltosssw , we have the ability to implement a feature that gives us a character count on the front-end so that the user can see the value they are currently at.

Options we would go for:

- A live character count **(recommended)**
- Show me how many characters I have gone over by

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by andrewwaltosssw** [comment]
Done. Live count added for SEO Title and Description fields:

![Image](https://github.com/SSWConsulting/SSW.Website/assets/87786621/86d42ac3-85c8-4368-84e2-7ef8f25624ec)
**Figure: Done gif of the editor with live count**

Done video: https://youtu.be/z52Sgz9wKDU
TODO: Update Wiki with new component
