### ISSUE TITLE
Are you stuck on legacy technologies page?: incorrect text shown for default selection on page load

### ISSUE THREAD

**Issue by leehawkinsssw** [SSWConsulting/SSW.Website#264]
The https://www.ssw.com.au/ssw/Consulting/Are-You-Stuck.aspx page loads with "I'm a Business Person" selected but shows the text relevant to when "I'm a Developer" is selected.

**Comment by bradystroud** [comment]
Closing as this was broken on the old website and was fixed when it was migrated to the new one
https://www.ssw.com.au/consulting/are-you-stuck
