### ISSUE TITLE
Signing up for newsletters doesn't work

### ISSUE THREAD

**Issue by leehawkinsssw** [SSWConsulting/SSW.Website#267]
On the Newsletters page at https://www.ssw.com.au/ssw/NETUG/SSWUpdatePrevious.aspx, pressing the "Join" button results in an error page:

![image](https://user-images.githubusercontent.com/106290015/221101471-8e497c28-6167-4567-b2a2-59b07f767128.png)

**Comment by wicksipedia** [comment]
Since this bug was reported on the old website, we won't fix it.

Escalated #282 to add the functionality to this site
