### ISSUE TITLE
💄Consulting pages - Inconsistent Headers Between v1 and v3

### ISSUE THREAD

**Issue by Harry-Ross** [SSWConsulting/SSW.Website#271]
![image](https://user-images.githubusercontent.com/20507092/221442388-c491aa32-ae1b-4327-ba73-d806f89e4c16.png)
**FIgure: v1  /consulting/bots.aspx**

![image](https://user-images.githubusercontent.com/20507092/221442356-82d26ae1-88a3-4028-baa7-933cc45c6b53.png)
**Figure: v3 /consulting/bots**

**Comment by wicksipedia** [comment]
implemented in #304
