### ISSUE TITLE
🔍  SEO | Pages not being indexed

### ISSUE THREAD

**Issue by andrewwaltosssw** [SSWConsulting/SSW.Website#2766]
We received a message from Google about some pages not being indexed because of:
- Duplicate without user-selected canonical
- Soft 404

- [ ] Investigate and fix

![Image](https://github.com/SSWConsulting/SSW.Website/assets/87786621/4410e91b-580b-4d5f-880b-e887c4afe2dc)
**Figure: Notification from Google**

cc: @camillars @sethdaily @wicksipedia

**Comment by jeoffreyfischer** [comment]
I have created a more detailed issue to fix this problem: https://github.com/SSWConsulting/SSW.Website/issues/2772
