### ISSUE TITLE
🐛 SSW Events - Incorrect Redirect

### ISSUE THREAD

**Issue by joshbermanssw** [SSWConsulting/SSW.Website#2824]
cc: @Calinator444 
**Describe the bug**
I click on the AI Hack Day - Sydney, on the SSW Events page. I get redirected to some other page not showing me info about the AI Hack Day

**To Reproduce**
1. Head to https://ssw.com.au/events
2. Click on AI Hack Day - Sydney 
3. Observe 

**Expected behavior**
It takes me to a page telling me about the AI Hack Day 

**Screenshots/Video**
If applicable, add screenshots/video to help explain your problem.
Remember to mark the area in the application thats impacted.

**Comment by Calinator444** [comment]
CC @wicksipedia 

Hey @joshbermanssw, I'm closing this as per your reply to the email thread.

To summarize there was a redirect that would divert traffic for aihackday.com to a domains for sale page but @chrisschultzssw removed it.




![Image](https://github.com/user-attachments/assets/31b6da1a-5f36-45b5-bb48-b14a7b9d7535)
