### ISSUE TITLE
💄 Homepage - Remove extra space between logos

### ISSUE THREAD

**Issue by jeoffreyfischer** [SSWConsulting/SSW.Website#2852]
Based on the email chain:

**From**: @camillars 
**Sent**: Wednesday, July 3, 2024 9:53 AM
**To**: @tiagov8 ; @jeoffreyfischer 
**Cc**: @JeanThirion ; @UlyssesMaclaren 
**Subject**: RE: Improving mobile UX on ssw.com.au and ssw.fr - Client's logo order

**Description**

URL: https://www.ssw.com.au/

In mobile view, the company logos at the bottom of the page have too much white space between them. 
This is bad UX as it takes longer to scroll down.

**Task**
- [x] Remove unnecessary extra space between logos

**Screenshots**
![Image](https://github.com/user-attachments/assets/a4b97ca0-b460-40e7-bfb1-b485eff560ac)
**Figure: Remove extra space between logos**

**Comment by jeoffreyfischer** [comment]
✅ Fixed - as per my conversation with @bettybondoc:
- the gap between logos has been removed
- the "Events Cinemas" logo has been changed from black to white background - to be consistent with the other logos

**Note**
Betty realised that some of these logos are inconsistent.
I created a PBI to redesign all these company logos: #2861 


**Screenshots**
![Image](https://github.com/user-attachments/assets/56a0196a-6e2a-4c7b-954e-c56ec18652b4)
**Figure: The gap between logos has been set to 0**

![Image](https://github.com/user-attachments/assets/9ab688af-ce9c-4289-bc4a-583c47605e3c)
**Figure: The "Events" logo has been changed to white background**

**Comment by Calinator444** [comment]
@jeoffreyfischer 

It looks like there are variants of this component with a gray background. We may need to open up a new Issue and fix this.

![Image](https://github.com/user-attachments/assets/a5c73684-05d7-4ef2-8690-5650ef57268a)
