### ISSUE TITLE
🧱 WAF - Tune it to stop bots spam

### ISSUE THREAD

**Issue by jeoffreyfischer** [SSWConsulting/SSW.Website#2880]
We need to tune the Web Application Firewall (WAF) to effectively block and mitigate bot-driven spam attacks

**Comment by jeoffreyfischer** [comment]
For more details, see with @wicksipedia

**Comment by tkapa** [comment]
Done - As per my conversation with @chrisschultzssw and @wicksipedia, we've gone over the WAF settings in Cloudflare and enabled the settings that make sense for SSW Website.

There is a "Bots" section of Cloudflare that can help mitigate bad bots. However, should we want to enable it requires $$$.

See the video Chris and I did here https://youtu.be/P-Yv3_XNhZQ
