### ISSUE TITLE
☁️Cloudflare - Add missing base routes Cloudflare (/)

### ISSUE THREAD

**Issue by Calinator444** [SSWConsulting/SSW.Website#2887]
@Calinator444, @jeoffreyfischer, @wicksipedia 

### Description
A number of the base pages don't redirect to their default variants anymore. (e.g. ssw.com.au/ssw/codeauditor/ doesn't redirect to ssw.com.au/ssw/codeauditor/default.aspx anymore). We need to add redirects to fix this. e.g. ssw.com.au/ssw/codeauditor/ should point to their migrated variant (ssw.com.au/ssw/codeauditor/default.html)

```[tasklist]
- [ ] Use CodeAuditor to find the broken links (e.g. pages ending in "/")
- [ ] Test the redirects using tfs365.com
- [ ] Add a redirect to their archive variants)
```

**Comment by jeoffreyfischer** [comment]
This is a Duplicate.
Fixed by #2902
