### ISSUE TITLE
Live banner - Update banner text and countdown logic

### ISSUE THREAD

**Issue by jimmidier** [SSWConsulting/SSW.Website#289]
As per conversation with the TV team, we need to update the live banner to be:

- [ ] Add field to Events SharePoint list - LiveStreamStartDateTime
- [ ] From:
  Airing in X hours and X minutes. (6PM Sydney)
To:
  Airing in X hours and X minutes. **Live stream starts at {{LiveStartDateTime}}pm. Doors open at {{StreamStartDateTime}}pm**

**Comment by wicksipedia** [comment]
Updated requirements as per conversation with @camillars and @jontygardner
