### ISSUE TITLE
⚰️ Website VM - Turn it off

### ISSUE THREAD

**Issue by jeoffreyfischer** [SSWConsulting/SSW.Website#2998]
TODO fill in

1. FrontDoor logs
2. IIS logs
3. Sys Admin

**Comment by amankumarrr** [comment]
no logs found from Front Door for v1 site



![Image](https://github.com/user-attachments/assets/d94f0aa0-1bb0-4ad3-b213-8031aa044f74)



**Figure: Front door logs for the past 7 days**

**Comment by amankumarrr** [comment]
@chrisschultzssw @wicksipedia 

We switched off the VM, but with the help of @wicksipedia, we discovered that there was still traffic on our v1 site, so Chris S turned it back on. Over the past 7 days, we've had around 15k requests to the server. We need to investigate where this traffic is coming from.

**Comment by amankumarrr** [comment]
Attaching the log file from IIS server. 
[iis-logs.xlsx](https://github.com/user-attachments/files/16773573/iis-logs.xlsx)

**Comment by amankumarrr** [comment]
We found around 15,492 hits on the IIS server for the past 7 days. Upon further investigation:

-   15,445 were the direct requests to the server, either via IP address or from prod.ssw.com.au  
-   27 requests were bots trying to find /owa endpoint which doesn’t exist 
-   10 were bots from China
-   10 were digital bots hosted by Digital Ocean

**Comment by amankumarrr** [comment]
✅Done - As per @chrisschultzssw, the VM is turned off and we will be decommissioning it in a week.
