### ISSUE TITLE
🐛 SEMrush - nofollow on external links

### ISSUE THREAD

**Issue by amankumarrr** [SSWConsulting/SSW.Website#3008]
**Describe the bug**
SEMrush is recommending that we avoid using nofollow on internal links, and this applies to about 1,979 links on our site as per the last SEMrush audit report.

![Image](https://github.com/user-attachments/assets/0ec7562d-6dd8-4130-895a-345469360af3)

**Figure: SEMrush description on nofollow**

**Comment by jeoffreyfischer** [comment]
- [x] Check what the links are
- [ ] Discuss with @wicksipedia

**Comment by amankumarrr** [comment]
@wicksipedia  

Already done ✅

Most of the links suggested by SEMrush are external SSW links, including those from YouTube, GitHub, and social networking sites. However, according to SEO best practices outlined by Google (https://developers.google.com/search/blog/2019/09/evolving-nofollow-new-ways-to-identify), it is recommended to add the nofollow attribute to external links.

I've attached the list of URLs below. Therefore, I'm closing this issue as Not Planned.

[www.ssw.com.au_nofollow_attributes_in_outgoing_external_links_20240903.xlsx](https://github.com/user-attachments/files/16843849/www.ssw.com.au_nofollow_attributes_in_outgoing_external_links_20240903.xlsx)
