### ISSUE TITLE
💸 SEMrush vs CodeAuditor Audit Reports

### ISSUE THREAD

**Issue by amankumarrr** [SSWConsulting/SSW.Website#3048]
**Description**  
We found some discrepancies in the reports from both crawlers. We need to investigate whether we can achieve the same results with SEMrush or if it makes sense to continue running CodeAuditor.

- [x] Investigate

**Comment by amankumarrr** [comment]
**Context:**

After setting the SEMrush crawler source to `sitemap`, we observed that it didn't detect many broken links. This limitation occurs because, when the source is set to `sitemap`, the crawler primarily checks if the page is loaded correctly, rather than verifying the accessibility of all links on the page.

To address this, I created another project for site auditing, this time configuring the crawler source to `website`. This approach allowed me to identify broken links more effectively. However, the crawler could only cover around 19% of the pages listed in the sitemap. This is because it could only find links up to 4 levels deep from the homepage, meaning not all website pages were covered.

**Recommendation for SEMrush:**

- **Sitemap Crawling:** Use this method to ensure all pages are functioning as expected and to identify any potential issues with SEO
- **Website Crawling:** Run additional audits to identify broken links.

---

**Comparison Between SEMrush and CodeAuditor:**

| **Feature**                                      | **SEMrush**                                           | **CodeAuditor**                                     |
|--------------------------------------------------|-------------------------------------------------------|----------------------------------------------------|
| **SEO Best Practices**                           | Provides detailed insights and recommendations        | Not focused on SEO best practices                   |
| **Link Accessibility**                           | Indicates if a page was redirected or has broken links | Crawls every page thoroughly to find broken links   |
| **Crawling Depth**                               | Limited by sitemap or settings                        | Crawls deeply but may require more refactoring       |
| **Report Quality**                               | Provides detailed broken link trails                  | Requires additional work to provide accurate reports|

**Conclusion:**  

Given the maintenance costs associated with CodeAuditor, it makes sense to leverage SEMrush for crawling as it provides a cost-effective alternative. Since we are already paying for SEMrush, we should use it to obtain the closest possible crawl results. SEMrush not only identifies broken links but also offers additional SEO insights and analyses, making it a valuable tool beyond just detecting broken images.


**Recommendation to Achieve Results Similar to CodeAuditor:**

**Set Up Separate Site Audits**: 

Configure individual site audits for each route, ensuring that each audit points to its respective blob storage URL. This approach allows SEMrush to thoroughly crawl each route and detect broken links effectively, similar to the detailed results provided by CodeAuditor.



![Image](https://github.com/user-attachments/assets/f18d0abd-1759-4f20-ae27-e8dade9f41e8)

**Figure: CodeAuditor - Showing most of the broken links are from `/ssw`**

**Comment by amankumarrr** [comment]
@wicksipedia 

As my conversation with @bradystroud while checking my manage up email on stop using CodeAuditor, we explored several options with SEMrush. However, we found that SEMrush alone is not fully capable of meeting our needs yet:

- SEMrush cannot detect broken links effectively when the source is a sitemap.
- SEMrush is unable to detect code issues like CodeAuditor does.
- We initially considered running each site audit separately to identify broken links, but this approach may lead to other issues, such as indexing problems.

Given these limitations, we believe it’s best to continue using CodeAuditor for now.

**Comment by amankumarrr** [comment]
Remaining tasks:
- [x] record a video 
- [x] send an email

**Comment by amankumarrr** [comment]
Done video - https://www.youtube.com/watch?v=dH2aWQXCiIo (2:33s)

**Comment by jeoffreyfischer** [comment]
Done Video V2 - https://www.youtube.com/watch?v=adCpW9fc7y4 (3min)

**Comment by amankumarrr** [comment]
Just recorded v3 - https://www.youtube.com/watch?v=n4IoMFb6iP0 (3min)

**Comment by amankumarrr** [comment]
v3 - https://youtu.be/rytfjiBCQnI (3min) - edited version

**Comment by amankumarrr** [comment]
✅ Done - Email has been sent with the subject "SSW Website - CodeAuditor and SEMrush - Keep using both tools"
