### ISSUE TITLE
🐛 CodeAuditor - Failed wokflow

### ISSUE THREAD

**Issue by jeoffreyfischer** [SSWConsulting/SSW.Website#3055]
**Describe the bug**
The "Weekly CodeAuditor - Test" has failed twice today.
This needs to be fixed so that we can keep using it to track broken pages on the Website.
As per my conversation with @zacharykeeping , he will investigate this issue.

**To Reproduce**
1. Go to https://github.com/SSWConsulting/SSW.Website/actions/workflows/weekly-codeauditor-scan.yml
2. Run the workflow from `main`
3. Once finished (usually it takes about 30min) see the "failed" result

**Expected behavior**
The workflow should succeed

**Screenshots/Video**

![Image](https://github.com/user-attachments/assets/b20a9449-5f5e-45a8-9077-a1c6899a73f2)
**Figure: "Weekly CodeAuditor - Test" has failed twice**

![Image](https://github.com/user-attachments/assets/99785b66-620e-490d-a550-1b493a40f1df)
**Figure: Error that is detected**

**Comment by jeoffreyfischer** [comment]
Update - Code Auditor is working again! But it would still be useful to investigate what happened 👍

**Comment by zacharykeeping** [comment]
I have implemented a bugfix on CodeAuditor here: https://github.com/SSWConsulting/SSW.CodeAuditor/pull/933

I'm hoping that helps prevent this issue from happening and also gives us some more info in the future if this happens again.

Please keep an eye on the scans and let me know if this or any other issues pop up.

**Comment by jeoffreyfischer** [comment]
I will run workflows once a day for the whole week to confirm that the fix worked 👍

**Comment by jeoffreyfischer** [comment]
✅ Done - the workflows all successfully completed throughout the week
