### ISSUE TITLE
🐛 LiveStream - generating lots of hydration/CORS errors in console

### ISSUE THREAD

**Issue by wicksipedia** [SSWConsulting/SSW.Website#306]
![Image](https://user-images.githubusercontent.com/600044/221717163-f80025b7-494f-4639-acde-7c6780410f05.png)

**Comment by jimmidier** [comment]
Tested on both staging and production and the error is no longer occuring now. Closing the issue.
![image](https://github.com/SSWConsulting/SSW.Website-v3/assets/16027480/9ed36354-1bf7-40aa-a6c1-e385db0d4282)
