### ISSUE TITLE
🔍 SEO - Reduce Total Blocking Time

### ISSUE THREAD

**Issue by jeoffreyfischer** [SSWConsulting/SSW.Website#3067]
**Description**
Our SEO is down due to the TBL (see screenshot below).

**Screenshots**
![Image](https://github.com/user-attachments/assets/5143e5cb-0024-4520-9ee4-0d65403b3d53)
**Figure: TBL is high**

**Note**: Work done to improve live stream banner performance was done as part of this PBI with the misunderstanding that it would reduce total blocking time. A separate issue was created for this - see https://github.com/SSWConsulting/SSW.Website/issues/3108

**Comment by Calinator444** [comment]
I tried adding additional dynamic imports but didn't see significant performance improvements

From analyzing the code I discovered that the livestream banner performs a data fetch for every page, which is expensive. I'm in the progress of converting this to a static fetch which should reduce total blocking time, particularly around user groups.

![Image](https://github.com/user-attachments/assets/d6e9dd08-fe79-4813-8d70-f60a661a2299)
**Figure**: **Page speed insights for slot with new dynamic imports (average performance in staging 60)**

**Comment by Calinator444** [comment]
TODO: Look at why overall performance has regressed from 90

**Comment by Calinator444** [comment]
I've looked into re-enabling Party Town, however Next JS workers are still experimental and are not guaranteed to work with all third party scripts.

**Note**: PartyTown was disabled due to compatibility issues with Hotjar and microsoft Clarity. Compatibility must be ensured before enabling it. https://github.com/SSWConsulting/SSW.Website/pull/1091

https://nextjs.org/docs/pages/api-reference/components/script#optional-props

**Comment by Calinator444** [comment]
As per my conversation with @jeoffreyfischer , I will investigate at which point in time the TBT regressed (it appears to have been between sprint 67-68).

@amankumarrr Also mentioned that migrating to app routing could improve performance as well.

**Comment by Calinator444** [comment]
I enabled bundling for Pages dependences. The results look promising on staging.

Our live site is on the left, staging slot with bundling enabled is on the right

![image](https://github.com/user-attachments/assets/c0910d53-0c05-4f87-a1bc-a3186e7317c9)
**Figure**: **Staging vs production TBT**

**Comment by Calinator444** [comment]
It's worth mentioning that the Total Blocking time can fluctuate fairly randomly. Here are some page speed insight reports I ran on the 20th of September.

| TBT    | Time   |
|--------|--------|
| 4640ms | 6:30pm |
| 2920ms | 6:30pm |
| 3240ms | 7:00pm |

**Comment by Calinator444** [comment]
@wicksipedia

As per my conversation with @amankumarrr I think it might be worth parking this for now until we migrate to App routing.
Link to related PBI: https://github.com/SSWConsulting/SSW.Website/issues/3153

![image](https://github.com/user-attachments/assets/f1c63b3d-7a3f-4c6b-a456-4989c7b47c6e)
**Figure**: **Page using App routing (/products)**
<br>
![image](https://github.com/user-attachments/assets/39281c17-0829-4ff9-801a-ba444364f4cf)
**Figure**: **Similar page using Pages router (/industry)**

**Comment by Calinator444** [comment]
@wicksipedia 

As per our conversation we are going to park this for now until we move to app routing.

This sprint I tried enable external dependency bundling for pages router dependencies but it cause build errors in our pipeline. This is an experimental feature and I don't recommend enabling it this close to switching over to rules.

![Image](https://github.com/user-attachments/assets/8291bdff-aedd-473d-9d61-30feb46259ce)

**Comment by jeoffreyfischer** [comment]
As per our conversation with @adamcogan during Sprint Review 75, @amankumarrr will work on implementing app-routing on SSW Website
TODO: Add link to PBI

**Comment by amankumarrr** [comment]
@wicksipedia @Calinator444 @bradystroud @jeoffreyfischer 

Interestingly, the bundle size of the migrated app routing page is almost half of that on the page routing, indicating that app routing could potentially reduce TBT (Total Blocking Time). However, the performance metrics from PageSpeed Insights don't show a significant improvement. I’ll investigate further to see if we can enhance performance and web vitals before implementing it on the homepage.


![Image](https://github.com/user-attachments/assets/54c5b24d-d67a-4bd9-9304-b1a778745f9f)
**Figure: PageSpeedInsights report of /product and /industry with their tree map respectively**

**Comment by Calinator444** [comment]
@amankumarrr I don't think bundling is enabled by default for pages router pages 

I investigated enabling dependency bundling for pages router pages during the last sprint but it caused errors on our build pipeline. Overall it's not a very stable feature so moving to app routing should be the priority for now.

https://nextjs.org/docs/pages/building-your-application/optimizing/package-bundling

**Comment by jeoffreyfischer** [comment]
❌ Not Done - We are hoping that this will be fixed by moving from Pages Router to App Router in #3159

**Comment by amankumarrr** [comment]
TBT will improve with this issue - https://github.com/SSWConsulting/SSW.Website/issues/3159. Upon further investigation, I found that while `/_next/static/*` was cached by Cloudflare, `/_next/image/*` was still being served by TinaCloud. This presents an opportunity to potentially save more TBT.

- [x] Enable cache for `_next/image/*`

**Comment by amankumarrr** [comment]
Fixed the layout shift issue with the live stream banner 

Screenshot:
![image](https://github.com/user-attachments/assets/8cec390e-93de-4811-abad-7787055c979a)
**Figure: Before** 

![image](https://github.com/user-attachments/assets/e48af73c-7e63-4fed-b4ec-8e8f16c525bc)
**Figure: After**

**Comment by amankumarrr** [comment]
✅ Removed the prefetching of data on homepage 
✅ Converted jpg images to webp 
✅ Reduce the client side rendering 
✅ Removed the background video for the /consulting pages

### On Production Slot

![image](https://github.com/user-attachments/assets/20fb0033-c3fb-4528-8da4-dffd5a3fa340)
**Figure: Home page report** 

![image](https://github.com/user-attachments/assets/41c705d0-965f-4a06-aa67-e424b0d45bf4)
**Figure: Consulting page report **

### On Staging Slot 

![image](https://github.com/user-attachments/assets/bad45327-8f83-4943-880c-7c3d10a04366)
**Figure: Home page report**

![image](https://github.com/user-attachments/assets/97a101cf-ae75-4f1b-a4a2-257268fb0b24)
**Figure: Consulting page report**

**Comment by wicksipedia** [comment]
> Converted jpg images to webp

It looks like you deleted the jpgs and replaced them with webp files. `next/image` should be able to serve webp files for us when appropriate.

This would be a better approach in case users don't support webp files

**Comment by amankumarrr** [comment]
> > Converted jpg images to webp
> 
> It looks like you deleted the jpgs and replaced them with webp files. `next/image` should be able to serve webp files for us when appropriate.
> 
> This would be a better approach in case users don't support webp files

I haven’t deleted any JPGs; I manually converted them to WebP. Since they were being served from CSS, next/image couldn't optimize them.
@wicksipedia
