### ISSUE TITLE
✨ App Routing - 📈Add telemetry for app router pages

### ISSUE THREAD

**Issue by Calinator444** [SSWConsulting/SSW.Website#3153]
CC: @wicksipedia 

### Description 

The App Router pages aren't sending Telemetry to app insights at the moment. This functionality was not added when the pages were ported. This needs to be fixed before rolling forward with the app router migration.

### Relevant routes

- /products
- /products/rewards

**Comment by Calinator444** [comment]
@wicksipedia wanted me to include some telemetry from the pages that were migrated to app routing before proceeding further. I've used `/products` as the bench mark as it is the only page that was migrated to app routing from pages routing.

## Summary

### Bounce rate: 

The bounce rate had a broader downward trend, but migrating `/products` page to app routing saw a slight improvement in this metric.

### Page Traffic: 

Page views saw a slight increase after migrating to app routing followed by a decrease in June. 

## Screenshots

**Note**: The red arrow denotes the point in time when the page was migrated to app routing
![Image](https://github.com/user-attachments/assets/dbae13fb-3f16-4168-9227-08133293d7fd)

**Figure**: **Page views over time for /products**

<br>

![Image](https://github.com/user-attachments/assets/6d163069-fa75-413a-9c49-6ae368b40122)

**Figure**: **Bounce rate for /products**

### Conclusion:
Migrating to app routing may lead to slight increases in traffic but is less significant than creating newsworthy events for SSW. For Instance, the large increase in May can likely be attributed to SSW Purchasing Tina CMS at that time. The large spike in April could also possibly be attributed to traffic following Adam's Talk at NDC Sydney.


### TODO - include App Insights logs after Aman's PR to fix this is approved

**Comment by Calinator444** [comment]
I handed this task over to @amankumarrr after moving over to rules

**Comment by amankumarrr** [comment]
✅ Done

WebVitals are being logged correctly!
![image](https://github.com/user-attachments/assets/1def7e63-8d76-44e1-932c-bc237a7a9dea)

I tested this to ensure it was sending requests to app insights in staging.

![image](https://github.com/user-attachments/assets/8737efa7-6fe3-4619-ba3b-260bb8b2a283)
