### ISSUE TITLE
♻️ App Router migration - Consulting

### ISSUE THREAD

**Issue by jeoffreyfischer** [SSWConsulting/SSW.Website#3162]
Migrating Consulting pages to App Routing.

- [x] Consulting Index 
- [x] Consulting pages 
- [x] Consulting - Video Production

**Comment by amankumarrr** [comment]
![image](https://github.com/user-attachments/assets/e9acf792-2b8c-4f40-ab77-73d319902045)

**Figure: Migrated consulting index page**

**Comment by amankumarrr** [comment]
Screenshot:
![image](https://github.com/user-attachments/assets/7b2e9e6d-aa59-4491-a6a7-3b336c1940e3)

**Figure: Migrated app routing video production page**

**Comment by amankumarrr** [comment]
Screenshot:
![image](https://github.com/user-attachments/assets/7f9de05c-b2b4-44eb-a673-255150cde1bd)
**Figure: App Routing - `Consulting/Artificial-intelligence`**



![image](https://github.com/user-attachments/assets/5aba873c-3eb2-4cb1-b749-8ac1630d4ea5)
**Figure: Before - Production slot**

![image](https://github.com/user-attachments/assets/5c9e1386-7ca6-4732-8028-12d0c0045701)
**Figure: After - PR slot**
