### ISSUE TITLE
♻️ App Router migration - Employment

### ISSUE THREAD

**Issue by jeoffreyfischer** [SSWConsulting/SSW.Website#3163]
### Acceptance Criteria
- [x] Performance for employment page is higher

![Image](https://github.com/user-attachments/assets/b31d768c-771a-4a0b-a1c8-20d209daab80)
**Figure**: **Employment page performance (mobile)**

**Comment by Calinator444** [comment]
✅ Done - Here are the new performance metrics for that page

![Image](https://github.com/user-attachments/assets/9942f7ad-03dd-4164-aa5f-bb00180e8577)
