### ISSUE TITLE
♻️ App Router migration - Events

### ISSUE THREAD

**Issue by jeoffreyfischer** [SSWConsulting/SSW.Website#3164]
- [x] migrate `/events`
- [x] migrate `/events/*`

**Comment by amankumarrr** [comment]
### ✅ Improved the past event loading time by prefetching it during build time

 Created issue to fix the client side rendering and performance - https://github.com/SSWConsulting/SSW.Website/issues/3271, I wanted to split the PR, as large PRs can lead to some other issues, once we migrate.

### On Production Slot
![image](https://github.com/user-attachments/assets/d864168c-a2f4-4911-a752-2711a681af82)
**Figure: /events page report**

![image](https://github.com/user-attachments/assets/2af73046-290f-4d5e-bcc8-9fac2d57c6d9)
**Figure: /events/ai-workshop report**


### On PR Slot
![image](https://github.com/user-attachments/assets/23b452ec-e4cb-44b4-83db-1820d95b6782)
**Figure: /events page report**

![image](https://github.com/user-attachments/assets/4072c5f3-e7f4-4491-893d-9ab4359c6983)
**Figure: /events/ai-workshop report**
