### ISSUE TITLE
♻️ App Router migration - Industry

### ISSUE THREAD

**Issue by jeoffreyfischer** [SSWConsulting/SSW.Website#3165]
- [x] Migrate `/industry` and `/industry/*` from Pages Router to App Router

![Image](https://github.com/user-attachments/assets/d8f1c61e-99fa-4f15-98e3-89d490c9226f)
**Figure: Before - [/industry/finance page performance (desktop)](https://pagespeed.web.dev/analysis/https-www-ssw-com-au-industry-finance/5p1g6187fq?form_factor=desktop)**

**Comment by babakamyljanovssw** [comment]
✅ Done - Deployed to Production

![Image](https://github.com/user-attachments/assets/7d821513-7d35-402d-b575-14bbae83c6e7)
**Figure: After - [/industry/finance page performance (desktop)](https://pagespeed.web.dev/analysis/https-www-ssw-com-au-industry-finance/ofmh7wmbfm?form_factor=desktop)**
