### ISSUE TITLE
♻️ App Router migration - Offices

### ISSUE THREAD

**Issue by jeoffreyfischer** [SSWConsulting/SSW.Website#3168]
- [x] Migrate `/offices` and `/offices/*` from Pages Router to App Router

**Comment by babakamyljanovssw** [comment]
✅ Done - Deployed to Production

![image](https://github.com/user-attachments/assets/219a4bcc-0f3d-4311-bdca-2294bbb127aa)
**Figure: Before**

![Image](https://github.com/user-attachments/assets/eefa3d4b-906a-4726-9301-a4565ae5c074)
**Figure: After**
