### ISSUE TITLE
♻️ App Router migration - Training

### ISSUE THREAD

**Issue by jeoffreyfischer** [SSWConsulting/SSW.Website#3169]
- [x] Migrate `/training/internship-fullstack` from Pages Router to App Router

![Image](https://github.com/user-attachments/assets/dc7eee62-296d-4e90-965b-4629ca3c8617)
**Figure: Before - [Training page performance (desktop)](https://pagespeed.web.dev/analysis/https-www-ssw-com-au-training-internship-fullstack/amu77az6sc?form_factor=desktop)**

**Comment by jeoffreyfischer** [comment]
Blocked by linting issue

**Comment by babakamyljanovssw** [comment]
✅ Done

![Image](https://github.com/user-attachments/assets/2b7861b5-76de-4020-9173-2583d084694c)
**Figure: After - [Training page performance (desktop)](https://pagespeed.web.dev/analysis/https-www-ssw-com-au-training-internship-fullstack/4kaq0si5rl?form_factor=desktop)**

**Comment by jeoffreyfischer** [comment]
@babakamyljanovssw investigate why Accessibility and Best Practices are lower than on /Industry page
