### ISSUE TITLE
🐛 CodeAuditor - Build failed on Rules

### ISSUE THREAD

**Issue by jeoffreyfischer** [SSWConsulting/SSW.Website#3188]
@zacharykeeping 

**Describe the bug**
As per my conversation with @tiagov8, Codeauditor is set to run weekly on rules. This week it failed
Can we avoid the same problem in the future?
Can we be warned if it ever fails again?

**To Reproduce**
N/A - it happened randomly

**Expected behavior**
The build should work

**Screenshots/Video**
![Image](https://github.com/user-attachments/assets/b195ebc0-ceea-4928-9a21-ef23ec67882a)
**Figure: The build failed last week**

**Comment by jeoffreyfischer** [comment]
This PBI was created in the wrong repo - I have moved it to: https://github.com/SSWConsulting/SSW.CodeAuditor/issues/943

**Comment by bradystroud** [comment]
> This PBI was created in the wrong repo - I have moved it to: [SSWConsulting/SSW.CodeAuditor#943](https://github.com/SSWConsulting/SSW.CodeAuditor/issues/943)

For next time, you can simply transfer the issue instead of re-creating it :)
https://docs.github.com/en/issues/tracking-your-work-with-issues/administering-issues/transferring-an-issue-to-another-repository#transferring-an-open-issue-to-another-repository
