### ISSUE TITLE
Consulting Options page: out-of-date content

### ISSUE THREAD

**Issue by leehawkinsssw** [SSWConsulting/SSW.Website#319]
On https://www.ssw.com.au/ssw/Consulting/Consulting.aspx:

1. It would be worth updating the web tech referenced on this page (currently ASP.NET MVC) to something more modern, e.g. React
2. Jason Taylor is listed as one of our experts but has left SSW. This static "Some of our experts" panel is a maintenance problem and should be dynamically loaded from current SSW people or just removed.
3. The text under "Australia Wide" reads "We have consultants available in all Australian capital cities including Sydney, Melbourne, Brisbane, Adelaide, Perth and Canberra." - is this true? It also fails to mention Newcastle.

**Comment by bradystroud** [comment]
related to #1398

**Comment by amankumarrr** [comment]
Hi @leehawkinsssw,
Already Done - page has been migrated - https://www.ssw.com.au/consulting/consulting and content was updated with this issue - https://github.com/SSWConsulting/SSW.Website/issues/1398
