### ISSUE TITLE
Web Application consulting page: broken link to SSW Rules

### ISSUE THREAD

**Issue by leehawkinsssw** [SSWConsulting/SSW.Website#320]
On https://www.ssw.com.au/ssw/Consulting/Web-Applications.aspx, the link in

Have a look at SSW Rules to Better Website Development - ASP.NET

is incorrect.

It is:

https://rules.ssw.com.au/rules-to-better-website-development-asp-net 

but should be :

https://ssw.com.au/rules/rules-to-better-website-development-asp-net/

**Comment by Harry-Ross** [comment]
Fixed by upgrade to v3 site: https://www.ssw.com.au/consulting/web-applications
