### ISSUE TITLE
Mobile Application Development consulting page: broken link to SSW Rules

### ISSUE THREAD

**Issue by leehawkinsssw** [SSWConsulting/SSW.Website#323]
On https://www.ssw.com.au/ssw/Consulting/Mobile-Application-Development.aspx, the link in

Have a look at SSW Rules to Better Mobile Apps.

is incorrect.

It is:

https://www.ssw.com.au/rules/rules-to-better-apps

but should be :

https://www.ssw.com.au/rules/rules-to-better-apps-mobile/

**Comment by bradystroud** [comment]
Thanks @leehawkinsssw 
Already done  - fixed when the page was migrated to the new site 🙂 (not added to a Sprint)
