### ISSUE TITLE
SSW Products page: link to Legacy Products is broken

### ISSUE THREAD

**Issue by leehawkinsssw** [SSWConsulting/SSW.Website#324]
On https://www.ssw.com.au/ssw/Products/Default.aspx, the link to "Legacy Products" at the bottom of the page is broken. 

It tries to load https://www.ssw.com.au/ssw/Products/Legacy.aspx which doesn't exist.

**Comment by wicksipedia** [comment]
Closing as the page in question (old website) has been replaced and the link in question no longer exists on the new page
