### ISSUE TITLE
🐛JotForm - Get Page URL is too long for CRM Flow

### ISSUE THREAD

**Issue by amankumarrr** [SSWConsulting/SSW.Website#3267]
@bradystroud 
**Describe the bug**
As per email with the subject "⚠️URGENT - Create lead in CRM flow failed - JotForm ", our CRM tend to fail when it provides URL with additional query params when it is longer than 200 characters.

- [x]  Trim the query params until it fits into in 200 characters.

**Comment by amankumarrr** [comment]
As per my conversation with @wicksipedia, we don't need to save query params and will only keep the urls.

**Comment by amankumarrr** [comment]
✅ Issue has been resolved. Now, we are trimming the url and only keeping the useful part of it.

![Image](https://github.com/user-attachments/assets/5fa4f9c2-fb92-4b40-89cc-060be63692bc)
**Figure: Test lead generated with the long query param**

**Comment by jeoffreyfischer** [comment]
Reopening this issue as we have just received an email about the same issue
>⚠️URGENT - Create lead in CRM flow failed - JotForm 

- [ ]  Investigate and fix

**Comment by Calinator444** [comment]
This is failing for a separate reason, a perspective client (who I won't name) added a phone number that was too long for the workflow. I will fix this by adding validation to the jotform

![Image](https://github.com/user-attachments/assets/5cd88afd-3aa8-493d-9824-aff1ca737444)
**Figure**: **Error message on failed workflow run**

**Comment by Calinator444** [comment]
✅Done I've set the maximum character length to **20** on the initial meeting form

The inputs shouldn't cause the workflow to fail anymore

![Image](https://github.com/user-attachments/assets/7d4cf7d1-d153-49a3-8fea-cad93b1a9e1e)
