### ISSUE TITLE
Sydney .NET User Group: link issues

### ISSUE THREAD

**Issue by leehawkinsssw** [SSWConsulting/SSW.Website#330]
On https://www.ssw.com.au/ssw/NETUG/Sydney.aspx, there are two link issues:

1. Under "Why - 3 Great Reasons to Attend The .NET User Group", the "spell this the American way" link goes to the non-specific https://www.ssw.com.au/SSW/Standards/Rules/RulesToBetterGoogleRankings.aspx#OnPage - it would be better to link directly to the spelling rule, https://ssw.com.au/rules/spelling-do-you-use-us-english/
2. At the bottom of the page, the "Join our Sydney UG Linkedin" link (https://www.ssw.com.au/ssw/Redirect/SSWLinkedinGroup.htm) doesn't in fact go to the Sydney UG LinkedIn group page.

**Comment by Harry-Ross** [comment]
Fixed by https://github.com/SSWConsulting/SSW.Website/pull/1459
