### ISSUE TITLE
✨ Develop the Cards Carousel Component

### ISSUE THREAD

**Issue by bettybondoc** [SSWConsulting/SSW.Website#3319]
cc @wicksipedia @isaaclombardssw @UlyssesMaclaren @adamcogan @miichaelsmedley @louisroa8189 

**Description**
Create the Cards Carousel component for the Consulting Pages. This component should allow users to display cards in either a stacked layout or a scrolling carousel. Users should have customization options for card content, categories, and grouping.

**Acceptance Criteria:**

- The Cards Carousel component includes the following customization options:

>   - Layout Selector: Stacked, Carousel
>   - Background Selector: Transparent, Grey-700, Gradient 1/2/3/4
>   - Heading Text Field
>   - Description Text Field
>   - Button 1 & Button 2
>     - Before Icon Selector
>     - Text Field
>     - After Icon Selector
>     - Style Selector (Primary, Secondary)
>   - Groupings:
>     - Category Text Field (Per Item)
>     - Drag-and-drop functionality for assigning cards to categories
>   - Cards (Repeatable):
>     - Style Selector (Default, No Border)
>     - Image File Uploader
>     - Label 1 & Label 2
>     - Icon Selector
>     - Heading Text Field
>     - Description Text Field
>     - List (Repeatable):
>       - Icon Selector
>       - Text Field
>     - Button Text Field, Link, and Icon

- Users are allowed to create categories and assign a card to a category 
- Fully responsive across desktop, tablet, and mobile
- Works seamlessly on all major browsers (Chrome, Firefox, Safari, Edge)
- Fields and sections can be enabled or disabled for flexibility
- The UI for customization options is grouped logically for ease of use (e.g., card settings, category grouping).
- Code is ready for theming (e.g., Light/Dark modes, custom colors – [see linked PBI](https://github.com/SSWConsulting/SSW.Website/issues/3300))
- Tested and approved by Wicksy, Louis, and Betty

**Tasks**
- [ ] TODO - Developer to update

![Image](https://github.com/user-attachments/assets/4d35c82c-d9e2-4649-a838-5fa2f4aa6010)
**Figure: Component - Carousel - Desktop**

![Image](https://github.com/user-attachments/assets/58372046-979b-48a3-affe-92b57f752ebc)
**Figure: Component - Stacked - Desktop**

![Image](https://github.com/user-attachments/assets/6bc04ba6-ef9d-483a-90ca-b94d0a1c414c)
**Figure: Component - Carousel - Mobile**

![Image](https://github.com/user-attachments/assets/b027e256-90df-43e8-8fde-669acdb54acd)
**Figure: Use Case - Client Stories**

![Image](https://github.com/user-attachments/assets/145e1397-d31b-4361-859c-b1415464eb84)
**Figure: Use Case - Related Tech**

**Comment by Calinator444** [comment]
This isn't done yet:

- the carousel buttons still need to be bound to the items
- the width of the carousel items still needs to be adjusted so that we have 3 cards on the screen at any given time

![Image](https://github.com/user-attachments/assets/fa699ab8-7437-4820-a829-bca02ac4d6d3)

**Comment by Calinator444** [comment]
Louis would like a black background for the consulting page components to take advantage of the bleed effect.

**Comment by isaaclombardssw** [comment]
This is complete alongside the other component's

It has been test passed by Louis. Check out the done video for a demo :)

**Comment by isaaclombardssw** [comment]
See our done video for more details – https://www.youtube.com/watch?v=YWSE8qX30Vw
