### ISSUE TITLE
✨ Related Technology Global Setup

### ISSUE THREAD

**Issue by bettybondoc** [SSWConsulting/SSW.Website#3320]
cc @wicksipedia @isaaclombardssw @UlyssesMaclaren @adamcogan @miichaelsmedley @louisroa8189 

**Description:**
Create a global setup feature where users can add, edit, and manage all related technologies in one central location. These technologies can then be referenced in the Card Component, allowing users to select pre-defined technologies as content. This setup ensures content consistency across pages and enables centralized updates, so any changes made to a technology are reflected globally.

**Acceptance Criteria**
- The global technology setup includes the following functionality:

>   - A centralized interface to add, edit, and delete technology entries.
>   - Each technology entry includes:
>     - Technology Name (Text Field).
>     - Description (WYSIWYG or Text Field).
>     - Icon Selector (from a pre-defined library).
>     - Optional Link Field (e.g., documentation or external resources).
>     - Image Uploader/Selector
> 
> - In the Card Component:
>   - Users can select pre-defined technologies from the global setup as content for the card.
>   - The selected technology’s content (name, description, icon, link, image) is displayed in the Card Component.
>   - Changes made to a technology in the global setup are automatically reflected in all associated Card Components.

- Fully responsive across desktop, tablet, and mobile
- Works seamlessly on all major browsers (Chrome, Firefox, Safari, Edge)
- Code is ready for theming (e.g., Light/Dark modes, custom colors – see linked PBI: https://github.com/SSWConsulting/SSW.Website/issues/3300)
- Tested and approved by Wicksy, Louis, and Betty
- Documentation is provided, including:
  - Steps to set up and manage global technologies
  - Examples of referencing technologies in the Card Component
  - Guidance on content updates and their global impact

**Tasks:**
- [ ] TODO - Developer to update

**Comment by jeoffreyfischer** [comment]
⚠️ Note: This new component is a wrapper around the card component - it uses the existing technology data.
A clean-up might be necessary

**Comment by Calinator444** [comment]
We have an existing technology field schema


Here's a list of fields that we have already:
- Technology Name (Text Field)
- Description (WYSIWYG or Text Field)
- Image Uploader/Selector (has a thumbnail field)
- Optional Link Field ("readMoreSlug", It should probably be renamed if we're allowing absolute URLs)


The only field we need is:
- Icon Selector (from a pre-defined library).

**Comment by Calinator444** [comment]
Not done yet - I've set up the schema for the global card's component but haven't set up the component yet.

**Comment by Calinator444** [comment]
I've set up the schema for the technology card carousel and created a component that massages the data into the existing card carousel component. I haven't tested it though.

I won't be able to finish this because I'll be on leave for a couple of weeks. Here's the branch with my changes
https://github.com/SSWConsulting/SSW.Website/tree/3320-related-technology-global-setup

**Comment by isaaclombardssw** [comment]
✅ Done - This is complete, a related technologies v2 schema ("global" data) has been created and seeded with the old related tech data. As per my conversation with Louis, he wants to go through those and organise them.

A new block has also been created which branches off the card component and reads the technology data.

**Comment by isaaclombardssw** [comment]
### Screenshots of the Tina Editor and UI

![Image](https://github.com/user-attachments/assets/c81d3d60-2eed-4326-bc12-50aa6b00a90f)
![Image](https://github.com/user-attachments/assets/b287580d-57a4-4d7d-85ad-dcaf93551aaf)
![Image](https://github.com/user-attachments/assets/947e4131-349b-4592-9074-ea7f571f3a1d)
![Image](https://github.com/user-attachments/assets/3bb4a2a6-6f7f-4d9a-95aa-e6e793928804)
