### ISSUE TITLE
✨ Develop the Accordion Block Component

### ISSUE THREAD

**Issue by bettybondoc** [SSWConsulting/SSW.Website#3321]
cc @wicksipedia @isaaclombardssw @UlyssesMaclaren @adamcogan @miichaelsmedley @louisroa8189 

**Description**
Create the Accordion Block component for the Consulting Pages. This component should allow users to present information in an accordion format with customization options for layout, styling, and content. The component should support multiple or single accordion item behavior and prioritize usability, flexibility, and accessibility.

**Acceptance Criteria:**
- The Accordion Block component includes the following customization options:
> - Layout Selector:
>     - No Image
>     - Image-Accordion
>     - Accordion-Image
>   - Background Selector:
>     - Transparent
>     - Grey-700
>     - Gradient 1/2/3/4
>   - Image File Uploader
>   - Heading Text Field
>   - Description Text Field
>   - Button 1 & Button 2:
>     - Before Icon Selector
>     - Text Field
>     - After Icon Selector
>     - Style Selector (Primary, Secondary)
>   - Accordion Item (Repeatable):
>     - Item Heading Text Field
>     - Item Body WYSIWYG
>     - Behavior:
>       - Multiple Open
>       - Single Open

- Fully responsive across desktop, tablet, and mobile
- Works seamlessly on all major browsers (Chrome, Firefox, Safari, Edge)
- Fields and sections can be enabled or disabled for flexibility
- The UI for customization options is grouped logically for ease of use (e.g., button settings grouped together)
- Code is ready for theming (e.g., Light/Dark modes, custom colors – see linked PBI: https://github.com/SSWConsulting/SSW.Website/issues/3300)
- Tested and approved by Wicksy, Louis, and Betty

**Tasks:**
- [ ] TODO - Developer to update

![Image](https://github.com/user-attachments/assets/9f3338db-4302-4881-bcf9-28efc0725e7e)
**Figure: Component - Desktop**

![Image](https://github.com/user-attachments/assets/5b735042-6304-4221-9882-d783ee616b6f)
**Figure: Component - Mobile**

![Image](https://github.com/user-attachments/assets/45f0346c-a2d6-4cd5-83c3-843f57f2d07e)
**Figure: Use Case - FAQ**

![Image](https://github.com/user-attachments/assets/8c26a752-176a-4469-b098-27f32d118372)
**Figure: Use Case - Steps**

**Comment by isaaclombardssw** [comment]
Effectively done – waiting for merge of Image Text cause I'm using some shared components

**Comment by isaaclombardssw** [comment]
Check out the staging branch at #3371 :)

**Comment by Calinator444** [comment]
See status update

https://github.com/SSWConsulting/SSW.Website/issues/3316#issuecomment-2518681507

**Comment by isaaclombardssw** [comment]
See our done video for more details – https://www.youtube.com/watch?v=YWSE8qX30Vw
