### ISSUE TITLE
🐛Deployment Pipeline - App Insights preventing new builds from being created

### ISSUE THREAD

**Issue by Calinator444** [SSWConsulting/SSW.Website#3359]
(Adding this because the bug is blocking us from shipping the new consulting page)

### Description
There's a bug in our deployment related to App insights that is preventing us from making new deployments.

### Todo 
- [x] Investigate
- [x] Fix

![Image](https://github.com/user-attachments/assets/56ca02af-4d8c-494d-a15c-9ac032b07760)

**Comment by Calinator444** [comment]
Done - I fixed and deployed the dependabot upgrade for app insights. We're able to deploy branches with new dependencies now.


https://github.com/SSWConsulting/SSW.Website/pull/3299

**Comment by jeoffreyfischer** [comment]
@Calinator444  TODO: document how this was fixed in the wiki
