### ISSUE TITLE
🐛 Eslint breaking our builds

### ISSUE THREAD

**Issue by Calinator444** [SSWConsulting/SSW.Website#3382]
### Description

Next.js is performing it's own listing check for the website at build time which does not align with the linting check in our pipeline. As a result we cannot merge any PRs right now because both linting checks have separate criteria.

Todo:
- [ ] Update the linting check for the website to align with Next.js' linting check

![Image](https://github.com/user-attachments/assets/7475c1f9-ead1-4382-9426-acf6c4146252)

**Comment by Calinator444** [comment]
✅Done - The linting check for Next.js is still different inside of our docker image for building the website than the docker image that runs the linting check.

For now we've updated the website's linter to use Next.js' configuration and disabled the check for Next.js builds in our pipeline so that we can create new releases. 

https://nextjs.org/docs/app/api-reference/config/eslint

**Comment by jeoffreyfischer** [comment]
✅ Done - TODO @Calinator444

**Comment by babakamyljanovssw** [comment]
cc: @wicksipedia @jeoffreyfischer @Calinator444 @isaaclombardssw 

I am re-opening this issue as this linting errors are seen in the pipeline

**Comment by Calinator444** [comment]
I believe I discovered the root cause of the issue. the ubuntu latest image we use to lint the website was recently updated to use the latest version of Node.js. Eslint behaves differently depending on which version of Node.js it uses (i.e. running the lint on node v20 behaves differently to node v22).


https://github.com/actions/runner-images/issues/10636
