### ISSUE TITLE
✨ Open Graph - Add default OG image for consulting pages

### ISSUE THREAD

**Issue by bradystroud** [SSWConsulting/SSW.Website#410]
cc: @tiagov8 @camillars @antonvojkovicssw 

**Is your feature request related to a problem? Please describe.**

Our consulting pages have the ability to set custom OG content for each page.
This is a cool feature, but when there is no content set, it doesnt look great. 

https://opengraph.dev/panel?url=https%3A%2F%2Fwww.ssw.com.au%2Fconsulting%2Fblazor
![image](https://user-images.githubusercontent.com/38869720/225153977-be63f223-556c-4b84-be65-aafc464840bb.png)
**Figure: No OG images set on the Blazor consulting page😕**

**Describe the solution you'd like**
When there is no image set for the page, show a generic consulting image
This could probably be set through tina in the global settings.

**Comment by tiagov8** [comment]
cc @Geordie88 

Hi @bradystroud 

FYI - We have a generic Open Graph image https://www.ssw.com.au/ssw/images/SSW-og.jpg 

...but Blazor (and most of consulting pages) has its own: https://www.ssw.com.au/SSW/Consulting/Images/open-graph/SSW-Consulting-Blazor-og.jpg 


1. Please implement all the custom ones (https://sswcom.sharepoint.com/:f:/r/sites/SSWDESIGN/Shared%20Documents/General/2-SSW-Marketing-Social-Media/LinkedIn/OpenGraph-thumbnails/exported?csf=1&web=1&e=pDVNq6)
2. Apply the generic one for other pages
