### ISSUE TITLE
✨ Open Graph - Support Twitter

### ISSUE THREAD

**Issue by bradystroud** [SSWConsulting/SSW.Website#413]
**Is your feature request related to a problem? Please describe.**

https://opengraph.dev/panel?url=https%3A%2F%2Fwww.ssw.com.au%2F
![image](https://user-images.githubusercontent.com/38869720/225157414-aab2827e-2970-49a8-b0e2-954573d104ee.png)
**Figure: No Twitter image or title**

**Describe the solution you'd like**
```[tasklist]
### Tasks
- [ ] Support twitter on all pages
```

**Comment by Harry-Ross** [comment]
The `next-seo` package doesn't support Twitter tags as Twitter now uses OpenGraph. As per: https://www.npmjs.com/package/next-seo#twitter. 

![Image](https://user-images.githubusercontent.com/20507092/226796754-487eb24b-0871-42a4-847d-c196960de5fe.png)

**Figure: Working OpenGraph tags with Twitter**

All the available Twitter tags are properly provided in `next-seo-config.ts` and `seo.tsx`.
