### ISSUE TITLE
❌ - Bug - Weird characters on job descriptions

### ISSUE THREAD

**Issue by piers-sinclair** [SSWConsulting/SSW.Website#419]
@BrookJeynes @bradystroud @tkapa @wicksipedia @johnxu77 @jimmidier @Harry-Ross @adamcogan 

**Is your feature request related to a problem? Please describe.**
On the SSW employment page, the job descriptions have weird characters.
https://www.ssw.com.au/ssw/Employment/

1.	Please fix.

**Describe the solution you'd like**
No weird characters

**Describe alternatives you've considered**
N/A - It's a bug

**Additional context**
![image](https://user-images.githubusercontent.com/79821522/225523774-f2e4464a-370c-4510-8784-439dca9c1814.png)
**Figure: Weird characters on job description**

**Comment by wicksipedia** [comment]
This is on the old website (not v3)

@tiagov8 - can you update it

**Comment by tiagov8** [comment]
Done - https://www.ssw.com.au/ssw/Employment/
