### ISSUE TITLE
✨ SSW Employment Jobs - Should be able to direct link to them

### ISSUE THREAD

**Issue by piers-sinclair** [SSWConsulting/SSW.Website#421]
@BrookJeynes @bradystroud @tkapa @wicksipedia @johnxu77 @jimmidier @Harry-Ross @adamcogan

**Is your feature request related to a problem? Please describe.**
On https://www.ssw.com.au/ssw/Employment/

I can see a bunch of jobs if I scroll down. However, this is very hidden. In particular, if I want to send a specific job to someone, I have no way to do that with the current system.

**Describe the solution you'd like**
Each job should have it's own page. Then I can directly link it to someone who might be ineterested.

**Describe alternatives you've considered**
Sending a link to a LinkedIn job posting, it's hard to find, intuitive and may not include all jobs. Furthermore, some jobs are on Seek.

**Comment by amankumarrr** [comment]
Hi @pierssinclairssw 

As per my conversation with @bradystroud, @Harry-Ross and @KristenHu, to make this easier, We'll add links to each opportunity and a handy button for users to copy the link. If a specific ID is in the URL, the webpage will automatically scroll to that opportunity. Please let us know your thoughts on it

**Comment by amankumarrr** [comment]
@pierssinclairssw @wicksipedia @bradystroud 

We have implemented auto-scrolling and auto collapsed if the URL contains that specific id 

![F72D1A84-4C76-454D-AD1E-21EC90EA6415](https://github.com/SSWConsulting/SSW.Website/assets/71385247/69f977f9-ebdb-4bc7-b992-e563497c1003)
**GIF: Auto-scrolling to the position defined in the URL**
