### ISSUE TITLE
🐛 MegaMenu - Update links to NextJs pages

### ISSUE THREAD

**Issue by bradystroud** [SSWConsulting/SSW.Website#424]
cc @jontygardner @tkapa 

**Is your feature request related to a problem? Please describe.**
The MegaMenu links to the old website

**Describe the solution you'd like**

```[tasklist]
- [ ] Check with @wicksipedia then change the links to go to our shiny new website
```

**Comment by Harry-Ross** [comment]
Closing as duplicate of #263
