### ISSUE TITLE
💸 Tech Debt - Events data

### ISSUE THREAD

**Issue by bradystroud** [SSWConsulting/SSW.Website#51]
Our events data is stored in Sharepoint. 
To get the data, we are using a service on the old website.

https://github.com/SSWConsulting/SSW.Website-v3/blob/396840ab8ed33f1edac6bfa2806891aaf61f843a/components/blocks/upcomingEvents.tsx#L33

```[tasklist]
### Tasks
- [ ] Discuss and decide how to remove the dependency on the old website
- [ ] Implement the new method of getting events data
```

As per our conversation, this should probably be an Azure function or Logic App that gets the data from sharepoint.

Multiple endpoints:
- Get list of events
- Get next event (for live banner)
- Get list of events + details (for search)

**Comment by Harry-Ross** [comment]
https://dev.azure.com/ssw2/SSW.Website/_versionControl?path=%24/SSW.Website/trunk/SSW.Website.WebUI/SharePointEventsService.aspx.cs
