### ISSUE TITLE
🔗 URL fix: Remove /Training from SSW events page's URL

### ISSUE THREAD

**Issue by hveraus** [SSWConsulting/SSW.Website#522]
As per conversation with Camilla, please remove /Training from SSW events page's URL

**From:**

https://www.ssw.com.au/ssw/Events/Training/Angular-Superpowers-Tour.aspx
https://www.ssw.com.au/ssw/Events/Training/Azure-Superpowers-Tour.aspx
https://www.ssw.com.au/ssw/Events/Training/Clean-Architecture-Workshop.aspx
https://www.ssw.com.au/ssw/Events/Training/NET-Superpowers-Tour.aspx
https://www.ssw.com.au/ssw/Events/Training/Azure-Superskills.aspx
https://www.ssw.com.au/ssw/Events/Training/Angular-Workshop.aspx
https://www.ssw.com.au/ssw/Events/Training/Clean-Architecture-Workshop.aspx

**To:**

https://www.ssw.com.au/Events/Angular-Superpowers-Tour.aspx
https://www.ssw.com.au/Events/Azure-Superpowers-Tour.aspx
https://www.ssw.com.au/Events/Clean-Architecture-Workshop.aspx
https://www.ssw.com.au/Events/NET-Superpowers-Tour.aspx
https://www.ssw.com.au/Events/Azure-Superskills.aspx
https://www.ssw.com.au/Events/Angular-Workshop.aspx
https://www.ssw.com.au/Events/Clean-Architecture-Workshop.aspx

**Comment by hveraus** [comment]
Also added a note to Events epic story - https://github.com/SSWConsulting/SSW.Website-v3/issues/528

Remove this PBI if done

**Comment by KristenHu** [comment]
Done - The URLs have been updated


![Image](https://github.com/SSWConsulting/SSW.Website/assets/52522913/ee7d6d28-1c83-4326-bcc2-8e2ab77a7b73)
