### ISSUE TITLE
Epic - Events

### ISSUE THREAD

**Issue by wicksipedia** [SSWConsulting/SSW.Website#528]
[Event listing](https://www.ssw.com.au/ssw/Events/?tech=all&type=all) 
[User groups](https://www.ssw.com.au/ssw/NETUG/Sydney.aspx) - PBI #997 
[Superpowers](https://www.ssw.com.au/ssw/Events/training/azure-superskills.aspx)

**Comment by hveraus** [comment]
As per my conversation with Matt, please remove /Training from SSW events page's URL when migrating events pages

**Change the URLs From:**
https://www.ssw.com.au/ssw/Events/Training/Angular-Superpowers-Tour.aspx
https://www.ssw.com.au/ssw/Events/Training/Azure-Superpowers-Tour.aspx
https://www.ssw.com.au/ssw/Events/Training/Clean-Architecture-Workshop.aspx
https://www.ssw.com.au/ssw/Events/Training/NET-Superpowers-Tour.aspx
https://www.ssw.com.au/ssw/Events/Training/Azure-Superskills.aspx
https://www.ssw.com.au/ssw/Events/Training/Angular-Workshop.aspx
https://www.ssw.com.au/ssw/Events/Training/Clean-Architecture-Workshop.aspx

**To:**
https://www.ssw.com.au/Events/Angular-Superpowers-Tour.aspx
https://www.ssw.com.au/Events/Azure-Superpowers-Tour.aspx
https://www.ssw.com.au/Events/Clean-Architecture-Workshop.aspx
https://www.ssw.com.au/Events/NET-Superpowers-Tour.aspx
https://www.ssw.com.au/Events/Azure-Superskills.aspx
https://www.ssw.com.au/Events/Angular-Workshop.aspx
https://www.ssw.com.au/Events/Clean-Architecture-Workshop.aspx

**Comment by wicksipedia** [comment]
closing as done
