### ISSUE TITLE
✨ Move hard-coded client logos to Tina schema

### ISSUE THREAD

**Issue by BrookJeynes** [SSWConsulting/SSW.Website#547]
Currently the client logos are hard-coded. These should be moved to the Tina config

![image](https://user-images.githubusercontent.com/25432120/233898015-50d891d6-080e-405c-84c5-099c4ffc7fc2.png)
**Figure: `components/blocks/clientLogos.tsx` Hard-coded values**

**Comment by PothieuG** [comment]
- The feature is ready for review.
