### ISSUE TITLE
💸 Tech Debt - Newsletter process

### ISSUE THREAD

**Issue by bradystroud** [SSWConsulting/SSW.Website#575]
**Description**  
Right now the process for adding newsletters is painful and there is lots of room for error.

TODO: Outline current process

There are lots of historical newsletters and assosiated images in this repo, these take up lots of space and make the project heavy.

**Proposed solution**  
Find a tool to better manage newsletters.

- Creating newsletters shouldn't need HTML and CSS skills
- Ideally, we wouldn't need to upload the newsletter and all the images here

**Comment by wicksipedia** [comment]
Closing as stale and newsletter support has been implemented
