### ISSUE TITLE
💸 Tech Debt - Client logos are hard-coded

### ISSUE THREAD

**Issue by BrookJeynes** [SSWConsulting/SSW.Website#583]
**Description**  
Currently the client logos are hard-coded.

```ts
// components/blocks/clientLogos.tsx

const clients = {
    "allianz": "allianz.jpg",
    "carnival": "carnival.jpg",
    "cisco": "cisco.jpg",
    "commonwealthbank": "commbank.jpg",
    "symantec": "symatec.jpg",
    "domain": "domain.jpg",
    "eventcinemas": "events.jpg",
    "microsoft": "microsoft.jpg",
    "toll": "toll.jpg",
};
```

**Proposed solution**  
These should instead be passed in via the Tina config so they can be dynamically changed.

**Comment by PothieuG** [comment]
Duplicate with this one:  https://github.com/SSWConsulting/SSW.Website-v3/issues/547
I move it to "Need Triage"
