### ISSUE TITLE
📄 Events - .NET Superpowers

### ISSUE THREAD

**Issue by bradystroud** [SSWConsulting/SSW.Website#596]
https://www.ssw.com.au/ssw/Events/Training/NET-Superpowers-Tour.aspx

As per my conversation with @camillars and @bradystroud , we think all SuperPower pages should be under the route of /events and Internship will remain under /training and remove all the content related to COVID on the page. 
```[tasklist]
### Tasks
- [x] Migrate pages
- [x] Update MegaMenu
- [x] Add redirect (blocked by #1087)
```

**Comment by KristenHu** [comment]
1. Migrate pages
**Done** - https://github.com/SSWConsulting/SSW.Website/pull/1126

2. Update MegaMenu
**Done** - https://github.com/SSWConsulting/SSW.Website.Menu.json/pull/89

3. Add redirect (blocked by https://github.com/SSWConsulting/SSW.Website/issues/1087)
**Done** - https://github.com/SSWConsulting/SSW.FrontDoor/pull/78
