### ISSUE TITLE
What do people say | missing a sentence under the title

### ISSUE THREAD

**Issue by bradystroud** [SSWConsulting/SSW.Website#604]
~~@BrookJeynes please give this a decription~~ - Done

As per the figma design, the "What do people say" section should have some text below the header.

![image](https://github.com/SSWConsulting/SSW.Website-v3/assets/25432120/276cb8c2-7331-4f20-a6b4-a330861fbfb7)
**Figure: Design from Figma board**

**Comment by jackreimers** [comment]
@bradystroud any idea what the text should actually say?

**Comment by bradystroud** [comment]
> @bradystroud any idea what the text should actually say?

Come up with something yourself or generate it.
Get it checked by Penny or Piers

**Comment by jackreimers** [comment]
As per my conversation with @UlyssesMaclaren, the consulting pages will not have a tagline as they do not add any additional context to the component.
