### ISSUE TITLE
Products Page

### ISSUE THREAD

**Issue by KristenHu** [SSWConsulting/SSW.Website#606]
Migrate the products index page to `/products`

~Products page in  SSW.Website-v1 has a section named Legacy Products, but it has already been deleted.~

- [x] Investigate if there's a new legacy product page
- [ ] If there's no such page, check if it should be added
 

![Image](https://user-images.githubusercontent.com/52522913/237021080-3b84c6a9-2f80-467b-a71c-55bb0965005a.png)
_Figure - old product page_

![Image](https://user-images.githubusercontent.com/52522913/237021240-7baf9168-b309-4e4d-8d44-b9f6a7c462cf.png)
_Figure - old product legacy page_

**Comment by bradystroud** [comment]
As per my conversation with @wicksipedia lets remove the Leagcy Products link

**Comment by bradystroud** [comment]
Closing this as the work is done
https://ssw.com.au/products
