### ISSUE TITLE
Newsletters - Upload file feature on TinaCMS

### ISSUE THREAD

**Issue by PothieuG** [SSWConsulting/SSW.Website#626]
We would like Penny to have as little action as possible to upload the new newsletters.
Currently, she has to enter newsletter information in TinaCMS (file name, month...), but she also has to manually add the HTML file to the public/newsletters/[year] folder.

Using TinaCMS's Media Manager does not meet our needs as any uploaded file will always be placed in the root of the /public folder.
An issue is currently open on the TinaCMS repository to address this : https://github.com/tinacms/tinacms/issues/3813

In the meantime, until we can utilize an internal feature within TinaCMS, we need to find another way to make Penny's work easier.  

1. go to http://localhost:3000/admin/index.html#/collections/newsletters | any json file
2. create a upload feature that would put the selected file on the right spot : public/newsletters/[the years related to json file name]
3. listing the file currently on the folder
4. let user delete a file if necessary

**Comment by PothieuG** [comment]
Currently, I have implemented a custom feature that includes the following functionality:
- Listing all newsletters in a folder
- Uploading a file to the current folder
- Deleting a file from the current folder

However, my main concern is that I am utilizing Next.js API routes for the upload and delete actions, which makes these routes insecure and accessible to anyone. I need to find a solution to make these routes secure.

**Comment by PothieuG** [comment]
- There has been no progress on this matter. Penny will have to continue manually uploading newsletters to the Git repository and making manual modifications in the CMS until an efficient way to upload documents via TinaCMS is found.
- Documentation should be created on this topic, and a video should be recorded demonstrating the functionality with Penny.

**Comment by bradystroud** [comment]
As per my conversation with @Harry-Ross the auth doesn't matter because its going through the git PR process.
The upload process needs to follow the same git process as Tina. This should be possible with 

https://tina.io/docs/reference/media/external/authentication/
and 
https://tina.io/docs/extending-tina/custom-field-components/


![Image](https://github.com/SSWConsulting/SSW.Website/assets/38869720/040dbc6d-4dc1-4269-bb80-4fef0c38794f)
**Figure: Notes from our discussion**

**Comment by Harry-Ross** [comment]
Currently, I have implemented a custom Tina component for file uploading:


![Image](https://github.com/SSWConsulting/SSW.Website/assets/20507092/4d3986b7-5ada-4b45-9ea2-3ae1e137b5ce)
**Figure: Custom Tina field with file upload - uses media manager to upload files to Tina Cloud uploads folder**

* Allows uploading of files of any file type using the `useCMS` hook
* Saves the file as a string path in the collection file

This uses a lot of undocumented Tina features, so is likely not the ideal solution to the problem. 

However, upon adding a `type: "image` field to the collection, I have found it is possible to upload HTML files through the image component, which may mean that the custom file upload component is not necessary.
