### ISSUE TITLE
📄 Consulting page index - correct miss placed tags

### ISSUE THREAD

**Issue by hveraus** [SSWConsulting/SSW.Website#642]
URL: https://www.ssw.com.au/consulting

As per conversation with Uly @UlyssesMaclaren , I need to:

- [x] Fix miss placed tags, e.g. Bots and Database dev pages show up under Website development
- [x] Add a new filter "AI Development", tag GPT and AI&Machine Learning pages
- [x] Change the tag name from “Consulting” to “Other SSW Services” and move it to the bottom
- [x] "Platform" tag seems missing, add it back

**Comment by amankumarrr** [comment]
#2 and #3 tasks seem like not accomplished, needs to be redone.


![Image](https://github.com/SSWConsulting/SSW.Website-v3/assets/71385247/2e1001a7-a951-43b4-9831-705c05797fe5)

 **Figure: Showing ChatGPT missing and Other SSW Services placement in middle**
