### ISSUE TITLE
📄 Consulting Index - Change the order of Left-Sidebar filter list

### ISSUE THREAD

**Issue by hveraus** [SSWConsulting/SSW.Website#650]
URL: https://www.ssw.com.au/consulting

**From:**

Order of Left-Sidebar filter list:
- Website Development
- Application Development
- Mobile Development
- Database Development
- Other SSW Services
- AI Development
- Design
- Video
- Platform Development
- Content Management Systems (CMS)
- Cloud and Infrastructure

**To:**

 Order of Left-Sidebar filter list:
- AI Development
- Website Development
- Application Development
- Mobile Development
- Database Development
- Platform Development
- Design
- Content Management Systems (CMS)
- Cloud and Infrastructure
- Video
- Other SSW Services

**Screenshots**
<img width="1261" alt="image" src="https://github.com/SSWConsulting/SSW.Website-v3/assets/4745861/c3883fd8-095d-44bb-b995-4425054a0003">

**Comment by Harry-Ross** [comment]
Should the "AI Development" group be moved above "Development Teams" in the main part of the page as well?

**Comment by amankumarrr** [comment]
Hi @hveraus,

We can reorder the sidebar by simply drag and drop, could you please try it using Tina, let me know if you need help.


![Image](https://github.com/SSWConsulting/SSW.Website/assets/71385247/f33a2a7b-8b61-4b69-807c-ec7350b3593b)

**Figure: Draggable sidebar in Tina CMS**
