### ISSUE TITLE
🐛 Pipeline - Yarn Build is not working 

### ISSUE THREAD

**Issue by amankumarrr** [SSWConsulting/SSW.Website#661]
**Describe the bug**
Since this morning, yarn build is failing due to Page.breadcrumb issue in graphQl.

**To Reproduce**
Run: `yarn build`

```[tasklist]
### Tasks
- [x] fix the issue
- [x] Investigate or follow up with Tina Discord for that issue

**Screenshots/Video** <img width="521" alt="MicrosoftTeams-image" src="https://github.com/SSWConsulting/SSW.Website-v3/assets/71385247/ad839dbb-196c-438a-af5a-fc792ede922d">
**Figure: Error in our pipeline during yarn build** <img width="1682" alt="MicrosoftTeams-image (1)" src="https://github.com/SSWConsulting/SSW.Website-v3/assets/71385247/dcad4c88-e8e1-41b9-b72f-82ca268f71a0">
Figure: Someone posted a same error on Tina Discord this morning
```

**Comment by amankumarrr** [comment]
Reopening this issue to follow up with Tina Discord's post as @bradystroud has left a comment and we might hear back from Tina if there is any update on it.

**Comment by bradystroud** [comment]
Cc @amankumarrr 

The Tina team fixed the bug! 
We could revert out workaround (#662) but I dont think it will have any effect.

![image](https://github.com/SSWConsulting/SSW.Website-v3/assets/38869720/6b1c8721-e8cf-4fbf-a4d1-7e372d89654c)
**Figure: TinaCMS fixed the bug 🚀**
