### ISSUE TITLE
📄 Test practice fixes

### ISSUE THREAD

**Issue by bradystroud** [SSWConsulting/SSW.Website#693]
URL: 
- www.ssw.com.au/consulting/test-practice
- https://ssw.com.au/consulting/alm-azure-devops

```[tasklist]
### Tasks
- [x] Find out wherever we are using this image and see if it works there
- [x] Fix broken image
```

![image](https://github.com/SSWConsulting/SSW.Website-v3/assets/38869720/6abfb973-5274-44ae-a503-5130d04aa525)
**Figure: Image not loaded correctly on the Test Practice consulting page**

**Comment by amankumarrr** [comment]
@bradystroud it is also broken on https://ssw.com.au/consulting/alm-azure-devops with the same image. 
<img width="948" alt="image" src="https://github.com/SSWConsulting/SSW.Website-v3/assets/71385247/ddc49d64-7381-4b05-a998-f3f897c89c8e">
**Figure: Image link is broken** 


However, it is working for some other pages:
<img width="114" alt="image" src="https://github.com/SSWConsulting/SSW.Website-v3/assets/71385247/03217c4e-15f2-49a8-a84f-6c8dee693671">
**Figure: List of pages that contain that image.**
