### ISSUE TITLE
✨ Tina - Click to edit visual editing

### ISSUE THREAD

**Issue by bradystroud** [SSWConsulting/SSW.Website#704]
See https://tina.io/docs/contextual-editing/react/#click-to-edit-experimental

- [x] Investigate on how we can implement this for our website
- [x] List down all the templates that need to be modified in the milestone https://github.com/SSWConsulting/SSW.Website/milestone/3

**Comment by amankumarrr** [comment]
@bradystroud @wicksipedia 

For this change, we need to update our UI rendering components for each template. I have updated the list of templates in the milestone. 
Tasks for this issue have been achieved therefore closing this issue.
