### ISSUE TITLE
💄 - Home page - Carousel image 

### ISSUE THREAD

**Issue by amankumarrr** [SSWConsulting/SSW.Website#716]
URL: https://www.ssw.com.au

### Description:
With our homepage carousel, objects and texts are little blurred out.

### Expected:
Text and objects should be clear and zoomed in. 

### Screenshot:
<img width="677" alt="BannerImage" src="https://github.com/SSWConsulting/SSW.Website-v3/assets/71385247/f68d6cff-d6c9-42f9-aca1-f8743af3e3a2">

**Figure: Matt & Camilla looks blurred out with text on left**

**Comment by hveraus** [comment]
As per conversation with Brady, Ken will reproduce the banner images and will try to update them on Tina
