### ISSUE TITLE
📈 Install Microsoft Clarity to SSW.Website

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.Website#722]
Hi team,

1. Copy and paste the Clarity code into the <head> element of ssw.com.au

```
<script type="text/javascript">
    (function(c,l,a,r,i,t,y){
        c[a]=c[a]||function(){(c[a].q=c[a].q||[]).push(arguments)};
        t=l.createElement(r);t.async=1;t.src="https://www.clarity.ms/tag/"+i;
        y=l.getElementsByTagName(r)[0];y.parentNode.insertBefore(t,y);
    })(window, document, "clarity", "script", "hc5fifvc4q");
</script>
```

More info: https://www.youtube.com/watch?v=xGcQl4jTIXQ

**Comment by bradystroud** [comment]
Try follow these steps 
https://learn.microsoft.com/en-us/clarity/third-party-integrations/google-tag-manager#option-1-install-clarity-on-gtm-recommended-method

**Comment by wicksipedia** [comment]
This was done with GTM (just took a while for it to kick in)

![CleanShot 2023-06-20 at 10 08 19](https://github.com/SSWConsulting/SSW.Website/assets/600044/4a0d6f71-1a26-48fa-9842-08789be7ec79)

**Comment by amankumarrr** [comment]
@camillars @wicksipedia @bradystroud 

As per my conversation with @tiagov8 and @bradystroud, it appears that we are currently utilizing Microsoft Clarity on our website. During my investigation, I discovered that we have included the Clarity script within the Google Manager tags, which is responsible for loading the Clarity script. Therefore, this issue has been closed!





![Image](https://github.com/SSWConsulting/SSW.Website/assets/71385247/936a93be-c91a-41e7-b287-5f1468975884)

**Figure: SSW website with Clarity Tag**



![Image](https://github.com/SSWConsulting/SSW.Website/assets/71385247/768874ca-1375-4527-8e7d-bb96a3191b2d)

**Figure: Clarity script with Google Analytics Tag**

**Comment by tiagov8** [comment]
As per email thread: **Re: Testing Clarity (HotJar's alternative from Microsoft)**

The Marketing team already have access to Clarity data ✅
