### ISSUE TITLE
✨ Suggestion - Home page massive icon

### ISSUE THREAD

**Issue by christoment** [SSWConsulting/SSW.Website#735]
Looking at the home page we have massive social media icon on top - I think this takes too much screen for useful information (roughly 15% of the screen!)

<img width="1726" alt="image" src="https://github.com/SSWConsulting/SSW.Website-v3/assets/35278147/8515249d-b785-4a94-81e6-704ec622239b">

Smaller icons or use this space for something else...

**Comment by wicksipedia** [comment]
Closing this issue. With the new megamenu, these icons are now in the footer
