### ISSUE TITLE
✨ Suggestion - Better YouTube Thumbnail quality

### ISSUE THREAD

**Issue by christoment** [SSWConsulting/SSW.Website#738]
https://www.ssw.com.au/consulting/azure

The consulting page's YouTube thumbnail has a pixelated image...

<img width="1727" alt="image" src="https://github.com/SSWConsulting/SSW.Website-v3/assets/35278147/2c80f2a8-c0a3-40bf-9b24-e06e2631b17c">

We should increase the quality to make them a bit sharp (or at least the pixel is not noticeable) if possible

**Comment by bradystroud** [comment]
As per my conversation with @pierssinclairssw the popup UX is weird and unintuitive.

- [x] Embed most of the videos normally (no popup)
- [x] Ensure thumbnail quailty is good
- [ ] Ensure player has a duration time code (e.g. 1:35)
- [x] Make the play button more visible 
- [x] For the small videos e.g. on the home page, use the current popup UX

![image](https://github.com/SSWConsulting/SSW.Website/assets/38869720/6368faa0-670c-4f9a-9128-858d3a2981af)
**Figure: good example of a play button - very visible**

Although this is inconsistent, the experience will be much better on the majority of the pages.

**Comment by Jord-Gui** [comment]
As per my conversation with @bradystroud, we no longer need to use the popup UX for small videos as the users can full screen it using the default YouTube controls.

**Comment by Jord-Gui** [comment]
As per my conversation with @bradystroud , the thumbnail duration timecode will be done via api call as opposed to a TinaCMS optional text field

**Comment by Jord-Gui** [comment]
Following discussion with @bradystroud and @Harry-Ross , putting this back into backlog so that we can focus on moving pages from old server. Figure out thumbnail timestamp thing later.

**Comment by wicksipedia** [comment]
closing as original issue has been done - moved the duration task to a separate issue #1620
