### ISSUE TITLE
🐛 - Mobile view - Menu - Clicking on chevron icon itself does not toggle the menu

### ISSUE THREAD

**Issue by KostaMadorsky** [SSWConsulting/SSW.Website#739]
**Describe the bug**
When you open the website on mobile, clicking on the chevron icon itself does nothing.

**To Reproduce**
1. Open mobile view
2. Open the menu
3. Click on the chevron icon

**Expected behavior**
The menu section is toggled.

**Screenshots/Video**

![3641d3b9-477b-4c07-bc85-b1ec277efe3d](https://github.com/SSWConsulting/SSW.Website-v3/assets/9411729/31667e91-dea8-4192-9a68-fdd3b255ad0a)

**Comment by wicksipedia** [comment]
Closing this issue. New megamenu does not have this issue
