### ISSUE TITLE
🐛 - Mobile view - Upcoming events - items do not fit

### ISSUE THREAD

**Issue by KostaMadorsky** [SSWConsulting/SSW.Website#740]
**Describe the bug**
Mobile view - Upcoming events - items do not fit

**To Reproduce**
1. Open mobile view
2. Check upcoming events

**Expected behavior**
Everything should fit.

**Screenshots/Video**
![9ccc396c-22ec-43a2-91ca-d8e48a3bc591](https://github.com/SSWConsulting/SSW.Website-v3/assets/9411729/6fd68c99-4fa9-4a5b-8637-f2eea8793be6)

**Comment by amankumarrr** [comment]
@wicksipedia @bradystroud 

This bug has been resolved by this issue #1148, we redesigned the events component.



![Image](https://github.com/SSWConsulting/SSW.Website/assets/71385247/076e7be1-46e4-4719-8574-cf3e174b077c)

**Figure: New events design in mobile view**
