### ISSUE TITLE
consulting/react text is too small

### ISSUE THREAD

**Issue by BrookJeynes** [SSWConsulting/SSW.Website#749]
CC: @bradystroud @adamcogan 

URL: https://ssw.com.au/consulting/react

The text seems to small and out of place, it would be great if it could be doubled or made larger please.

**Screenshots**
![Screenshot 2023-06-05 at 14 56 52](https://github.com/SSWConsulting/SSW.Website-v3/assets/25432120/2de63daf-b836-4161-bc64-d68229b7b7eb)
**Figure: Body text is too small**

**Comment by tiagov8** [comment]
Hi Team, 

> The text seems to small and out of place, it would be great if it could be doubled or made larger please.

The body size should be 18px (slightly bigger than the minimun recommended 16px)

The paragraph padding should be set to `padding: 0;`
The paragraph margin should be set to `margin: 1rem 0;` 

1. Please ping me on Teams if you need help adjusting these ;)
