### ISSUE TITLE
💄 Newsletter Signup - implement redesign

### ISSUE THREAD

**Issue by wicksipedia** [SSWConsulting/SSW.Website#755]
Reskin newsletter sign up component to look like

![Image](https://github.com/SSWConsulting/SSW.Website/assets/600044/ea72c10c-d5ec-456e-b86b-5a45cfbfad6c)

Note: should be able to use Tina to drop component on other pages e.g. home page

**Comment by KristenHu** [comment]
As we already have #707 to update the styling for Newsletter, this issue can be closed.
The description above has been added to #707

**Comment by wicksipedia** [comment]
This is for the signup component as priority. The other issue is for the whole page
