### ISSUE TITLE
🐛  Home Page | Contact Us - NSW shows Sydney but not Newcastle

### ISSUE THREAD

**Issue by bradystroud** [SSWConsulting/SSW.Website#760]
**Describe the bug**

![image](https://github.com/SSWConsulting/SSW.Website/assets/38869720/f9cfa77e-1e2e-4392-b599-6e8aec556397)

**To Reproduce**
1. Go to home page
2. Scroll to `Contact Us`
3. Click NSW state
4. Only Sydney is expanded, not Newcastle 😕

**Expected behavior**
Syd and Newcastle states are expanded

**Comment by amankumarrr** [comment]
@bradystroud @wicksipedia  

![ezgif com-optimize](https://github.com/SSWConsulting/SSW.Website/assets/71385247/6feb2b90-4b3b-45b2-9ca1-75418b519b43)

**GIF: Toggles on hovering map and tabs**
