### ISSUE TITLE
👨‍⚖️ Contact form - follow DRY and avoid repetition on labels

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.Website#763]
URL: E.g. Click button on https://www.ssw.com.au/consulting/mobile-application-development

1. Can we remove the word "Your" from all these input labels?

as per https://www.ssw.com.au/rules/avoid-repetition/ 

<img width="780" alt="Screenshot 2023-06-06 at 11 19 47 AM" src="https://github.com/SSWConsulting/SSW.Website/assets/12601228/090c4f0a-e0bf-405f-ab9a-ca8b598d1c61">

**Comment by wicksipedia** [comment]
This should be done in conjunction with #1619

**Comment by amankumarrr** [comment]
Closing this as the form is handled by JotForm and done with #1619
