### ISSUE TITLE
♻️ Embedded video thumbnail quality

### ISSUE THREAD

**Issue by bradystroud** [SSWConsulting/SSW.Website#771]
**Describe the bug**
We have had a lot of feedback saying the video thumbnails are too low quality. 

https://ssw.com.au/consulting/blazor

```[tasklist]
### Tasks
- [x] Discuss the current approach to embedding videos with a designer (whether we can should make it embedded and not as a popup)
- [x] Investigate if we can increase thumbnail quality without dropping SEO
```

![image](https://github.com/SSWConsulting/SSW.Website/assets/38869720/65c2310a-3e80-481d-89a2-009d03f810ac)
**Figure: low quality thumbnail**

**Comment by Jord-Gui** [comment]
One potential fix for the thumbnail quality is to explicitly give a thumbnail image, as this gives a nice and crisp thumbnail.
![image](https://github.com/SSWConsulting/SSW.Website/assets/41951199/1d2097a7-f23d-46ed-8e23-0883812427d5)
![image](https://github.com/SSWConsulting/SSW.Website/assets/41951199/cb4276c0-0b34-4dc8-bf67-53100f8f5dba)

**Comment by Jord-Gui** [comment]
As discussed with Brady and Joseph:
- We will be keeping the videos as is (with popup) as we want it to be consistent throughout and the popup version is to cater for smaller videos e.g., https://www.ssw.com.au/training/internship-fullstack

**Comment by piers-sinclair** [comment]
@Jord-Gui 

I think we should remove the pop-up. It's a super weird UX.

I went to 3 separate news websites and none of them use a pop-up

https://www.aljazeera.com/program/africa-direct/2023/7/4/a-future-with-fish-a-budding-fish-farmer-in-niger
https://www.theguardian.com/australia-news/video/2023/jul/07/anthony-albanese-says-robodebt-was-a-gross-betrayal-and-a-human-tragedy-video
https://www.abc.net.au/news/2023-07-07/robodebt-royal-commission-final-report-live-updates/102488602

**Comment by bradystroud** [comment]
@pierssinclairssw thanks for the feedback - it will be actioned as part of [#738](https://github.com/SSWConsulting/SSW.Website/issues/738)
