### ISSUE TITLE
💸 UI Tech Debt - CSS - Headings sizes are not ideal

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.Website#804]
cc @hveraus 

Hi team, 

H4 is currently in the same size as a H2... 🤯

1. I suggest we follow the exact font sizes from: https://getbootstrap.com/docs/5.0/content/typography/
2. Just make H1, H2, and H3 in SSW red - H4 and smaller are in the same color as the regular paragraphs

**Note:** This may require changing some heading here and there to make them look better

Example... On offices addresses links H4 the font is clearly too big...

<img width="920" alt="Screenshot 2023-06-13 at 3 51 02 PM" src="https://github.com/SSWConsulting/SSW.Website/assets/12601228/2faf578e-e168-4374-92d4-26eb4f89c1df">

**Comment by tiagov8** [comment]
Related to https://github.com/SSWConsulting/SSW.Website/issues/1473

**Comment by amankumarrr** [comment]
@tiagov8
this has been addressed in #1473 therefore closing this.

**Comment by amankumarrr** [comment]
@tiagov8 @wicksipedia @bradystroud 

I've noticed that the modifications I made to address issue #1473 haven't affected the `/offices/*` pages. This is likely because we're utilizing the `prose` class and setting styles in the base `style.css`, which is conflicting with the styles from `tailwind.config.css`. This inconsistency significantly impacts the entire site. To resolve this, we need to thoroughly clean up the styling and ensure consistency across the entire website.

**Comment by Harry-Ross** [comment]
* Made prose styles more consistent across pages
  * Removed a lot of custom overrides for `@tailwindcss/typography` to simplify new dev experience, and align to the reasonable defaults intended by the use of the `prose` class 
  * Condensed number of prose overrides, as employment and consulting were the same

![image](https://github.com/SSWConsulting/SSW.Website/assets/20507092/7b02bd9a-65bb-4eff-b663-e7e47cbc8ed1)
**Figure: `/` before**

![image](https://github.com/SSWConsulting/SSW.Website/assets/20507092/cf1600d4-a8ea-420d-b86e-93e3fc3f940e)
**Figure: `/` after**

![image](https://github.com/SSWConsulting/SSW.Website/assets/20507092/6a4c136d-616d-44e9-a62a-f8681cb144c0)
**Figure: `/terms-and-conditions` before**

![image](https://github.com/SSWConsulting/SSW.Website/assets/20507092/319717f7-fa8d-447d-9b78-05dc6d9c5e46)
**Figure: `/terms-and-conditions` after**

![image](https://github.com/SSWConsulting/SSW.Website/assets/20507092/f144b1ed-1ba2-4c46-bb8d-fb2c1e8a85b8)
**Figure: `/offices/hangzhou` before**

![image](https://github.com/SSWConsulting/SSW.Website/assets/20507092/9ae4fb2f-305c-47bc-9c0e-5469b60ed029)
**Figure: `/offices/hangzhou after**

![image](https://github.com/SSWConsulting/SSW.Website/assets/20507092/4843da14-fd3c-494d-aaf1-f672ea23f9ef)
**Figure: `/industry/educational` before**

![image](https://github.com/SSWConsulting/SSW.Website/assets/20507092/8d79f33a-5d89-48d4-8951-8ce92b6ea060)
**Figure: `/industry/educational` after**

![image](https://github.com/SSWConsulting/SSW.Website/assets/20507092/831181e7-e2f4-4fe2-ab40-33504325a81c)
**Figure: `/consulting/angular` before**

![image](https://github.com/SSWConsulting/SSW.Website/assets/20507092/4c824d1b-fdab-4174-b59c-9938fedb99b0)
**Figure: `/consulting/angular` after (neglible change here)**
