### ISSUE TITLE
💸 Markup Tech Debt - How come our Logo section is a Heading 4?

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.Website#805]
Hi team, 

Inspecting a page I noticed the SSW logo is a H4... any reason?

1. Can we make it a normal `<div>` which semantically makes more sense ?

<img width="449" alt="Screenshot 2023-06-13 at 4 04 34 PM" src="https://github.com/SSWConsulting/SSW.Website/assets/12601228/e0a58df4-5a11-45b2-b56c-695f17b7ebc3">

```[tasklist]
### Tasks
- [x] Change logo to a div, not heading
- [x] Ensure styling doesn't change
```

**Comment by bradystroud** [comment]
Oops - didn't mean to close it 🤦🏻‍♂️

**Comment by bradystroud** [comment]
related to #804 and https://github.com/SSWConsulting/SSW.Website/issues/1473
