### ISSUE TITLE
📄Docs - Wiki Page for Components

### ISSUE THREAD

**Issue by Harry-Ross** [SSWConsulting/SSW.Website#818]
At the moment, when you press the "embed" button on Tina, it won't give you a preview or description of what each component is. It would be good if there was a piece of documentation describing some/all of the components available to users.

![Image](https://github.com/SSWConsulting/SSW.Website/assets/20507092/b1f009d7-4eba-49f9-a056-cd47a1b50def)
**Figure: The "Embed" button in the Tina rich text edtior**

```[tasklist]
### Tasks
- [x] Write a wiki page listing components that can be used in the Tina rich text editor
```

**Comment by jackreimers** [comment]
https://github.com/SSWConsulting/SSW.Website/wiki/Available-Tina-Components
Wiki article has been reviewd by @amankumarrr
