### ISSUE TITLE
Improve SSW Internship page

### ISSUE THREAD

**Issue by BrookJeynes** [SSWConsulting/SSW.Website#822]
CC: @PennyWalker @bradystroud @Ben0189 

URL: https://www.ssw.com.au/training/fullstack

Hey team,

As per my email from Penny,

- [x] Can we change the URL
    From:
        fullstack
    To:
        internship-fullstack
- [x] Add “SSW Internship” as a heading above the “Who should apply… etc ”
    ![image](https://github.com/SSWConsulting/SSW.Website/assets/25432120/fe2be9f9-f20f-4ec4-9842-57a7041b3a27)
    **Figure: Add SSW Internship here**
- [x] In the “Who should apply” section. Change
    From:
        People looking to upskill
    To:
        People looking for work experience
- [x] Add referrals we got from Brady and Ben
    - Ben Neoh - "The SSW Internship was the perfect starting point for me with no prior knowledge. It provided invaluable hands-on experience and helped me develop both my technical skills and soft skills."
    - Brady Stroud - "The SSW internship was an incredible experience. I not only sharpened my coding skills, but also acquired valuable soft skills to excel in client projects."
- [x] Add a link to our Firebootcamp course: the [SSW | Become a World Class Beginner .NET Developer in 9 Weeks (firebootcamp.com)](https://firebootcamp.com/)
- [x] Explain that FireBootCamp is something that successful interns will get - Under "What you will get?", write "You get FireBootCamp course for free"
- [x] Get the wording around the link checked by Seth

~~- [] Send a test please to Adam, call to get his feedback~~
* Not done, as was checked by Piers and Seth

1. This page should also filter out interns who haven't got the right experience. Add some "Entry Requirements" including
* Relational Database Design e.g. ERDs and Normalization
* Object Oriented Programming
* Basic SQL Querying

**Comment by piers-sinclair** [comment]
I feel like this page would be better if it filtered out interns who haven't got the right experience @BrookJeynes @UlyssesMaclaren @PennyWalker @lukecookssw @william-liebenberg 

I think we should add some "Entry Requirements" including
Relational Database Design e.g. ERDs and Normalization
Object Oriented Programming
Basic SQL Querying

**Comment by UlyssesMaclaren** [comment]
> I feel like this page would be better if it filtered out interns who haven't got the right experience @BrookJeynes @UlyssesMaclaren @PennyWalker @lukecookssw @william-liebenberg
> 
> I think we should add some "Entry Requirements" including Relational Database Design e.g. ERDs and Normalization Object Oriented Programming Basic SQL Querying

Agreed... I've added it to the description

**Comment by piers-sinclair** [comment]
Hi @Harry-Ross 

As per our conversation, 

1. Change the "Who should apply?" section

From
- University students studying an IT degree
- Recent university graduates
- People looking to upskill

To
- University students or graduates
  - Computer Science degree or equivalent
- People with the following skills:
  - Relational database design
  - Basic SQL querying
  - Object-oriented programming
  - Basic JavaScript 

To @pierssinclairssw 

1. Make rules for these technical skills that we can link to.
