### ISSUE TITLE
✨ Terms and Conditions template - Click to edit visual editing

### ISSUE THREAD

**Issue by amankumarrr** [SSWConsulting/SSW.Website#840]
Feature: https://tina.io/docs/contextual-editing/react/#click-to-edit-experimental
URL: https://ssw.com.au/terms-and-conditions 
Route: `/terms-and-conditions`

#### Description:
Tina introduced a new exciting feature where user can edit the content by simply clicking on it, we need to implement this feature for our website and need to ensure that we follow this for our upcoming templates.

**Comment by KristenHu** [comment]
The feature has been added to the editable part, this issue can be closed.


![Image](https://github.com/SSWConsulting/SSW.Website/assets/52522913/a9461edf-b148-446a-a2f4-0284cf8648f2)
