### ISSUE TITLE
✨ Training template - Click to edit visual editing

### ISSUE THREAD

**Issue by amankumarrr** [SSWConsulting/SSW.Website#843]
Feature: https://tina.io/docs/contextual-editing/react/#click-to-edit-experimental
URL: https://ssw.com.au/training/fullstack 
Route: `training/fullstack`

#### Description:
Tina introduced a new exciting feature where user can edit the content by simply clicking on it, we need to implement this feature for our website and need to ensure that we follow this for our upcoming templates.

**Comment by Harry-Ross** [comment]
This PBI is blocked by #895 - several schema changes made that should be reflected in the visual editing.
