### ISSUE TITLE
✨ New Feature - TinaCMS Search

### ISSUE THREAD

**Issue by Harry-Ross** [SSWConsulting/SSW.Website#845]
As per https://tina.io/docs/reference/search/overview/, there is a global config flag to enable search in all collections. 

```[tasklist]
### Tasks
- [x] Get token from TinaCMS dashboard
- [x] Enable search in `config.tsx`
```

**Comment by amankumarrr** [comment]
Search feature has been added to Tina, now we can search on content and files under particular collection.

![Image](https://github.com/SSWConsulting/SSW.Website/assets/71385247/333bce0d-af04-451d-b016-cc3eaa272076)

**Figure: Tina with search field**
