### ISSUE TITLE
💄UI - UtilityButton Not Consistent with Booking Button

### ISSUE THREAD

**Issue by Harry-Ross** [SSWConsulting/SSW.Website#850]
As per my conversation with @amankumarrr, the UtilityButton element looks odd + inconsistent with the booking button. We agreed that it needs an increase in x padding. 

```[tasklist]
### Tasks
- [ ] Replicate the padding on the booking button for the UtilityButton element
```

**Comment by Jord-Gui** [comment]
@Harry-Ross are you able to add screenshots to this?

**Comment by Jord-Gui** [comment]
http://localhost:3000/employment
![image](https://github.com/SSWConsulting/SSW.Website/assets/41951199/748b75d4-b06c-438b-a2db-abecc430d75f)

padding left and right should look more like below:

http://localhost:3000/consulting/react
![image](https://github.com/SSWConsulting/SSW.Website/assets/41951199/7913f66f-42c2-4f43-a8a9-64ab6d3c77c7)

**Comment by Jord-Gui** [comment]
Done
