### ISSUE TITLE
💄FR | Mobile - Increase SSW logo size

### ISSUE THREAD

**Issue by cvionnet** [SSWConsulting/SSW.Website#852]
URL: https://ssw.fr/fr/

SSW logo looks tiny on mobile

**Screenshots**
![image](https://github.com/SSWConsulting/SSW.Website/assets/46954368/0e963391-305a-4ac8-b41d-33abdf53fd28)
Figure: SSW Europe home page displayed on mobile

**Comment by bradystroud** [comment]
Nice spot! @cvionnet 🔎

Unfortunately this backlog is just for the Australian site (https://www.ssw.com.au)

@tiagov8 @JeanThirion  Where is the best spot for this feedback?

**Comment by tiagov8** [comment]
Hey @cvionnet 

Done - Logo is now in a reasonable size in any screen: https://ssw.fr/

SSW.Europe.Website tasks can be added here: https://dev.azure.com/ssw/SSW.Europe.Website/ OR if simple sent via email

Cheers,
