### ISSUE TITLE
⚡️ Slow Page load bug caused by v1 website outage

### ISSUE THREAD

**Issue by bradystroud** [SSWConsulting/SSW.Website#856]
Aman and I noticed the website was taking a long time to load. 
We did a bit of investigating and found that getting the SharePoint events data for the livestream banner is blocking the page load, and was taking up to 2 mins. it doesnt usually take this long, we think the v1 Website had a short outage.

```[tasklist]
### Tasks
- [ ] This call should not block page load - refactor 
- [ ] If we cant get the events data, the livestream banner should just be hidden (its not part of the core functionality of the page)
``` 

![Image](https://user-images.githubusercontent.com/38869720/248123854-3d47895c-5cd5-4842-9f57-bba4194f7c01.png)
**FIgure: App Insights - livestream data took 2 min to load**

![Image](https://user-images.githubusercontent.com/38869720/248126139-33759cf0-d1ee-4461-a4d1-2038ea7ed424.png)
**FIgure: Response time spiked for ~10min**

**Comment by Harry-Ross** [comment]
Closed by #879 - events data has been migrated to a NextJS API
