### ISSUE TITLE
🚨 App Insights - Fix 404s

### ISSUE THREAD

**Issue by bradystroud** [SSWConsulting/SSW.Website#862]
There are lots of 404s in App Insights. We have already fixed the important ones (MegaMenu images and /Employment)

```[tasklist]
### Tasks
- [x] Investigate and fix these
```

**Comment by amankumarrr** [comment]
@bradystroud @adamcogan 

After Investigate, I found this route `https://www.ssw.com.au/ssw/Employees/employeesprofile.aspx` that was giving 404 issue, which I have redirected to https://www.ssw.com.au/people - https://github.com/SSWConsulting/SSW.FrontDoor/pull/53

![Image](https://github.com/SSWConsulting/SSW.Website/assets/71385247/158ed894-bbc0-4447-9c82-540818b12217)
**Figure: Employeesprofile showing error in appInsight logs** 

All the major routes have been successfully redirected to the new SSW website. therefore, closing this issue.
