### ISSUE TITLE
🐛 Video Produciton page linking to iteslf

### ISSUE THREAD

**Issue by bradystroud** [SSWConsulting/SSW.Website#869]
**Describe the bug**
On https://www.ssw.com.au/consulting/video-production there are some cards that should link to different pages. All the links go to the same page

![image](https://github.com/SSWConsulting/SSW.Website/assets/38869720/20f5b72a-1362-4b68-b36a-2007b08089f1)

This is because when this page was migrated from the old website, a redirect was added in Front Door for everything on the /Video-Production path. The pages it is trying to link to are under /Video-Production e.g. https://www.ssw.com.au/ssw/Consulting/Video-Production/Video-Production-Content-Marketing.aspx

https://github.com/SSWConsulting/SSW.FrontDoor/blob/f27aaa3a99d3f1117e975fc5b68a1aac9863fd05/Redirects/static-redirects.json#L449-L452

The redirect is making these other pages inaccessible.

```[tasklist]
### Tasks
- [x] Fix redirect
- [x] Make PBIs to migrate the remaining pages
```

**Comment by amankumarrr** [comment]
@bradystroud 
Fixed the route in the front door repo - https://github.com/SSWConsulting/SSW.FrontDoor/pull/54.

Created issues for all the pages that need to be migrated:
#880, #881, #882, #883, #884, #885
