### ISSUE TITLE
📄 Checklist for working on PowerAutomate

### ISSUE THREAD

**Issue by bradystroud** [SSWConsulting/SSW.Website#876]
**Is your feature request related to a problem? Please describe.**
Right now, when someone starts on a PA flow change they dont know where to start and ask for help.

**Describe the solution you'd like**
A wiki/checklist that explains what you need access to and where to start developing PA flows for the website.

```[tasklist]
### Tasks
- [x] Write the docs
- [x] Get a dev who hasnt worked on PA before to test it
```

I think it should go in our wiki. This is public, so ensure there are no keys/passwords in there

**Comment by amankumarrr** [comment]
@bradystroud 
I tested it with @johnxu77 as he's currently working on modifying the existing flow, and incorporated his feedback, therefore, I'm closing this issue .
