### ISSUE TITLE
🐛 Error message when uploading a image with duplicated file name

### ISSUE THREAD

**Issue by hveraus** [SSWConsulting/SSW.Website#921]
**Describe the bug**
When uploading a image, if there is a image with same name in the media manager, you will get this error message

![ef49c8c7-5861-47d8-8faf-d2daa33534b1](https://github.com/SSWConsulting/SSW.Website/assets/4745861/55f9d9ea-a570-4309-aa2d-3bf7243639ae)
Figure: error message

<img width="931" alt="Screenshot 2023-07-03 at 1 58 18 PM" src="https://github.com/SSWConsulting/SSW.Website/assets/4745861/f578c2b0-08bf-4d91-9057-08a4074f2544">
Figure: Consult screenshot when uploading image

**To Reproduce**
1. upload a image with the same file name as one already in the media manager

**Expected behavior**
A clear message to show user the name is taken

**Comment by bradystroud** [comment]
Thanks @hveraus 

I created a bug on the Tina repo to fix this 
https://github.com/tinacms/tinacms/issues/4059

There is nothing we can do on our end
