### ISSUE TITLE
♻️  Terms and Conditions - Table Component Adjusted to JSON object

### ISSUE THREAD

**Issue by Harry-Ross** [SSWConsulting/SSW.Website#933]
**Is your feature request related to a problem? Please describe.**
As per my conversation with @pierssinclairssw , the terms and conditions table editor is highly unintuitive for non-devs, as it is a textbox with a markdown table. 

**Describe the solution you'd like**
Convert the table input value to a JSON object in the schema, to allow it to be easier edited in TinaCMS. 

**Additional context**
![image](https://github.com/SSWConsulting/SSW.Website/assets/20507092/d40d00fc-4884-40db-a183-a1400471678c)
**Figure: What is displayed in TinaCMS**

Linked to #939

**Comment by Harry-Ross** [comment]
As per my conversation with @bradystroud, the nested object component does not work with a regular <TinaMarkdown> element, so it can only be used as a block element. This is annoying, as it means we will need have to have 2 separate implementations, one with the new object way of doing it, and one with the previous ugly way of doing it for use on `/consulting/software-audit`.

I have filed a help request with the TinaCMS team in their Discord server here: https://discord.com/channels/835168149439643678/1126746374021595217

They have said that they are researching a fix, or it may be fixed in their mentioned PR...

**Comment by bradystroud** [comment]
done video - https://youtu.be/sWdLPnhit0E
