### ISSUE TITLE
📄 Consulting index - Improve Web Design image

### ISSUE THREAD

**Issue by bradystroud** [SSWConsulting/SSW.Website#949]
@jaydenalchin @tiagov8

URL: https://ssw.com.au/consulting

The image for the web design service on https://ssw.com.au/consulting is bad

I like the Product Design image

![SCR-20230706-hkvq](https://github.com/SSWConsulting/SSW.Website/assets/38869720/eaa2c2a6-46a4-4446-a608-f5b044e8c97a)
Figure: This image should be replaced

**Comment by tiagov8** [comment]
Designers backlog: 



ID | Work Item Type | Title | State | Effort | Iteration Path | Assigned To
-- | -- | -- | -- | -- | -- | --
[81960](https://ssw.visualstudio.com/SSW.Design/_workitems/edit/81960) | Product Backlog Item | 📄 Consulting index - Improve Web Design image | New | 2 | SSW.Design |

**Comment by wicksipedia** [comment]
closing this as it was done, but not closed
