### ISSUE TITLE
✨ Add characters limitation + relevant SEO instructions next to titles in Tina CMS

### ISSUE THREAD

**Issue by camillars** [SSWConsulting/SSW.Website#950]
**Hi team** 👋

1. please change
from
   Title 
to
   Title (70 characters)

2. please change
from
   Description
to 
   Description (150 characters)

![image](https://github.com/SSWConsulting/SSW.Website/assets/53064613/d31b29f0-fc0a-4291-9fa3-30725f7587ee)
**Figure: fields that need an update**

**Comment by bradystroud** [comment]
Hey @camillars I did some research and looks like we can add validation to these fields
https://tina.io/docs/extending-tina/validation/

This would enforce the 70 char limit

What do you think about doing this as well?

**Comment by camillars** [comment]
> Hey @camillars I did some research and looks like we can add validation to these fields https://tina.io/docs/extending-tina/validation/
> 
> This would enforce the 70 char limit
> 
> What do you think about doing this as well?

Amazing, please add that too :)
