### ISSUE TITLE
✨ SEO - Tag external URLs with rel=”nofollow”

### ISSUE THREAD

**Issue by camillars** [SSWConsulting/SSW.Website#963]
Hi @bradystroud 

as per our chat, 

1. can we implement in a bulk on the website a rule to tag external URLs with rel=”nofollow” as per https://www.ssw.com.au/rules/seo-nofollow/?

Thanks,
Camilla

**Comment by amankumarrr** [comment]
@camillars @bradystroud 
Done - Added `nofollow` for all external links except for `/rules`, `/people`, `/ssw` and `ssw.tv`.
