### ISSUE TITLE
💄 User Group Page - Improve Design

### ISSUE THREAD

**Issue by hveraus** [SSWConsulting/SSW.Website#997]
URL - https://www.ssw.com.au/ssw/NETUG/Sydney.aspx

**Is your feature request related to a problem? Please describe.**
The current user group page is too crowed and hard to read, does not has clear call to action and not mobile friendly. 

**Describe the solution you'd like**
Please see  [Done Video - Design Mockup for SSW Event User Group Page V2](https://www.youtube.com/watch?v=ZjV8r2zmIGc) and Figma | SSW.Website V3 | Events Pages | SSW/UG page

**Key features**
1. New layout: follow internship page's design guide
2. New library of presenters: we can just pick one for the hero banner
3. Register form: need some backend development
4. 3 status of hero banner: upcoming event, on going event, after event
5. Share event: need a third-party service
6. Join us as a presenter: link to an online form
7. Latest Tech Banner: any chance we can make the tech icons animated and clickable?

**Additional context**
Please note: there might be some minor change and text refinement still coming, e.g. text size, padding and margin refinement.

**Comment by bradystroud** [comment]
A nice screenshot from Kens [Done Video](https://www.youtube.com/watch?v=ZjV8r2zmIGc)

<img width="511" alt="image" src="https://github.com/SSWConsulting/SSW.Website/assets/38869720/123ffc54-78a2-406a-84af-541e67004788">

**Comment by wicksipedia** [comment]
closing as done
